/**********************************************************************/
/*                                                                    */
/*  File name : DEXPO.H                                               */
/*  Date      : 03.09.2019 11:31:40                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : sat2017                                    */
/*  ISaGRAF program name : DEXPO                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_DEXPO_TMPB1	0X00D5

/* Analogs */

#define _SCC_DEXPO_DEXPO	0X01B6
#define _SCC_DEXPO_EXP_	0X01B7
#define _SCC_DEXPO_SP_	0X01B8
#define _SCC_DEXPO_PV_	0X01B9
#define _SCC_DEXPO_LO	0X01BA
#define _SCC_DEXPO_D_	0X01BB
#define _SCC_DEXPO_TMPR1	0X0204
#define _SCC_DEXPO_TMPR3	0X0205
#define _SCC_DEXPO_TMPR2	0X02FB
#define _SCC_DEXPO_TMPR4	0X02FC

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */















