/**********************************************************************/
/*                                                                    */
/*  File name : GASPUMP.H                                             */
/*  Date      : 03.09.2019 11:31:40                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : sat2017                                    */
/*  ISaGRAF program name : GASPUMP                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_GASPUMP_CTRL	0X007E
#define _SCC_GASPUMP_GP3	0X007F
#define _SCC_GASPUMP_GP2	0X0080
#define _SCC_GASPUMP_GP	0X0081
#define _SCC_GASPUMP_ED1_6EB18C01_Q_VA	0X00B2
#define _SCC_GASPUMP_ED1_6EB18C00_Q_VA	0X00B3
#define _SCC_GASPUMP_ED1_6EB18BFF_Q_VA	0X00B4
#define _SCC_GASPUMP_ED1_6EB18BFD_B3__VA	0X00B5

/* Analogs */

#define _SCC_GASPUMP_S001	0X01A3
#define _SCC_GASPUMP_W004	0X01A4
#define _SCC_GASPUMP_W003	0X01A5
#define _SCC_GASPUMP_W002	0X01A6
#define _SCC_GASPUMP_W001	0X01A7
#define _SCC_GASPUMP_W005	0X01A8
#define _SCC_GASPUMP_TMPR2	0X020F
#define _SCC_GASPUMP_ED1_6EB18C01_N4__VA	0X025E
#define _SCC_GASPUMP_ED1_6EB18C01_N3__VA	0X025F
#define _SCC_GASPUMP_ED1_6EB18C01_N2__VA	0X0260
#define _SCC_GASPUMP_ED1_6EB18C01_N1__VA	0X0261
#define _SCC_GASPUMP_ED1_6EB18BFF_N1__VA	0X0262
#define _SCC_GASPUMP_ED1_6EB18BFE_N1__VA	0X0263

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












#define _SCC_GASPUMP_ED1_6EB18C00	0X0001

#define _SCC_GASPUMP_ED1_6EB18C01	0X0001
#define _SCC_GASPUMP_ED1_6EB18BFF	0X0002
#define _SCC_GASPUMP_ED1_6EB18BFE	0X0003

#define _SCC_GASPUMP_ED1_6EB18BFD	0X0001

