/**********************************************************************/
/*                                                                    */
/*  File name : KALMAN.H                                              */
/*  Date      : 03.09.2019 11:31:40                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : sat2017                                    */
/*  ISaGRAF program name : KALMAN                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_KALMAN_RUN_	0X008E

/* Analogs */

#define _SCC_KALMAN_STATE	0X01A1
#define _SCC_KALMAN_STATE_	0X01A2
#define _SCC_KALMAN_XIN_	0X01C6
#define _SCC_KALMAN_F_	0X01C7

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */















