/**********************************************************************/
/*                                                                    */
/*  File name : SLOW_UP.H                                             */
/*  Date      : 03.09.2019 11:31:40                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : sat2017                                    */
/*  ISaGRAF program name : SLOW_UP                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_SLOW_UP_FIRST	0X0083
#define _SCC_SLOW_UP_RUN_	0X008D

/* Analogs */

#define _SCC_SLOW_UP_OUT_	0X01AE
#define _SCC_SLOW_UP_LOCOUT	0X01AF
#define _SCC_SLOW_UP_DELTA	0X01B0
#define _SCC_SLOW_UP_MAX_	0X01C3
#define _SCC_SLOW_UP_MIN_	0X01C4
#define _SCC_SLOW_UP_IN_	0X01C5

/* Timers */

#define _SCC_SLOW_UP_TUP_	0X0007

/* Messages */


/* Functions */


/* Function blocks */















