/**********************************************************************/
/*                                                                    */
/*  File name : DEXPO.H                                               */
/*  Date      : 20.10.2016 13:17:30                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : vip2016                                    */
/*  ISaGRAF program name : DEXPO                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */

#define _SCC_DEXPO_DEXPO	0X018E
#define _SCC_DEXPO_EXP_	0X018F
#define _SCC_DEXPO_SP_	0X0190
#define _SCC_DEXPO_PV_	0X0191
#define _SCC_DEXPO_D_	0X0192
#define _SCC_DEXPO_TMPR2	0X01C5
#define _SCC_DEXPO_TMPR3	0X01C6
#define _SCC_DEXPO_TMPR4	0X028E
#define _SCC_DEXPO_TMPR1	0X028F

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












