/**********************************************************************/
/*                                                                    */
/*  File name : PIDMY.H                                               */
/*  Date      : 20.10.2016 13:17:30                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : vip2016                                    */
/*  ISaGRAF program name : PIDMY                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PIDMY_REJ	0X0084
#define _SCC_PIDMY_REJ_	0X0085
#define _SCC_PIDMY_MODE_	0X008B
#define _SCC_PIDMY_FIRSTRUN	0X008C
#define _SCC_PIDMY_AUTO_	0X008D

/* Analogs */

#define _SCC_PIDMY_KE_	0X017C
#define _SCC_PIDMY_SUM_	0X017D
#define _SCC_PIDMY_XT_	0X017E
#define _SCC_PIDMY_SUM0_	0X017F
#define _SCC_PIDMY_XOUT_	0X0180
#define _SCC_PIDMY_KSP_	0X0196
#define _SCC_PIDMY_KPV_	0X0197
#define _SCC_PIDMY_XMAX_	0X0198
#define _SCC_PIDMY_XMIN_	0X0199
#define _SCC_PIDMY_P0_	0X019A
#define _SCC_PIDMY_TI_	0X019B
#define _SCC_PIDMY_KP_	0X019C
#define _SCC_PIDMY_X0_	0X019D
#define _SCC_PIDMY_SP_	0X019E
#define _SCC_PIDMY_PV_	0X019F
#define _SCC_PIDMY_TMPR1	0X01C7
#define _SCC_PIDMY_TMPR4	0X01C9

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












