/**********************************************************************/
/*                                                                    */
/*  File name : SLOW_UP.H                                             */
/*  Date      : 20.10.2016 13:17:30                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : vip2016                                    */
/*  ISaGRAF program name : SLOW_UP                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_SLOW_UP_FIRST	0X0087

/* Analogs */

#define _SCC_SLOW_UP_LOCOUT	0X0181
#define _SCC_SLOW_UP_DELTA	0X0182
#define _SCC_SLOW_UP_OUT_	0X0183
#define _SCC_SLOW_UP_MAX_	0X01A0
#define _SCC_SLOW_UP_MIN_	0X01A1
#define _SCC_SLOW_UP_IN_	0X01A2

/* Timers */

#define _SCC_SLOW_UP_TUP_	0X0005

/* Messages */


/* Functions */


/* Function blocks */












