/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_8.H                                             */
/*  Date      : 15.10.2015 19:55:01                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ftest                                      */
/*  ISaGRAF program name : FL_FB_8                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_8_ED1_2067069A_BI5__VA	0X0169
#define _SCC_FL_FB_8_ED1_2067069A_BI3__VA	0X016A
#define _SCC_FL_FB_8_ED1_2067069A_BI2__VA	0X016B
#define _SCC_FL_FB_8_ED1_2067069A_BI1__VA	0X016C
#define _SCC_FL_FB_8_ED1_2067069A_Q__VA	0X016D
#define _SCC_FL_FB_8_ED1_2067069B_Q__VA	0X016E
#define _SCC_FL_FB_8_ED1_20670698_Q_VA	0X016F
#define _SCC_FL_FB_8_ED1_20670699_Q_VA	0X0170
#define _SCC_FL_FB_8_ED1_20670695_Q_VA	0X0171
#define _SCC_FL_FB_8_ED1_20670696_Q_VA	0X0172
#define _SCC_FL_FB_8_ED1_20670697_Q_VA	0X0173
#define _SCC_FL_FB_8_ED1_20670692_Q_VA	0X0174
#define _SCC_FL_FB_8_ED1_20670693_Q_VA	0X0175
#define _SCC_FL_FB_8_ED1_20670694_Q_VA	0X0176
#define _SCC_FL_FB_8_ED1_V0001	0X0177
#define _SCC_FL_FB_8_ED1_V0002	0X0178
#define _SCC_FL_FB_8_ED1_V0003	0X0179
#define _SCC_FL_FB_8_ED1_V0004	0X017A
#define _SCC_FL_FB_8_ED1_V0005	0X017B
#define _SCC_FL_FB_8_ED1_V0006	0X017C
#define _SCC_FL_FB_8_ED1_20670690_Q_VA	0X017D
#define _SCC_FL_FB_8_ED1_20670691_Q_VA	0X017E

/* Analogs */


/* Timers */

#define _SCC_FL_FB_8_ED1_20670695_ET_VA	0X0012
#define _SCC_FL_FB_8_ED1_20670696_ET_VA	0X0013

/* Function blocks */

#define _SCC_FL_FB_8_ED1_20670699	0X0032
#define _SCC_FL_FB_8_ED1_20670696	0X0033
#define _SCC_FL_FB_8_ED1_20670697	0X0034
#define _SCC_FL_FB_8_ED1_20670698	0X0035
#define _SCC_FL_FB_8_ED1_20670693	0X0036
#define _SCC_FL_FB_8_ED1_20670694	0X0037
#define _SCC_FL_FB_8_ED1_20670695	0X0038

#define _SCC_FL_FB_8_ED1_20670692	0X0016
#define _SCC_FL_FB_8_ED1_20670690	0X0017
#define _SCC_FL_FB_8_ED1_20670691	0X0018

#define _SCC_FL_FB_8_ED1_2067069B	0X0008

#define _SCC_FL_FB_8_ED1_2067069A	0X0008
