/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_6.H                                             */
/*  Date      : 15.10.2015 19:55:01                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ftest                                      */
/*  ISaGRAF program name : FL_FB_6                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_6_ED1_20670598_BI5__VA	0X013D
#define _SCC_FL_FB_6_ED1_20670598_BI3__VA	0X013E
#define _SCC_FL_FB_6_ED1_20670598_BI2__VA	0X013F
#define _SCC_FL_FB_6_ED1_20670598_BI1__VA	0X0140
#define _SCC_FL_FB_6_ED1_20670598_Q__VA	0X0141
#define _SCC_FL_FB_6_ED1_20670599_Q__VA	0X0142
#define _SCC_FL_FB_6_ED1_20670596_Q_VA	0X0143
#define _SCC_FL_FB_6_ED1_20670597_Q_VA	0X0144
#define _SCC_FL_FB_6_ED1_20670593_Q_VA	0X0145
#define _SCC_FL_FB_6_ED1_20670594_Q_VA	0X0146
#define _SCC_FL_FB_6_ED1_20670595_Q_VA	0X0147
#define _SCC_FL_FB_6_ED1_20670590_Q_VA	0X0148
#define _SCC_FL_FB_6_ED1_20670591_Q_VA	0X0149
#define _SCC_FL_FB_6_ED1_20670592_Q_VA	0X014A
#define _SCC_FL_FB_6_ED1_V0001	0X014B
#define _SCC_FL_FB_6_ED1_V0002	0X014C
#define _SCC_FL_FB_6_ED1_V0003	0X014D
#define _SCC_FL_FB_6_ED1_V0004	0X014E
#define _SCC_FL_FB_6_ED1_V0005	0X014F
#define _SCC_FL_FB_6_ED1_V0006	0X0150
#define _SCC_FL_FB_6_ED1_2067058E_Q_VA	0X0151
#define _SCC_FL_FB_6_ED1_2067058F_Q_VA	0X0152

/* Analogs */


/* Timers */

#define _SCC_FL_FB_6_ED1_20670593_ET_VA	0X000E
#define _SCC_FL_FB_6_ED1_20670594_ET_VA	0X000F

/* Function blocks */

#define _SCC_FL_FB_6_ED1_20670597	0X0024
#define _SCC_FL_FB_6_ED1_20670594	0X0025
#define _SCC_FL_FB_6_ED1_20670595	0X0026
#define _SCC_FL_FB_6_ED1_20670596	0X0027
#define _SCC_FL_FB_6_ED1_20670591	0X0028
#define _SCC_FL_FB_6_ED1_20670592	0X0029
#define _SCC_FL_FB_6_ED1_20670593	0X002A

#define _SCC_FL_FB_6_ED1_20670590	0X0010
#define _SCC_FL_FB_6_ED1_2067058E	0X0011
#define _SCC_FL_FB_6_ED1_2067058F	0X0012

#define _SCC_FL_FB_6_ED1_20670599	0X0006

#define _SCC_FL_FB_6_ED1_20670598	0X0006
