/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_7.H                                             */
/*  Date      : 15.10.2015 19:55:01                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ftest                                      */
/*  ISaGRAF program name : FL_FB_7                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_7_ED1_20670699_BI5__VA	0X0153
#define _SCC_FL_FB_7_ED1_20670699_BI3__VA	0X0154
#define _SCC_FL_FB_7_ED1_20670699_BI2__VA	0X0155
#define _SCC_FL_FB_7_ED1_20670699_BI1__VA	0X0156
#define _SCC_FL_FB_7_ED1_20670699_Q__VA	0X0157
#define _SCC_FL_FB_7_ED1_2067069A_Q__VA	0X0158
#define _SCC_FL_FB_7_ED1_20670697_Q_VA	0X0159
#define _SCC_FL_FB_7_ED1_20670698_Q_VA	0X015A
#define _SCC_FL_FB_7_ED1_20670694_Q_VA	0X015B
#define _SCC_FL_FB_7_ED1_20670695_Q_VA	0X015C
#define _SCC_FL_FB_7_ED1_20670696_Q_VA	0X015D
#define _SCC_FL_FB_7_ED1_20670691_Q_VA	0X015E
#define _SCC_FL_FB_7_ED1_20670692_Q_VA	0X015F
#define _SCC_FL_FB_7_ED1_20670693_Q_VA	0X0160
#define _SCC_FL_FB_7_ED1_V0001	0X0161
#define _SCC_FL_FB_7_ED1_V0002	0X0162
#define _SCC_FL_FB_7_ED1_V0003	0X0163
#define _SCC_FL_FB_7_ED1_V0004	0X0164
#define _SCC_FL_FB_7_ED1_V0005	0X0165
#define _SCC_FL_FB_7_ED1_V0006	0X0166
#define _SCC_FL_FB_7_ED1_2067068F_Q_VA	0X0167
#define _SCC_FL_FB_7_ED1_20670690_Q_VA	0X0168

/* Analogs */


/* Timers */

#define _SCC_FL_FB_7_ED1_20670694_ET_VA	0X0010
#define _SCC_FL_FB_7_ED1_20670695_ET_VA	0X0011

/* Function blocks */

#define _SCC_FL_FB_7_ED1_20670698	0X002B
#define _SCC_FL_FB_7_ED1_20670695	0X002C
#define _SCC_FL_FB_7_ED1_20670696	0X002D
#define _SCC_FL_FB_7_ED1_20670697	0X002E
#define _SCC_FL_FB_7_ED1_20670692	0X002F
#define _SCC_FL_FB_7_ED1_20670693	0X0030
#define _SCC_FL_FB_7_ED1_20670694	0X0031

#define _SCC_FL_FB_7_ED1_20670691	0X0013
#define _SCC_FL_FB_7_ED1_2067068F	0X0014
#define _SCC_FL_FB_7_ED1_20670690	0X0015

#define _SCC_FL_FB_7_ED1_2067069A	0X0007

#define _SCC_FL_FB_7_ED1_20670699	0X0007
