/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_3.H                                             */
/*  Date      : 15.10.2015 19:55:01                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ftest                                      */
/*  ISaGRAF program name : FL_FB_3                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_3_ED1_20670495_BI5__VA	0X00FB
#define _SCC_FL_FB_3_ED1_20670495_BI3__VA	0X00FC
#define _SCC_FL_FB_3_ED1_20670495_BI2__VA	0X00FD
#define _SCC_FL_FB_3_ED1_20670495_BI1__VA	0X00FE
#define _SCC_FL_FB_3_ED1_20670495_Q__VA	0X00FF
#define _SCC_FL_FB_3_ED1_20670496_Q__VA	0X0100
#define _SCC_FL_FB_3_ED1_20670493_Q_VA	0X0101
#define _SCC_FL_FB_3_ED1_20670494_Q_VA	0X0102
#define _SCC_FL_FB_3_ED1_20670490_Q_VA	0X0103
#define _SCC_FL_FB_3_ED1_20670491_Q_VA	0X0104
#define _SCC_FL_FB_3_ED1_20670492_Q_VA	0X0105
#define _SCC_FL_FB_3_ED1_2067048D_Q_VA	0X0106
#define _SCC_FL_FB_3_ED1_2067048E_Q_VA	0X0107
#define _SCC_FL_FB_3_ED1_2067048F_Q_VA	0X0108
#define _SCC_FL_FB_3_ED1_V0001	0X0109
#define _SCC_FL_FB_3_ED1_V0002	0X010A
#define _SCC_FL_FB_3_ED1_V0003	0X010B
#define _SCC_FL_FB_3_ED1_V0004	0X010C
#define _SCC_FL_FB_3_ED1_V0005	0X010D
#define _SCC_FL_FB_3_ED1_V0006	0X010E
#define _SCC_FL_FB_3_ED1_2067048B_Q_VA	0X010F
#define _SCC_FL_FB_3_ED1_2067048C_Q_VA	0X0110

/* Analogs */


/* Timers */

#define _SCC_FL_FB_3_ED1_20670490_ET_VA	0X0008
#define _SCC_FL_FB_3_ED1_20670491_ET_VA	0X0009

/* Function blocks */

#define _SCC_FL_FB_3_ED1_20670494	0X000F
#define _SCC_FL_FB_3_ED1_20670491	0X0010
#define _SCC_FL_FB_3_ED1_20670492	0X0011
#define _SCC_FL_FB_3_ED1_20670493	0X0012
#define _SCC_FL_FB_3_ED1_2067048E	0X0013
#define _SCC_FL_FB_3_ED1_2067048F	0X0014
#define _SCC_FL_FB_3_ED1_20670490	0X0015

#define _SCC_FL_FB_3_ED1_2067048D	0X0007
#define _SCC_FL_FB_3_ED1_2067048B	0X0008
#define _SCC_FL_FB_3_ED1_2067048C	0X0009

#define _SCC_FL_FB_3_ED1_20670496	0X0003

#define _SCC_FL_FB_3_ED1_20670495	0X0003
