/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_4.H                                             */
/*  Date      : 15.10.2015 19:55:01                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ftest                                      */
/*  ISaGRAF program name : FL_FB_4                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_4_ED1_20670496_BI5__VA	0X0111
#define _SCC_FL_FB_4_ED1_20670496_BI3__VA	0X0112
#define _SCC_FL_FB_4_ED1_20670496_BI2__VA	0X0113
#define _SCC_FL_FB_4_ED1_20670496_BI1__VA	0X0114
#define _SCC_FL_FB_4_ED1_20670496_Q__VA	0X0115
#define _SCC_FL_FB_4_ED1_20670497_Q__VA	0X0116
#define _SCC_FL_FB_4_ED1_20670494_Q_VA	0X0117
#define _SCC_FL_FB_4_ED1_20670495_Q_VA	0X0118
#define _SCC_FL_FB_4_ED1_20670491_Q_VA	0X0119
#define _SCC_FL_FB_4_ED1_20670492_Q_VA	0X011A
#define _SCC_FL_FB_4_ED1_20670493_Q_VA	0X011B
#define _SCC_FL_FB_4_ED1_2067048E_Q_VA	0X011C
#define _SCC_FL_FB_4_ED1_2067048F_Q_VA	0X011D
#define _SCC_FL_FB_4_ED1_20670490_Q_VA	0X011E
#define _SCC_FL_FB_4_ED1_V0001	0X011F
#define _SCC_FL_FB_4_ED1_V0002	0X0120
#define _SCC_FL_FB_4_ED1_V0003	0X0121
#define _SCC_FL_FB_4_ED1_V0004	0X0122
#define _SCC_FL_FB_4_ED1_V0005	0X0123
#define _SCC_FL_FB_4_ED1_V0006	0X0124
#define _SCC_FL_FB_4_ED1_2067048C_Q_VA	0X0125
#define _SCC_FL_FB_4_ED1_2067048D_Q_VA	0X0126

/* Analogs */


/* Timers */

#define _SCC_FL_FB_4_ED1_20670491_ET_VA	0X000A
#define _SCC_FL_FB_4_ED1_20670492_ET_VA	0X000B

/* Function blocks */

#define _SCC_FL_FB_4_ED1_20670495	0X0016
#define _SCC_FL_FB_4_ED1_20670492	0X0017
#define _SCC_FL_FB_4_ED1_20670493	0X0018
#define _SCC_FL_FB_4_ED1_20670494	0X0019
#define _SCC_FL_FB_4_ED1_2067048F	0X001A
#define _SCC_FL_FB_4_ED1_20670490	0X001B
#define _SCC_FL_FB_4_ED1_20670491	0X001C

#define _SCC_FL_FB_4_ED1_2067048E	0X000A
#define _SCC_FL_FB_4_ED1_2067048C	0X000B
#define _SCC_FL_FB_4_ED1_2067048D	0X000C

#define _SCC_FL_FB_4_ED1_20670497	0X0004

#define _SCC_FL_FB_4_ED1_20670496	0X0004
