/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_2.H                                             */
/*  Date      : 15.10.2015 19:55:01                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ftest                                      */
/*  ISaGRAF program name : FL_FB_2                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_2_ED1_20670494_BI5__VA	0X00E5
#define _SCC_FL_FB_2_ED1_20670494_BI3__VA	0X00E6
#define _SCC_FL_FB_2_ED1_20670494_BI2__VA	0X00E7
#define _SCC_FL_FB_2_ED1_20670494_BI1__VA	0X00E8
#define _SCC_FL_FB_2_ED1_20670494_Q__VA	0X00E9
#define _SCC_FL_FB_2_ED1_20670495_Q__VA	0X00EA
#define _SCC_FL_FB_2_ED1_20670492_Q_VA	0X00EB
#define _SCC_FL_FB_2_ED1_20670493_Q_VA	0X00EC
#define _SCC_FL_FB_2_ED1_2067048F_Q_VA	0X00ED
#define _SCC_FL_FB_2_ED1_20670490_Q_VA	0X00EE
#define _SCC_FL_FB_2_ED1_20670491_Q_VA	0X00EF
#define _SCC_FL_FB_2_ED1_2067048C_Q_VA	0X00F0
#define _SCC_FL_FB_2_ED1_2067048D_Q_VA	0X00F1
#define _SCC_FL_FB_2_ED1_2067048E_Q_VA	0X00F2
#define _SCC_FL_FB_2_ED1_V0001	0X00F3
#define _SCC_FL_FB_2_ED1_V0002	0X00F4
#define _SCC_FL_FB_2_ED1_V0003	0X00F5
#define _SCC_FL_FB_2_ED1_V0004	0X00F6
#define _SCC_FL_FB_2_ED1_V0005	0X00F7
#define _SCC_FL_FB_2_ED1_V0006	0X00F8
#define _SCC_FL_FB_2_ED1_2067048A_Q_VA	0X00F9
#define _SCC_FL_FB_2_ED1_2067048B_Q_VA	0X00FA

/* Analogs */


/* Timers */

#define _SCC_FL_FB_2_ED1_2067048F_ET_VA	0X0006
#define _SCC_FL_FB_2_ED1_20670490_ET_VA	0X0007

/* Function blocks */

#define _SCC_FL_FB_2_ED1_20670493	0X0008
#define _SCC_FL_FB_2_ED1_20670490	0X0009
#define _SCC_FL_FB_2_ED1_20670491	0X000A
#define _SCC_FL_FB_2_ED1_20670492	0X000B
#define _SCC_FL_FB_2_ED1_2067048D	0X000C
#define _SCC_FL_FB_2_ED1_2067048E	0X000D
#define _SCC_FL_FB_2_ED1_2067048F	0X000E

#define _SCC_FL_FB_2_ED1_2067048C	0X0004
#define _SCC_FL_FB_2_ED1_2067048A	0X0005
#define _SCC_FL_FB_2_ED1_2067048B	0X0006

#define _SCC_FL_FB_2_ED1_20670495	0X0002

#define _SCC_FL_FB_2_ED1_20670494	0X0002
