/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_1.H                                             */
/*  Date      : 15.10.2015 19:55:01                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ftest                                      */
/*  ISaGRAF program name : FL_FB_1                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_1_ED1_20670393_BI5__VA	0X00CD
#define _SCC_FL_FB_1_ED1_20670393_BI3__VA	0X00CE
#define _SCC_FL_FB_1_ED1_20670393_BI2__VA	0X00CF
#define _SCC_FL_FB_1_ED1_20670393_BI1__VA	0X00D0
#define _SCC_FL_FB_1_ED1_20670393_Q__VA	0X00D1
#define _SCC_FL_FB_1_ED1_20670394_Q__VA	0X00D2
#define _SCC_FL_FB_1_ED1_20670391_Q_VA	0X00D3
#define _SCC_FL_FB_1_ED1_20670392_Q_VA	0X00D4
#define _SCC_FL_FB_1_ED1_2067038E_Q_VA	0X00D5
#define _SCC_FL_FB_1_ED1_2067038F_Q_VA	0X00D6
#define _SCC_FL_FB_1_ED1_20670390_Q_VA	0X00D7
#define _SCC_FL_FB_1_ED1_2067038B_Q_VA	0X00D8
#define _SCC_FL_FB_1_ED1_2067038C_Q_VA	0X00D9
#define _SCC_FL_FB_1_ED1_2067038D_Q_VA	0X00DA
#define _SCC_FL_FB_1_ED1_V0001	0X00DB
#define _SCC_FL_FB_1_ED1_V0002	0X00DC
#define _SCC_FL_FB_1_ED1_V0003	0X00DD
#define _SCC_FL_FB_1_ED1_V0004	0X00DE
#define _SCC_FL_FB_1_ED1_V0005	0X00DF
#define _SCC_FL_FB_1_ED1_V0006	0X00E0
#define _SCC_FL_FB_1_ED1_20670389_Q_VA	0X00E1
#define _SCC_FL_FB_1_ED1_2067038A_Q_VA	0X00E2

/* Analogs */


/* Timers */

#define _SCC_FL_FB_1_ED1_2067038E_ET_VA	0X0003
#define _SCC_FL_FB_1_ED1_2067038F_ET_VA	0X0004

/* Function blocks */

#define _SCC_FL_FB_1_ED1_20670392	0X0001
#define _SCC_FL_FB_1_ED1_2067038F	0X0002
#define _SCC_FL_FB_1_ED1_20670390	0X0003
#define _SCC_FL_FB_1_ED1_20670391	0X0004
#define _SCC_FL_FB_1_ED1_2067038C	0X0005
#define _SCC_FL_FB_1_ED1_2067038D	0X0006
#define _SCC_FL_FB_1_ED1_2067038E	0X0007

#define _SCC_FL_FB_1_ED1_2067038B	0X0001
#define _SCC_FL_FB_1_ED1_20670389	0X0002
#define _SCC_FL_FB_1_ED1_2067038A	0X0003

#define _SCC_FL_FB_1_ED1_20670394	0X0001

#define _SCC_FL_FB_1_ED1_20670393	0X0001
