/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_5.H                                             */
/*  Date      : 15.10.2015 19:55:01                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ftest                                      */
/*  ISaGRAF program name : FL_FB_5                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_5_ED1_20670597_BI5__VA	0X0127
#define _SCC_FL_FB_5_ED1_20670597_BI3__VA	0X0128
#define _SCC_FL_FB_5_ED1_20670597_BI2__VA	0X0129
#define _SCC_FL_FB_5_ED1_20670597_BI1__VA	0X012A
#define _SCC_FL_FB_5_ED1_20670597_Q__VA	0X012B
#define _SCC_FL_FB_5_ED1_20670598_Q__VA	0X012C
#define _SCC_FL_FB_5_ED1_20670595_Q_VA	0X012D
#define _SCC_FL_FB_5_ED1_20670596_Q_VA	0X012E
#define _SCC_FL_FB_5_ED1_20670592_Q_VA	0X012F
#define _SCC_FL_FB_5_ED1_20670593_Q_VA	0X0130
#define _SCC_FL_FB_5_ED1_20670594_Q_VA	0X0131
#define _SCC_FL_FB_5_ED1_2067058F_Q_VA	0X0132
#define _SCC_FL_FB_5_ED1_20670590_Q_VA	0X0133
#define _SCC_FL_FB_5_ED1_20670591_Q_VA	0X0134
#define _SCC_FL_FB_5_ED1_V0001	0X0135
#define _SCC_FL_FB_5_ED1_V0002	0X0136
#define _SCC_FL_FB_5_ED1_V0003	0X0137
#define _SCC_FL_FB_5_ED1_V0004	0X0138
#define _SCC_FL_FB_5_ED1_V0005	0X0139
#define _SCC_FL_FB_5_ED1_V0006	0X013A
#define _SCC_FL_FB_5_ED1_2067058D_Q_VA	0X013B
#define _SCC_FL_FB_5_ED1_2067058E_Q_VA	0X013C

/* Analogs */


/* Timers */

#define _SCC_FL_FB_5_ED1_20670592_ET_VA	0X000C
#define _SCC_FL_FB_5_ED1_20670593_ET_VA	0X000D

/* Function blocks */

#define _SCC_FL_FB_5_ED1_20670596	0X001D
#define _SCC_FL_FB_5_ED1_20670593	0X001E
#define _SCC_FL_FB_5_ED1_20670594	0X001F
#define _SCC_FL_FB_5_ED1_20670595	0X0020
#define _SCC_FL_FB_5_ED1_20670590	0X0021
#define _SCC_FL_FB_5_ED1_20670591	0X0022
#define _SCC_FL_FB_5_ED1_20670592	0X0023

#define _SCC_FL_FB_5_ED1_2067058F	0X000D
#define _SCC_FL_FB_5_ED1_2067058D	0X000E
#define _SCC_FL_FB_5_ED1_2067058E	0X000F

#define _SCC_FL_FB_5_ED1_20670598	0X0005

#define _SCC_FL_FB_5_ED1_20670597	0X0005
