/**********************************************************************/
/*                                                                    */
/*  File name : EEP_B_W.H                                             */
/*  Date      : 03.10.2018 14:25:06                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : feeder                                     */
/*  ISaGRAF program name : EEP_B_W                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */






