/**********************************************************************/
/*                                                                    */
/*  File name : FD_22.H                                               */
/*  Date      : 03.10.2018 14:25:06                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : feeder                                     */
/*  ISaGRAF program name : FD_22                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_22_MQ_03	0X0006
#define _SCC_FD_22_MQ_04	0X005C
#define _SCC_FD_22_MQ_02	0X005D
#define _SCC_FD_22_MQ_01	0X005E
#define _SCC_FD_22_ED1_B5322E8F_Q_VA	0X0092
#define _SCC_FD_22_ED1_B5322E8E_Q_VA	0X0093
#define _SCC_FD_22_ED1_B5322E8D_B12__VA	0X0094
#define _SCC_FD_22_ED1_B5322E93_Q_VA	0X0095
#define _SCC_FD_22_ED1_B5322E92_Q_VA	0X0096
#define _SCC_FD_22_ED1_B5322E91_B1__VA	0X0097
#define _SCC_FD_22_ED1_B5322E90_Q_VA	0X0098
#define _SCC_FD_22_ED1_B5322E91_B16__VA	0X0099

/* Analogs */

#define _SCC_FD_22_W_09	0X0085
#define _SCC_FD_22_W_07	0X0086
#define _SCC_FD_22_W_06	0X0087
#define _SCC_FD_22_W_05	0X0088
#define _SCC_FD_22_W_04	0X0089
#define _SCC_FD_22_W_03	0X008A
#define _SCC_FD_22_W_02	0X008B
#define _SCC_FD_22_W_01	0X008C
#define _SCC_FD_22_TMPR1	0X00B7
#define _SCC_FD_22_TMPR5	0X00BC
#define _SCC_FD_22_TMPR8	0X00C0
#define _SCC_FD_22_ED1_B5322E8E_N3__VA	0X0108
#define _SCC_FD_22_ED1_B5322E8E_N2__VA	0X0109
#define _SCC_FD_22_ED1_B5322E8E_N1__VA	0X010A
#define _SCC_FD_22_ED1_B5322E93_N3__VA	0X010B
#define _SCC_FD_22_ED1_B5322E93_N2__VA	0X010C
#define _SCC_FD_22_ED1_B5322E93_N1__VA	0X010D
#define _SCC_FD_22_ED1_B5322E92_N1__VA	0X010E
#define _SCC_FD_22_ED1_B5322E90_N1__VA	0X010F

/* Timers */


/* Functions */


/* Function blocks */



#define _SCC_FD_22_ED1_B5322E90	0X0006
#define _SCC_FD_22_ED1_B5322E8E	0X0007
#define _SCC_FD_22_ED1_B5322E93	0X0008
#define _SCC_FD_22_ED1_B5322E92	0X0009

#define _SCC_FD_22_ED1_B5322E8F	0X0002


#define _SCC_FD_22_ED1_B5322E8D	0X0002
#define _SCC_FD_22_ED1_B5322E91	0X0003
