/**********************************************************************/
/*                                                                    */
/*  File name : FD_23.H                                               */
/*  Date      : 03.10.2018 14:25:06                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : feeder                                     */
/*  ISaGRAF program name : FD_23                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_23_MQ_03	0X0005
#define _SCC_FD_23_MQ_02	0X005F
#define _SCC_FD_23_MQ_01	0X0060
#define _SCC_FD_23_ED1_B5322E8E_Q_VA	0X009A
#define _SCC_FD_23_ED1_B5322E92_Q_VA	0X009B
#define _SCC_FD_23_ED1_B5322E91_Q_VA	0X009C
#define _SCC_FD_23_ED1_B5322E90_B1__VA	0X009D
#define _SCC_FD_23_ED1_B5322E8F_Q_VA	0X009E
#define _SCC_FD_23_ED1_B5322E90_B16__VA	0X009F

/* Analogs */

#define _SCC_FD_23_W_09	0X008D
#define _SCC_FD_23_W_04	0X008E
#define _SCC_FD_23_W_03	0X008F
#define _SCC_FD_23_W_02	0X0090
#define _SCC_FD_23_W_01	0X0091
#define _SCC_FD_23_TMPR1	0X00B6
#define _SCC_FD_23_TMPR5	0X00BB
#define _SCC_FD_23_TMPR8	0X00BF
#define _SCC_FD_23_ED1_B5322E92_N3__VA	0X0110
#define _SCC_FD_23_ED1_B5322E92_N2__VA	0X0111
#define _SCC_FD_23_ED1_B5322E92_N1__VA	0X0112
#define _SCC_FD_23_ED1_B5322E91_N1__VA	0X0113
#define _SCC_FD_23_ED1_B5322E8F_N1__VA	0X0114

/* Timers */


/* Functions */


/* Function blocks */



#define _SCC_FD_23_ED1_B5322E8F	0X000A
#define _SCC_FD_23_ED1_B5322E92	0X000B
#define _SCC_FD_23_ED1_B5322E91	0X000C

#define _SCC_FD_23_ED1_B5322E8E	0X0003


#define _SCC_FD_23_ED1_B5322E90	0X0004
