/**********************************************************************/
/*                                                                    */
/*  File name : FD_21.H                                               */
/*  Date      : 03.10.2018 14:25:06                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : feeder                                     */
/*  ISaGRAF program name : FD_21                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_21_MQ_03	0X0007
#define _SCC_FD_21_MQ_05	0X0059
#define _SCC_FD_21_MQ_02	0X005A
#define _SCC_FD_21_MQ_01	0X005B
#define _SCC_FD_21_ED1_B5322E90_Q_VA	0X008A
#define _SCC_FD_21_ED1_B5322E8F_Q_VA	0X008B
#define _SCC_FD_21_ED1_B5322E8D_Q_VA	0X008C
#define _SCC_FD_21_ED1_B5322E94_Q_VA	0X008D
#define _SCC_FD_21_ED1_B5322E93_Q_VA	0X008E
#define _SCC_FD_21_ED1_B5322E92_B1__VA	0X008F
#define _SCC_FD_21_ED1_B5322E91_Q_VA	0X0090
#define _SCC_FD_21_ED1_B5322E92_B16__VA	0X0091

/* Analogs */

#define _SCC_FD_21_W_09	0X007E
#define _SCC_FD_21_W_05	0X007F
#define _SCC_FD_21_W_04	0X0080
#define _SCC_FD_21_W_03	0X0081
#define _SCC_FD_21_W_02	0X0082
#define _SCC_FD_21_W_01	0X0083
#define _SCC_FD_21_TMPR1	0X00B8
#define _SCC_FD_21_TMPR10	0X00BA
#define _SCC_FD_21_TMPR5	0X00BD
#define _SCC_FD_21_TMPR13	0X00BE
#define _SCC_FD_21_TMPR9	0X00C1
#define _SCC_FD_21_ED1_B5322E8F_N1__VA	0X00FB
#define _SCC_FD_21_ED1_B5322E8E_XOUT__VA	0X00FC
#define _SCC_FD_21_ED1_V0001	0X00FD
#define _SCC_FD_21_ED1_B5322E94_N3__VA	0X0103
#define _SCC_FD_21_ED1_B5322E94_N2__VA	0X0104
#define _SCC_FD_21_ED1_B5322E94_N1__VA	0X0105
#define _SCC_FD_21_ED1_B5322E93_N1__VA	0X0106
#define _SCC_FD_21_ED1_B5322E91_N1__VA	0X0107

/* Timers */


/* Functions */


/* Function blocks */

#define _SCC_FD_21_ED1_B5322E8D	0X0002


#define _SCC_FD_21_ED1_B5322E91	0X0002
#define _SCC_FD_21_ED1_B5322E8F	0X0003
#define _SCC_FD_21_ED1_B5322E94	0X0004
#define _SCC_FD_21_ED1_B5322E93	0X0005

#define _SCC_FD_21_ED1_B5322E90	0X0001

#define _SCC_FD_21_ED1_B5322E8E	0X0001

#define _SCC_FD_21_ED1_B5322E92	0X0001
