/**********************************************************************/
/*                                                                    */
/*  File name : KALMAN.H                                              */
/*  Date      : 03.10.2018 14:25:06                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : feeder                                     */
/*  ISaGRAF program name : KALMAN                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_KALMAN_RUN_	0X0062

/* Analogs */

#define _SCC_KALMAN_STATE_	0X007D
#define _SCC_KALMAN_STATE	0X0084
#define _SCC_KALMAN_XIN_	0X0095
#define _SCC_KALMAN_F_	0X0096

/* Timers */


/* Functions */


/* Function blocks */






