/**********************************************************************/
/*                                                                    */
/*  File name : MUX2.H                                                */
/*  Date      : 03.10.2018 14:25:06                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : feeder                                     */
/*  ISaGRAF program name : MUX2                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MUX2_SL	0X0061

/* Analogs */

#define _SCC_MUX2_MUX2	0X0092
#define _SCC_MUX2_IN2	0X0093
#define _SCC_MUX2_IN1	0X0094

/* Timers */


/* Functions */


/* Function blocks */






