/**********************************************************************/
/*                                                                    */
/*  File name : PARM_STO.H                                            */
/*  Date      : 03.10.2018 14:25:06                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : feeder                                     */
/*  ISaGRAF program name : PARM_STO                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARM_STO_RES	0X0057
#define _SCC_PARM_STO_READ	0X0058

/* Analogs */

#define _SCC_PARM_STO_SAV_ST	0X0078

/* Timers */

#define _SCC_PARM_STO_SAV_TM	0X0001

/* Functions */


/* Function blocks */






