/**********************************************************************/
/*                                                                    */
/*  File name : START.H                                               */
/*  Date      : 03.10.2018 14:25:06                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : feeder                                     */
/*  ISaGRAF program name : START                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_START_ED1_B5333930_Q_VA	0X0088
#define _SCC_START_ED1_B533392E_Q_VA	0X0089

/* Analogs */

#define _SCC_START_AI_4_4	0X0079
#define _SCC_START_AI_4_3	0X007A
#define _SCC_START_AI_4_2	0X007B
#define _SCC_START_AI_4_1	0X007C
#define _SCC_START_TMPR1	0X00B9
#define _SCC_START_ED1_B533392F_XOUT_VA	0X00F6
#define _SCC_START_ED1_B533392E_N4__VA	0X00F7
#define _SCC_START_ED1_B533392E_N3__VA	0X00F8
#define _SCC_START_ED1_B533392E_N2__VA	0X00F9
#define _SCC_START_ED1_B533392E_N1__VA	0X00FA

/* Timers */


/* Functions */


/* Function blocks */

#define _SCC_START_ED1_B5333930	0X0001

#define _SCC_START_ED1_B533392F	0X0001

#define _SCC_START_ED1_B533392E	0X0001



