/**********************************************************************/
/*                                                                    */
/*  File name : TX_X.H                                                */
/*  Date      : 03.10.2018 14:25:06                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : feeder                                     */
/*  ISaGRAF program name : TX_X                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */

#define _SCC_TX_X_TMPR1	0X00B5

/* Timers */


/* Functions */


/* Function blocks */






