/**********************************************************************/
/*                                                                    */
/*  File name : appli.H                                               */
/*  Date      : 17.08.2020 11:31:33                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : test8028                                   */
/*                                                                    */
/**********************************************************************/

/* Global variables of the various programs */

/* Programs */

#define _SCC_TEST	0X0001

/* Booleans */

#define _SCC_DUMMYCOIL	0X0001

/* Analogs */

#define _SCC_Q1	0X0001
#define _SCC_Q2	0X0002
#define _SCC_Q3	0X0003
#define _SCC_Q4	0X0004
#define _SCC_Q5	0X0005
#define _SCC_Q6	0X0006
#define _SCC_Q7	0X0007
#define _SCC_Q8	0X0008
#define _SCC_ALLOUT	0X0009
#define _SCC_FBL_RET	0X000A
