/**********************************************************************/
/*                                                                    */
/*  File name : CONTROL.H                                             */
/*  Date      : 15.09.2016 22:54:32                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : kf1000                                     */
/*  ISaGRAF program name : CONTROL                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_CONTROL_FE_X_J	0X0070
#define _SCC_CONTROL_L_IJ	0X0071
#define _SCC_CONTROL_RE_LOCK	0X0072

/* Analogs */

#define _SCC_CONTROL_TMPR1	0X0064
#define _SCC_CONTROL_TMPR3	0X0065
#define _SCC_CONTROL_TMPR4	0X0066

/* Timers */


/* Functions */


/* Function blocks */













