/**********************************************************************/
/*                                                                    */
/*  File name : EEP_N_R.H                                             */
/*  Date      : 15.09.2016 22:54:32                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : kf1000                                     */
/*  ISaGRAF program name : EEP_N_R                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */













