/**********************************************************************/
/*                                                                    */
/*  File name : A4_20_TO.H                                            */
/*  Date      : 07.10.2014 13:21:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur                                      */
/*  ISaGRAF program name : A4_20_TO                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












