/**********************************************************************/
/*                                                                    */
/*  File name : BLEDING.H                                             */
/*  Date      : 07.10.2014 13:21:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur                                      */
/*  ISaGRAF program name : BLEDING                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_BLEDING_RE_TS0	0X0071
#define _SCC_BLEDING_P_06	0X0072
#define _SCC_BLEDING_P_05	0X0073
#define _SCC_BLEDING_P_04	0X0074
#define _SCC_BLEDING_P_03	0X0075
#define _SCC_BLEDING_P_02	0X0076
#define _SCC_BLEDING_P_01	0X0077

/* Analogs */

#define _SCC_BLEDING_OC_13	0X0174
#define _SCC_BLEDING_TMPR1	0X01A7

/* Timers */

#define _SCC_BLEDING_TP_06	0X0001
#define _SCC_BLEDING_TP_05	0X0002
#define _SCC_BLEDING_TP_04	0X0003
#define _SCC_BLEDING_TP_03	0X0004
#define _SCC_BLEDING_TP_02	0X0005
#define _SCC_BLEDING_TP_01	0X0006

/* Messages */


/* Functions */


/* Function blocks */












