/**********************************************************************/
/*                                                                    */
/*  File name : EEP_N_R.H                                             */
/*  Date      : 14.08.2013 15:49:43                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur                                      */
/*  ISaGRAF program name : EEP_N_R                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Messages */


/* Functions */


/* Function blocks */













