/**********************************************************************/
/*                                                                    */
/*  File name : EEP_N_W.H                                             */
/*  Date      : 09.10.2013 13:56:57                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur                                      */
/*  ISaGRAF program name : EEP_N_W                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Messages */


/* Functions */


/* Function blocks */













