/**********************************************************************/
/*                                                                    */
/*  File name : MUX2.H                                                */
/*  Date      : 07.10.2014 13:21:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur                                      */
/*  ISaGRAF program name : MUX2                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MUX2_SL	0X0078

/* Analogs */

#define _SCC_MUX2_MUX2	0X0175
#define _SCC_MUX2_IN2	0X0176
#define _SCC_MUX2_IN1	0X0177

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












