/**********************************************************************/
/*                                                                    */
/*  File name : P_P0.H                                                */
/*  Date      : 07.10.2014 13:21:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur                                      */
/*  ISaGRAF program name : P_P0                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_P_P0_AUTO_O	0X006F
#define _SCC_P_P0_MODE_	0X0079
#define _SCC_P_P0_AUTO_	0X007A

/* Analogs */

#define _SCC_P_P0_KP_O	0X016B
#define _SCC_P_P0_X0_O	0X016C
#define _SCC_P_P0_SP_O	0X016D
#define _SCC_P_P0_PV_O	0X016E
#define _SCC_P_P0_KP_	0X0178
#define _SCC_P_P0_X0_	0X0179
#define _SCC_P_P0_SP_	0X017A
#define _SCC_P_P0_PV_	0X017B
#define _SCC_P_P0_P0_	0X017C

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












