/**********************************************************************/
/*                                                                    */
/*  File name : PIDMY.H                                               */
/*  Date      : 07.10.2014 13:21:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur                                      */
/*  ISaGRAF program name : PIDMY                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PIDMY_AUTO_	0X007B
#define _SCC_PIDMY_MODE_	0X007C

/* Analogs */

#define _SCC_PIDMY_XT_	0X016F
#define _SCC_PIDMY_SUM0_	0X0170
#define _SCC_PIDMY_XOUT_	0X0171
#define _SCC_PIDMY_KE_	0X0172
#define _SCC_PIDMY_SUM_	0X0173
#define _SCC_PIDMY_P0_	0X017D
#define _SCC_PIDMY_TD_	0X017E
#define _SCC_PIDMY_TI_	0X017F
#define _SCC_PIDMY_KP_	0X0180
#define _SCC_PIDMY_X0_	0X0181
#define _SCC_PIDMY_SP_	0X0182
#define _SCC_PIDMY_PV_	0X0183
#define _SCC_PIDMY_XMAX_	0X0184
#define _SCC_PIDMY_XMIN_	0X0185
#define _SCC_PIDMY_TMPR3	0X01A2

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












