/**********************************************************************/
/*                                                                    */
/*  File name : RETAIN_A.H                                            */
/*  Date      : 06.06.2011 14:01:11                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur                                      */
/*  ISaGRAF program name : RETAIN_A                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Messages */


/* Functions */

