/**********************************************************************/
/*                                                                    */
/*  File name : TX_X.H                                                */
/*  Date      : 07.10.2014 13:21:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur                                      */
/*  ISaGRAF program name : TX_X                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












