/**********************************************************************/
/*                                                                    */
/*  File name : appli.H                                               */
/*  Date      : 24.09.2020 10:05:34                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : apcmn                                      */
/*                                                                    */
/**********************************************************************/

/* Global variables of the various programs */

/* Programs */

#define _SCC_IOS	0X0001
#define _SCC_CONTROL	0X0002
#define _SCC_SEM	0X0003
#define _SCC_SYNC	0X0004

/* Booleans */

#define _SCC_IO000A_00	0X0001
#define _SCC_NET_14	0X0004
#define _SCC_NET_13	0X0005
#define _SCC_NET_12	0X0006
#define _SCC_NET_11	0X0007
#define _SCC_NET_3	0X0008
#define _SCC_NET_2	0X0009
#define _SCC_NET_1	0X000A
#define _SCC_TO_VODA	0X000B
#define _SCC_RUN	0X000C
#define _SCC_TOUT	0X000D
#define _SCC_TS	0X000E
#define _SCC_UNLOOK	0X000F
#define _SCC_LOOK	0X0010
#define _SCC_BUSY	0X0011
#define _SCC_DOZVIL_5	0X0012
#define _SCC_DOZVIL_4	0X0013
#define _SCC_DOZVIL_3	0X0014
#define _SCC_DOZVIL_2	0X0015
#define _SCC_DOZVIL_1	0X0016
#define _SCC_NET_15	0X0017
#define _SCC_CBOO00000001	0X001B
#define _SCC_CBOO00000000	0X001C
#define _SCC_TMPB3	0X001D
#define _SCC_TMPB2	0X001E
#define _SCC_TMPB1	0X001F
#define _SCC_TMPB8	0X0025
#define _SCC_TMPB7	0X0026
#define _SCC_TMPB5	0X0027
#define _SCC_TMPB4	0X0028
#define _SCC_TMPB14	0X0029
#define _SCC_TMPB13	0X002A
#define _SCC_TMPB11	0X002B
#define _SCC_TMPB10	0X002C
#define _SCC_TMPB17	0X002E
#define _SCC_TMPB16	0X002F
#define _SCC_TMPB19	0X0030
#define _SCC_DUMMYCOIL	0X003E
#define _SCC_TMPB9	0X003F
#define _SCC_TMPB6	0X0040
#define _SCC_ED1_9ACC4449_DOZVIL_VA	0X0041
#define _SCC_ED1_9ACC4447_DZ_VA	0X0044
#define _SCC_ED1_9ACC4447_DOZVIL_VA	0X0045
#define _SCC_ED1_9ACC4448_DZ_VA	0X0046
#define _SCC_ED1_9ACC4448_DOZVIL_VA	0X0047
#define _SCC_ED1_9ACC4449_DZ_VA	0X0048
#define _SCC_ED1_9ACC4445_DZ_VA	0X0049
#define _SCC_ED1_9ACC4445_DOZVIL_VA	0X004A
#define _SCC_ED1_9ACC4446_DZ_VA	0X004B
#define _SCC_ED1_9ACC4446_DOZVIL_VA	0X004C

/* Analogs */

#define _SCC_IO0009_00	0X0001
#define _SCC_V_01	0X0002
#define _SCC_V_02	0X0003
#define _SCC_V_03	0X0004
#define _SCC_V_04	0X0005
#define _SCC_V_05	0X0006
#define _SCC_V_06	0X0007
#define _SCC_V_07	0X0008
#define _SCC_V_08	0X0009
#define _SCC_CFSTATE_3	0X0012
#define _SCC_CFSTATE_2	0X0013
#define _SCC_CFSTATE_1	0X0014
#define _SCC_STATE_3	0X0015
#define _SCC_STATE_2	0X0016
#define _SCC_STATE_1	0X0017
#define _SCC_V_09	0X0018
#define _SCC_OB_5	0X0019
#define _SCC_OB_4	0X001A
#define _SCC_OB_3	0X001B
#define _SCC_OB_2	0X001C
#define _SCC_OB_1	0X001D
#define _SCC_CFSTATE_5	0X001E
#define _SCC_CFSTATE_4	0X001F
#define _SCC_CANA00000010	0X0022
#define _SCC_CANA00000005	0X0023
#define _SCC_CANA000003D4	0X0024
#define _SCC_CANA00000014	0X0025
#define _SCC_CANA00000008	0X0026
#define _SCC_CANA0000000D	0X0027
#define _SCC_CANA0000000E	0X0028
#define _SCC_CANA0000000F	0X0029
#define _SCC_CANA0000000B	0X002A
#define _SCC_CANA0000000C	0X002B
#define _SCC_CANA00000001	0X002C
#define _SCC_CANA00000004	0X002D
#define _SCC_CANA00000002	0X002E
#define _SCC_CANA00000003	0X002F
#define _SCC_REAL_NULL	0X0030
#define _SCC_FBL_RET	0X0035
#define _SCC_TMPR9	0X0043
#define _SCC_TMPR8	0X0044
#define _SCC_TMPR7	0X0045
#define _SCC_TMPR6	0X0046
#define _SCC_TMPR5	0X0047
#define _SCC_TMPR4	0X0048
#define _SCC_TMPR3	0X0049
#define _SCC_TMPR2	0X004A

/* Timers */

#define _SCC_CTMR0000EA60	0X0001
#define _SCC_CTMR000007D0	0X0002
#define _SCC_CTMR000000FA	0X0003
#define _SCC_CTMR00001770	0X0004

/* Functions */

#define _SCC_EBUS_STS	0X0001
#define _SCC_V0_10_TO	0X0002
#define _SCC_A4_20_TO	0X0003

/* Function blocks */

#define _SCC_STD_R_TRIG	0X0004

#define _SCC_STD_TON	0X0009

#define _SCC_STD_SEMA	0X000C

#define _SCC_STD_AVERAGE	0X0011

#define _SCC_STD_BLINK	0X0013

#define _SCC_I_7017	0X0015

#define _SCC_EBUS_F_W	0X0016

#define _SCC_EBUS_N_R	0X0017

#define _SCC_EBUS_B_W	0X0018
