/**********************************************************************/
/*                                                                    */
/*  File name : CONTROL.H                                             */
/*  Date      : 24.09.2020 10:05:34                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : apcmn                                      */
/*  ISaGRAF program name : CONTROL                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */

#define _SCC_CONTROL_TMPR1	0X0033
#define _SCC_CONTROL_TMPR2	0X0034

/* Timers */


/* Functions */


/* Function blocks */









