/**********************************************************************/
/*                                                                    */
/*  File name : SEM.H                                                 */
/*  Date      : 24.09.2020 10:05:34                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : apcmn                                      */
/*  ISaGRAF program name : SEM                                        */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_SEM_ED1_9ACC444A_Q_VA	0X0042
#define _SCC_SEM_ED1_9ACC444B_BUSY_VA	0X0043

/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */


#define _SCC_SEM_ED1_9ACC444A	0X0006

#define _SCC_SEM_ED1_9ACC444B	0X0001






