/**********************************************************************/
/*                                                                    */
/*  File name : SYNC.H                                                */
/*  Date      : 24.09.2020 10:05:34                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : apcmn                                      */
/*  ISaGRAF program name : SYNC                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_SYNC_DZ	0X0018
#define _SCC_SYNC_DOZVIL	0X0019
#define _SCC_SYNC_LINK	0X001A

/* Analogs */

#define _SCC_SYNC_ST_NEW	0X0020
#define _SCC_SYNC_OB	0X0021

/* Timers */


/* Functions */


/* Function blocks */









