/**********************************************************************/
/*                                                                    */
/*  File name : appli.H                                               */
/*  Date      : 02.07.2010 15:58:32                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : kf_emit                                    */
/*                                                                    */
/**********************************************************************/

/* Global variables of the various programs */

/* Programs */

#define _SCC_ISO	0X0001
#define _SCC_MAIN	0X0002

/* Booleans */

#define _SCC_X_DL	0X0001
#define _SCC_X_KT	0X0002
#define _SCC_X_KH	0X0003
#define _SCC_Y_BW	0X0004
#define _SCC_Y_FW	0X0005
#define _SCC_P	0X0006
#define _SCC_IO	0X0007
#define _SCC_CBOO00000000	0X0009
#define _SCC_DUMMYCOIL	0X000D
#define _SCC_TMPB2	0X0016
#define _SCC_TMPB1	0X0017

/* Analogs */

#define _SCC_IO0000_00	0X0001
#define _SCC_RC	0X0002
#define _SCC_CANA00000036	0X0003
#define _SCC_CANA00000001	0X0004
#define _SCC_CANA00000002	0X0005
#define _SCC_CANA00000000	0X0006
#define _SCC_FBL_RET	0X0007
#define _SCC_TMPI3	0X0008

/* Timers */

#define _SCC_CTMR0001D4C0	0X0001
#define _SCC_CTMR000009C4	0X0002
#define _SCC_CTMR000001F4	0X0003

/* Function blocks */

#define _SCC_STD_SR	0X0003

#define _SCC_STD_TON	0X0009

#define _SCC_I_7060D	0X0015
