/**********************************************************************/
/*                                                                    */
/*  File name : ISO.H                                                 */
/*  Date      : 02.07.2010 15:58:32                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : kf_emit                                    */
/*  ISaGRAF program name : ISO                                        */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_ISO_ED1_2E6F0F52_BI2__VA	0X000A
#define _SCC_ISO_ED1_2E6F0F52_BI1__VA	0X000B
#define _SCC_ISO_ED1_2E6F0F52_Q__VA	0X000C
#define _SCC_ISO_ED1_2E6F0F4E_Q1_VA	0X000E
#define _SCC_ISO_ED1_2E6F0F4F_Q1_VA	0X000F
#define _SCC_ISO_ED1_2E6F0F50_Q_VA	0X0010
#define _SCC_ISO_ED1_2E6F0F51_Q1_VA	0X0011
#define _SCC_ISO_ED1_V0001	0X0012
#define _SCC_ISO_ED1_2E6F0F4B_Q_VA	0X0013
#define _SCC_ISO_ED1_2E6F0F4C_Q1_VA	0X0014
#define _SCC_ISO_ED1_2E6F0F4D_Q_VA	0X0015

/* Analogs */


/* Timers */


/* Function blocks */

#define _SCC_ISO_ED1_2E6F0F4E	0X0001
#define _SCC_ISO_ED1_2E6F0F4F	0X0002
#define _SCC_ISO_ED1_2E6F0F51	0X0003
#define _SCC_ISO_ED1_2E6F0F4C	0X0004

#define _SCC_ISO_ED1_2E6F0F50	0X0001
#define _SCC_ISO_ED1_2E6F0F4B	0X0002
#define _SCC_ISO_ED1_2E6F0F4D	0X0003

#define _SCC_ISO_ED1_2E6F0F52	0X0001
