/**********************************************************************/
/*                                                                    */
/*  File name : MAIN.H                                                */
/*  Date      : 02.07.2010 15:58:32                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : kf_emit                                    */
/*  ISaGRAF program name : MAIN                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MAIN_RE	0X0008

/* Analogs */


/* Timers */


/* Function blocks */



