/**********************************************************************/
/*                                                                    */
/*  File name : DISPATCH.H                                            */
/*  Date      : 24.09.2017 10:34:06                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : lfpn                                       */
/*  ISaGRAF program name : DISPATCH                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_DISPATCH_ED1_C7EC8F50_Q_VA	0X00B9

/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */



#define _SCC_DISPATCH_ED1_C7EC8F50	0X0023










