/**********************************************************************/
/*                                                                    */
/*  File name : DRIVER.H                                              */
/*  Date      : 24.09.2017 10:34:06                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : lfpn                                       */
/*  ISaGRAF program name : DRIVER                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_DRIVER_I_LOW	0X0068

/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */













