/**********************************************************************/
/*                                                                    */
/*  File name : EEP_N_W.H                                             */
/*  Date      : 24.09.2017 10:34:06                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : lfpn                                       */
/*  ISaGRAF program name : EEP_N_W                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */













