/**********************************************************************/
/*                                                                    */
/*  File name : MAIN.H                                                */
/*  Date      : 24.09.2017 10:34:06                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : lfpn                                       */
/*  ISaGRAF program name : MAIN                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MAIN_FE_GZAG	0X0060
#define _SCC_MAIN_RE_TEST	0X0061
#define _SCC_MAIN_RE_FOTT	0X0062
#define _SCC_MAIN_RE_X_STOP	0X0063
#define _SCC_MAIN_RE_TS_LOT	0X0064
#define _SCC_MAIN_RE_X6B	0X0065
#define _SCC_MAIN_FE_X4B	0X0066
#define _SCC_MAIN_RE_X4B	0X0067

/* Analogs */

#define _SCC_MAIN_T_P_S	0X0070
#define _SCC_MAIN_K_V	0X0071
#define _SCC_MAIN_Q_M_M	0X0072
#define _SCC_MAIN_HB_1	0X0073
#define _SCC_MAIN_H0_1	0X0074
#define _SCC_MAIN_TMPR1	0X00B5
#define _SCC_MAIN_TMPR10	0X00B6
#define _SCC_MAIN_TMPR3	0X00B7
#define _SCC_MAIN_TMPR11	0X00B8
#define _SCC_MAIN_TMPR5	0X00B9
#define _SCC_MAIN_TMPR8	0X00BA
#define _SCC_MAIN_TMPR9	0X00BC

/* Timers */


/* Functions */


/* Function blocks */













