/**********************************************************************/
/*                                                                    */
/*  File name : PARM_STO.H                                            */
/*  Date      : 24.09.2017 10:34:06                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : lfpn                                       */
/*  ISaGRAF program name : PARM_STO                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARM_STO_RES	0X0058
#define _SCC_PARM_STO_READ	0X0059

/* Analogs */

#define _SCC_PARM_STO_STATUS_OLD	0X0066
#define _SCC_PARM_STO_SAV_ST	0X0067

/* Timers */


/* Functions */


/* Function blocks */













