/**********************************************************************/
/*                                                                    */
/*  File name : MAIN.H                                                */
/*  Date      : 11.10.2017 15:26:43                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : testmvg                                    */
/*  ISaGRAF program name : MAIN                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MAIN_R_L	0X0083
#define _SCC_MAIN_RE_TPER	0X00B4

/* Analogs */

#define _SCC_MAIN_NC_2	0X0084
#define _SCC_MAIN_I	0X0085
#define _SCC_MAIN_NFW	0X0086
#define _SCC_MAIN_RUNF	0X0087
#define _SCC_MAIN_NF	0X0088

/* Timers */


/* Functions */


/* Function blocks */





