/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_3.H                                             */
/*  Date      : 13.10.2017 13:51:19                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fltrmvg                                    */
/*  ISaGRAF program name : FL_FB_3                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_3_ED1_DE5F029F_Q__VA	0X0127
#define _SCC_FL_FB_3_ED1_DE5F029E_BI8__VA	0X0128
#define _SCC_FL_FB_3_ED1_DE5F029E_BI6__VA	0X0129
#define _SCC_FL_FB_3_ED1_DE5F029E_BI5__VA	0X012A
#define _SCC_FL_FB_3_ED1_DE5F029E_BI4__VA	0X012B
#define _SCC_FL_FB_3_ED1_DE5F029E_BI3__VA	0X012C
#define _SCC_FL_FB_3_ED1_DE5F029E_BI2__VA	0X012D
#define _SCC_FL_FB_3_ED1_DE5F029E_BI1__VA	0X012E
#define _SCC_FL_FB_3_ED1_DE5F029E_Q__VA	0X012F
#define _SCC_FL_FB_3_ED1_DE5F029B_Q_VA	0X0130
#define _SCC_FL_FB_3_ED1_DE5F029C_Q_VA	0X0131
#define _SCC_FL_FB_3_ED1_DE5F029D_Q_VA	0X0132
#define _SCC_FL_FB_3_ED1_DE5F0298_Q_VA	0X0133
#define _SCC_FL_FB_3_ED1_DE5F0299_Q_VA	0X0134
#define _SCC_FL_FB_3_ED1_DE5F029A_Q_VA	0X0135
#define _SCC_FL_FB_3_ED1_DE5F0295_Q_VA	0X0136
#define _SCC_FL_FB_3_ED1_DE5F0296_Q_VA	0X0137
#define _SCC_FL_FB_3_ED1_DE5F0297_Q_VA	0X0138
#define _SCC_FL_FB_3_ED1_DE5F0292_Q_VA	0X0139
#define _SCC_FL_FB_3_ED1_DE5F0293_Q_VA	0X013A
#define _SCC_FL_FB_3_ED1_DE5F0294_Q_VA	0X013B
#define _SCC_FL_FB_3_ED1_DE5F028F_Q_VA	0X013C
#define _SCC_FL_FB_3_ED1_DE5F0290_Q_VA	0X013D
#define _SCC_FL_FB_3_ED1_DE5F0291_Q_VA	0X013E
#define _SCC_FL_FB_3_ED1_DE5F028B_Q_VA	0X013F
#define _SCC_FL_FB_3_ED1_DE5F028C_Q_VA	0X0140
#define _SCC_FL_FB_3_ED1_DE5F028D_Q_VA	0X0141
#define _SCC_FL_FB_3_ED1_DE5F028E_Q_VA	0X0142
#define _SCC_FL_FB_3_ED1_V0001	0X0143
#define _SCC_FL_FB_3_ED1_V0002	0X0144
#define _SCC_FL_FB_3_ED1_V0003	0X0145
#define _SCC_FL_FB_3_ED1_V0004	0X0146
#define _SCC_FL_FB_3_ED1_V0005	0X0147
#define _SCC_FL_FB_3_ED1_V0006	0X0148
#define _SCC_FL_FB_3_ED1_V0007	0X0149
#define _SCC_FL_FB_3_ED1_V0008	0X014A
#define _SCC_FL_FB_3_ED1_V0009	0X014B
#define _SCC_FL_FB_3_ED1_V000A	0X014C
#define _SCC_FL_FB_3_ED1_V000B	0X014D
#define _SCC_FL_FB_3_ED1_V000C	0X014E

/* Analogs */


/* Timers */

#define _SCC_FL_FB_3_ED1_DE5F0298_ET_VA	0X0031
#define _SCC_FL_FB_3_ED1_DE5F0295_ET_VA	0X0032
#define _SCC_FL_FB_3_ED1_DE5F0296_ET_VA	0X0033
#define _SCC_FL_FB_3_ED1_DE5F0297_ET_VA	0X0034
#define _SCC_FL_FB_3_ED1_DE5F028B_ET_VA	0X0035

/* Messages */


/* Functions */


/* Function blocks */


#define _SCC_FL_FB_3_ED1_DE5F029C	0X001B
#define _SCC_FL_FB_3_ED1_DE5F029D	0X001C
#define _SCC_FL_FB_3_ED1_DE5F0299	0X001D
#define _SCC_FL_FB_3_ED1_DE5F029A	0X001E
#define _SCC_FL_FB_3_ED1_DE5F029B	0X001F
#define _SCC_FL_FB_3_ED1_DE5F0295	0X0020
#define _SCC_FL_FB_3_ED1_DE5F0296	0X0021
#define _SCC_FL_FB_3_ED1_DE5F0297	0X0022
#define _SCC_FL_FB_3_ED1_DE5F0298	0X0023
#define _SCC_FL_FB_3_ED1_DE5F0293	0X0024
#define _SCC_FL_FB_3_ED1_DE5F0294	0X0025
#define _SCC_FL_FB_3_ED1_DE5F028D	0X0026
#define _SCC_FL_FB_3_ED1_DE5F028B	0X0027

#define _SCC_FL_FB_3_ED1_DE5F0292	0X000D
#define _SCC_FL_FB_3_ED1_DE5F028F	0X000E
#define _SCC_FL_FB_3_ED1_DE5F0290	0X000F
#define _SCC_FL_FB_3_ED1_DE5F0291	0X0010
#define _SCC_FL_FB_3_ED1_DE5F028C	0X0011
#define _SCC_FL_FB_3_ED1_DE5F028E	0X0012







#define _SCC_FL_FB_3_ED1_DE5F029F	0X0003

#define _SCC_FL_FB_3_ED1_DE5F029E	0X0003
