/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_1.H                                             */
/*  Date      : 13.10.2017 13:51:19                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fltrmvg                                    */
/*  ISaGRAF program name : FL_FB_1                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_1_ED1_DE5EFF9D_Q__VA	0X00D3
#define _SCC_FL_FB_1_ED1_DE5EFF9C_BI8__VA	0X00D4
#define _SCC_FL_FB_1_ED1_DE5EFF9C_BI6__VA	0X00D5
#define _SCC_FL_FB_1_ED1_DE5EFF9C_BI5__VA	0X00D6
#define _SCC_FL_FB_1_ED1_DE5EFF9C_BI4__VA	0X00D7
#define _SCC_FL_FB_1_ED1_DE5EFF9C_BI3__VA	0X00D8
#define _SCC_FL_FB_1_ED1_DE5EFF9C_BI2__VA	0X00D9
#define _SCC_FL_FB_1_ED1_DE5EFF9C_BI1__VA	0X00DA
#define _SCC_FL_FB_1_ED1_DE5EFF9C_Q__VA	0X00DB
#define _SCC_FL_FB_1_ED1_DE5EFF99_Q_VA	0X00DC
#define _SCC_FL_FB_1_ED1_DE5EFF9A_Q_VA	0X00DD
#define _SCC_FL_FB_1_ED1_DE5EFF9B_Q_VA	0X00DE
#define _SCC_FL_FB_1_ED1_DE5EFF96_Q_VA	0X00DF
#define _SCC_FL_FB_1_ED1_DE5EFF97_Q_VA	0X00E0
#define _SCC_FL_FB_1_ED1_DE5EFF98_Q_VA	0X00E1
#define _SCC_FL_FB_1_ED1_DE5EFF93_Q_VA	0X00E2
#define _SCC_FL_FB_1_ED1_DE5EFF94_Q_VA	0X00E3
#define _SCC_FL_FB_1_ED1_DE5EFF95_Q_VA	0X00E4
#define _SCC_FL_FB_1_ED1_DE5EFF90_Q_VA	0X00E5
#define _SCC_FL_FB_1_ED1_DE5EFF91_Q_VA	0X00E6
#define _SCC_FL_FB_1_ED1_DE5EFF92_Q_VA	0X00E7
#define _SCC_FL_FB_1_ED1_DE5EFF8D_Q_VA	0X00E8
#define _SCC_FL_FB_1_ED1_DE5EFF8E_Q_VA	0X00E9
#define _SCC_FL_FB_1_ED1_DE5EFF8F_Q_VA	0X00EA
#define _SCC_FL_FB_1_ED1_DE5EFF89_Q_VA	0X00EB
#define _SCC_FL_FB_1_ED1_DE5EFF8A_Q_VA	0X00EC
#define _SCC_FL_FB_1_ED1_DE5EFF8B_Q_VA	0X00ED
#define _SCC_FL_FB_1_ED1_DE5EFF8C_Q_VA	0X00EE
#define _SCC_FL_FB_1_ED1_V0001	0X00EF
#define _SCC_FL_FB_1_ED1_V0002	0X00F0
#define _SCC_FL_FB_1_ED1_V0003	0X00F1
#define _SCC_FL_FB_1_ED1_V0004	0X00F2
#define _SCC_FL_FB_1_ED1_V0005	0X00F3
#define _SCC_FL_FB_1_ED1_V0006	0X00F4
#define _SCC_FL_FB_1_ED1_V0007	0X00F5
#define _SCC_FL_FB_1_ED1_V0008	0X00F6
#define _SCC_FL_FB_1_ED1_V0009	0X00F7
#define _SCC_FL_FB_1_ED1_V000A	0X00F8
#define _SCC_FL_FB_1_ED1_V000B	0X00F9
#define _SCC_FL_FB_1_ED1_V000C	0X00FA

/* Analogs */


/* Timers */

#define _SCC_FL_FB_1_ED1_DE5EFF96_ET_VA	0X001B
#define _SCC_FL_FB_1_ED1_DE5EFF93_ET_VA	0X001C
#define _SCC_FL_FB_1_ED1_DE5EFF94_ET_VA	0X001D
#define _SCC_FL_FB_1_ED1_DE5EFF95_ET_VA	0X001E
#define _SCC_FL_FB_1_ED1_DE5EFF89_ET_VA	0X001F

/* Messages */


/* Functions */


/* Function blocks */


#define _SCC_FL_FB_1_ED1_DE5EFF9A	0X0001
#define _SCC_FL_FB_1_ED1_DE5EFF9B	0X0002
#define _SCC_FL_FB_1_ED1_DE5EFF97	0X0003
#define _SCC_FL_FB_1_ED1_DE5EFF98	0X0004
#define _SCC_FL_FB_1_ED1_DE5EFF99	0X0005
#define _SCC_FL_FB_1_ED1_DE5EFF93	0X0006
#define _SCC_FL_FB_1_ED1_DE5EFF94	0X0007
#define _SCC_FL_FB_1_ED1_DE5EFF95	0X0008
#define _SCC_FL_FB_1_ED1_DE5EFF96	0X0009
#define _SCC_FL_FB_1_ED1_DE5EFF91	0X000A
#define _SCC_FL_FB_1_ED1_DE5EFF92	0X000B
#define _SCC_FL_FB_1_ED1_DE5EFF8B	0X000C
#define _SCC_FL_FB_1_ED1_DE5EFF89	0X000D

#define _SCC_FL_FB_1_ED1_DE5EFF90	0X0001
#define _SCC_FL_FB_1_ED1_DE5EFF8D	0X0002
#define _SCC_FL_FB_1_ED1_DE5EFF8E	0X0003
#define _SCC_FL_FB_1_ED1_DE5EFF8F	0X0004
#define _SCC_FL_FB_1_ED1_DE5EFF8A	0X0005
#define _SCC_FL_FB_1_ED1_DE5EFF8C	0X0006







#define _SCC_FL_FB_1_ED1_DE5EFF9D	0X0001

#define _SCC_FL_FB_1_ED1_DE5EFF9C	0X0001
