/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_4.H                                             */
/*  Date      : 13.10.2017 13:51:19                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fltrmvg                                    */
/*  ISaGRAF program name : FL_FB_4                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_4_ED1_DE5F03A0_Q__VA	0X014F
#define _SCC_FL_FB_4_ED1_DE5F039F_BI8__VA	0X0150
#define _SCC_FL_FB_4_ED1_DE5F039F_BI6__VA	0X0151
#define _SCC_FL_FB_4_ED1_DE5F039F_BI5__VA	0X0152
#define _SCC_FL_FB_4_ED1_DE5F039F_BI4__VA	0X0153
#define _SCC_FL_FB_4_ED1_DE5F039F_BI3__VA	0X0154
#define _SCC_FL_FB_4_ED1_DE5F039F_BI2__VA	0X0155
#define _SCC_FL_FB_4_ED1_DE5F039F_BI1__VA	0X0156
#define _SCC_FL_FB_4_ED1_DE5F039F_Q__VA	0X0157
#define _SCC_FL_FB_4_ED1_DE5F039C_Q_VA	0X0158
#define _SCC_FL_FB_4_ED1_DE5F039D_Q_VA	0X0159
#define _SCC_FL_FB_4_ED1_DE5F039E_Q_VA	0X015A
#define _SCC_FL_FB_4_ED1_DE5F0399_Q_VA	0X015B
#define _SCC_FL_FB_4_ED1_DE5F039A_Q_VA	0X015C
#define _SCC_FL_FB_4_ED1_DE5F039B_Q_VA	0X015D
#define _SCC_FL_FB_4_ED1_DE5F0396_Q_VA	0X015E
#define _SCC_FL_FB_4_ED1_DE5F0397_Q_VA	0X015F
#define _SCC_FL_FB_4_ED1_DE5F0398_Q_VA	0X0160
#define _SCC_FL_FB_4_ED1_DE5F0393_Q_VA	0X0161
#define _SCC_FL_FB_4_ED1_DE5F0394_Q_VA	0X0162
#define _SCC_FL_FB_4_ED1_DE5F0395_Q_VA	0X0163
#define _SCC_FL_FB_4_ED1_DE5F0390_Q_VA	0X0164
#define _SCC_FL_FB_4_ED1_DE5F0391_Q_VA	0X0165
#define _SCC_FL_FB_4_ED1_DE5F0392_Q_VA	0X0166
#define _SCC_FL_FB_4_ED1_DE5F038C_Q_VA	0X0167
#define _SCC_FL_FB_4_ED1_DE5F038D_Q_VA	0X0168
#define _SCC_FL_FB_4_ED1_DE5F038E_Q_VA	0X0169
#define _SCC_FL_FB_4_ED1_DE5F038F_Q_VA	0X016A
#define _SCC_FL_FB_4_ED1_V0001	0X016B
#define _SCC_FL_FB_4_ED1_V0002	0X016C
#define _SCC_FL_FB_4_ED1_V0003	0X016D
#define _SCC_FL_FB_4_ED1_V0004	0X016E
#define _SCC_FL_FB_4_ED1_V0005	0X016F
#define _SCC_FL_FB_4_ED1_V0006	0X0170
#define _SCC_FL_FB_4_ED1_V0007	0X0171
#define _SCC_FL_FB_4_ED1_V0008	0X0172
#define _SCC_FL_FB_4_ED1_V0009	0X0173
#define _SCC_FL_FB_4_ED1_V000A	0X0174
#define _SCC_FL_FB_4_ED1_V000B	0X0175
#define _SCC_FL_FB_4_ED1_V000C	0X0176

/* Analogs */


/* Timers */

#define _SCC_FL_FB_4_ED1_DE5F0399_ET_VA	0X0036
#define _SCC_FL_FB_4_ED1_DE5F0396_ET_VA	0X0037
#define _SCC_FL_FB_4_ED1_DE5F0397_ET_VA	0X0038
#define _SCC_FL_FB_4_ED1_DE5F0398_ET_VA	0X0039
#define _SCC_FL_FB_4_ED1_DE5F038C_ET_VA	0X003A

/* Messages */


/* Functions */


/* Function blocks */


#define _SCC_FL_FB_4_ED1_DE5F039D	0X0028
#define _SCC_FL_FB_4_ED1_DE5F039E	0X0029
#define _SCC_FL_FB_4_ED1_DE5F039A	0X002A
#define _SCC_FL_FB_4_ED1_DE5F039B	0X002B
#define _SCC_FL_FB_4_ED1_DE5F039C	0X002C
#define _SCC_FL_FB_4_ED1_DE5F0396	0X002D
#define _SCC_FL_FB_4_ED1_DE5F0397	0X002E
#define _SCC_FL_FB_4_ED1_DE5F0398	0X002F
#define _SCC_FL_FB_4_ED1_DE5F0399	0X0030
#define _SCC_FL_FB_4_ED1_DE5F0394	0X0031
#define _SCC_FL_FB_4_ED1_DE5F0395	0X0032
#define _SCC_FL_FB_4_ED1_DE5F038E	0X0033
#define _SCC_FL_FB_4_ED1_DE5F038C	0X0034

#define _SCC_FL_FB_4_ED1_DE5F0393	0X0013
#define _SCC_FL_FB_4_ED1_DE5F0390	0X0014
#define _SCC_FL_FB_4_ED1_DE5F0391	0X0015
#define _SCC_FL_FB_4_ED1_DE5F0392	0X0016
#define _SCC_FL_FB_4_ED1_DE5F038D	0X0017
#define _SCC_FL_FB_4_ED1_DE5F038F	0X0018







#define _SCC_FL_FB_4_ED1_DE5F03A0	0X0004

#define _SCC_FL_FB_4_ED1_DE5F039F	0X0004
