/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_2.H                                             */
/*  Date      : 13.10.2017 13:51:19                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fltrmvg                                    */
/*  ISaGRAF program name : FL_FB_2                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_2_ED1_DE5F009E_Q__VA	0X00FF
#define _SCC_FL_FB_2_ED1_DE5F009D_BI8__VA	0X0100
#define _SCC_FL_FB_2_ED1_DE5F009D_BI6__VA	0X0101
#define _SCC_FL_FB_2_ED1_DE5F009D_BI5__VA	0X0102
#define _SCC_FL_FB_2_ED1_DE5F009D_BI4__VA	0X0103
#define _SCC_FL_FB_2_ED1_DE5F009D_BI3__VA	0X0104
#define _SCC_FL_FB_2_ED1_DE5F009D_BI2__VA	0X0105
#define _SCC_FL_FB_2_ED1_DE5F009D_BI1__VA	0X0106
#define _SCC_FL_FB_2_ED1_DE5F009D_Q__VA	0X0107
#define _SCC_FL_FB_2_ED1_DE5F009A_Q_VA	0X0108
#define _SCC_FL_FB_2_ED1_DE5F009B_Q_VA	0X0109
#define _SCC_FL_FB_2_ED1_DE5F009C_Q_VA	0X010A
#define _SCC_FL_FB_2_ED1_DE5F0097_Q_VA	0X010B
#define _SCC_FL_FB_2_ED1_DE5F0098_Q_VA	0X010C
#define _SCC_FL_FB_2_ED1_DE5F0099_Q_VA	0X010D
#define _SCC_FL_FB_2_ED1_DE5F0094_Q_VA	0X010E
#define _SCC_FL_FB_2_ED1_DE5F0095_Q_VA	0X010F
#define _SCC_FL_FB_2_ED1_DE5F0096_Q_VA	0X0110
#define _SCC_FL_FB_2_ED1_DE5F0091_Q_VA	0X0111
#define _SCC_FL_FB_2_ED1_DE5F0092_Q_VA	0X0112
#define _SCC_FL_FB_2_ED1_DE5F0093_Q_VA	0X0113
#define _SCC_FL_FB_2_ED1_DE5F008E_Q_VA	0X0114
#define _SCC_FL_FB_2_ED1_DE5F008F_Q_VA	0X0115
#define _SCC_FL_FB_2_ED1_DE5F0090_Q_VA	0X0116
#define _SCC_FL_FB_2_ED1_DE5F008A_Q_VA	0X0117
#define _SCC_FL_FB_2_ED1_DE5F008B_Q_VA	0X0118
#define _SCC_FL_FB_2_ED1_DE5F008C_Q_VA	0X0119
#define _SCC_FL_FB_2_ED1_DE5F008D_Q_VA	0X011A
#define _SCC_FL_FB_2_ED1_V0001	0X011B
#define _SCC_FL_FB_2_ED1_V0002	0X011C
#define _SCC_FL_FB_2_ED1_V0003	0X011D
#define _SCC_FL_FB_2_ED1_V0004	0X011E
#define _SCC_FL_FB_2_ED1_V0005	0X011F
#define _SCC_FL_FB_2_ED1_V0006	0X0120
#define _SCC_FL_FB_2_ED1_V0007	0X0121
#define _SCC_FL_FB_2_ED1_V0008	0X0122
#define _SCC_FL_FB_2_ED1_V0009	0X0123
#define _SCC_FL_FB_2_ED1_V000A	0X0124
#define _SCC_FL_FB_2_ED1_V000B	0X0125
#define _SCC_FL_FB_2_ED1_V000C	0X0126

/* Analogs */


/* Timers */

#define _SCC_FL_FB_2_ED1_DE5F0097_ET_VA	0X002C
#define _SCC_FL_FB_2_ED1_DE5F0094_ET_VA	0X002D
#define _SCC_FL_FB_2_ED1_DE5F0095_ET_VA	0X002E
#define _SCC_FL_FB_2_ED1_DE5F0096_ET_VA	0X002F
#define _SCC_FL_FB_2_ED1_DE5F008A_ET_VA	0X0030

/* Messages */


/* Functions */


/* Function blocks */


#define _SCC_FL_FB_2_ED1_DE5F009B	0X000E
#define _SCC_FL_FB_2_ED1_DE5F009C	0X000F
#define _SCC_FL_FB_2_ED1_DE5F0098	0X0010
#define _SCC_FL_FB_2_ED1_DE5F0099	0X0011
#define _SCC_FL_FB_2_ED1_DE5F009A	0X0012
#define _SCC_FL_FB_2_ED1_DE5F0094	0X0013
#define _SCC_FL_FB_2_ED1_DE5F0095	0X0014
#define _SCC_FL_FB_2_ED1_DE5F0096	0X0015
#define _SCC_FL_FB_2_ED1_DE5F0097	0X0016
#define _SCC_FL_FB_2_ED1_DE5F0092	0X0017
#define _SCC_FL_FB_2_ED1_DE5F0093	0X0018
#define _SCC_FL_FB_2_ED1_DE5F008C	0X0019
#define _SCC_FL_FB_2_ED1_DE5F008A	0X001A

#define _SCC_FL_FB_2_ED1_DE5F0091	0X0007
#define _SCC_FL_FB_2_ED1_DE5F008E	0X0008
#define _SCC_FL_FB_2_ED1_DE5F008F	0X0009
#define _SCC_FL_FB_2_ED1_DE5F0090	0X000A
#define _SCC_FL_FB_2_ED1_DE5F008B	0X000B
#define _SCC_FL_FB_2_ED1_DE5F008D	0X000C







#define _SCC_FL_FB_2_ED1_DE5F009E	0X0002

#define _SCC_FL_FB_2_ED1_DE5F009D	0X0002
