/**********************************************************************/
/*                                                                    */
/*  File name : MAIN.H                                                */
/*  Date      : 13.10.2017 13:51:19                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fltrmvg                                    */
/*  ISaGRAF program name : MAIN                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MAIN_R_L	0X0085
#define _SCC_MAIN_RE_TPER	0X00B6

/* Analogs */

#define _SCC_MAIN_NFW	0X0088
#define _SCC_MAIN_RUNF	0X0089
#define _SCC_MAIN_NF	0X008A
#define _SCC_MAIN_NC_2	0X008B
#define _SCC_MAIN_I	0X008C

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */











