/**********************************************************************/
/*                                                                    */
/*  File name : OFF_ALL.H                                             */
/*  Date      : 13.10.2017 13:51:19                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fltrmvg                                    */
/*  ISaGRAF program name : OFF_ALL                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_OFF_ALL_OFF_ALL	0X00B7

/* Analogs */


/* Timers */


/* Messages */


/* Functions */


/* Function blocks */











