/**********************************************************************/
/*                                                                    */
/*  File name : PARM_RAM.H                                            */
/*  Date      : 13.10.2017 13:51:19                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fltrmvg                                    */
/*  ISaGRAF program name : PARM_RAM                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARM_RAM_INIT	0X0060

/* Analogs */

#define _SCC_PARM_RAM_II	0X0080
#define _SCC_PARM_RAM_ADR	0X0081

/* Timers */


/* Messages */

#define _SCC_PARM_RAM_TMPM1	0X0001
#define _SCC_PARM_RAM_TMPM2	0X0002
#define _SCC_PARM_RAM_TMPM3	0X0003
#define _SCC_PARM_RAM_TMPM4	0X0004

/* Functions */


/* Function blocks */











