/**********************************************************************/
/*                                                                    */
/*  File name : RUNNER.H                                              */
/*  Date      : 13.10.2017 13:51:19                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fltrmvg                                    */
/*  ISaGRAF program name : RUNNER                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_RUNNER_ED1_DE5EFD90_Q_VA	0X00CE
#define _SCC_RUNNER_ED1_DE5EFD91_Q_VA	0X00CF
#define _SCC_RUNNER_ED1_DE5EFD7E_Q_VA	0X00D0
#define _SCC_RUNNER_ED1_DE5EFD7F_Q_VA	0X00D1
#define _SCC_RUNNER_ED1_DE5EFD7A_Q__VA	0X00D2

/* Analogs */

#define _SCC_RUNNER_TMPR1	0X00A9
#define _SCC_RUNNER_TMPR4	0X00AA
#define _SCC_RUNNER_ED1_DE5EFD8F_XOUT_VA	0X00B2
#define _SCC_RUNNER_ED1_DE5EFD8B_XOUT_VA	0X00B3
#define _SCC_RUNNER_ED1_DE5EFD8C_XOUT_VA	0X00B4
#define _SCC_RUNNER_ED1_DE5EFD8D_XOUT_VA	0X00B5
#define _SCC_RUNNER_ED1_DE5EFD8E_XOUT_VA	0X00B6
#define _SCC_RUNNER_ED1_DE5EFD88_XOUT_VA	0X00B7
#define _SCC_RUNNER_ED1_DE5EFD89_XOUT_VA	0X00B8
#define _SCC_RUNNER_ED1_DE5EFD8A_XOUT_VA	0X00B9
#define _SCC_RUNNER_ED1_DE5EFD85_XOUT_VA	0X00BA
#define _SCC_RUNNER_ED1_DE5EFD86_XOUT_VA	0X00BB
#define _SCC_RUNNER_ED1_DE5EFD87_XOUT_VA	0X00BC
#define _SCC_RUNNER_ED1_DE5EFD82_XOUT_VA	0X00BD
#define _SCC_RUNNER_ED1_DE5EFD83_XOUT_VA	0X00BE
#define _SCC_RUNNER_ED1_DE5EFD84_XOUT_VA	0X00BF
#define _SCC_RUNNER_ED1_DE5EFD7D_YY__VA	0X00C0
#define _SCC_RUNNER_ED1_DE5EFD80_XOUT_VA	0X00C1
#define _SCC_RUNNER_ED1_DE5EFD81_XOUT_VA	0X00C2
#define _SCC_RUNNER_ED1_DE5EFD7C_SS__VA	0X00C3
#define _SCC_RUNNER_ED1_DE5EFD7C_MM__VA	0X00C4
#define _SCC_RUNNER_ED1_DE5EFD7C_HH__VA	0X00C5
#define _SCC_RUNNER_ED1_DE5EFD7D_DD__VA	0X00C6
#define _SCC_RUNNER_ED1_DE5EFD7D_MM__VA	0X00C7

/* Timers */

#define _SCC_RUNNER_PER	0X0001

/* Messages */


/* Functions */


/* Function blocks */

#define _SCC_RUNNER_ED1_DE5EFD90	0X0001
#define _SCC_RUNNER_ED1_DE5EFD7E	0X0002



#define _SCC_RUNNER_ED1_DE5EFD8F	0X0001
#define _SCC_RUNNER_ED1_DE5EFD8C	0X0002
#define _SCC_RUNNER_ED1_DE5EFD8D	0X0003
#define _SCC_RUNNER_ED1_DE5EFD8E	0X0004
#define _SCC_RUNNER_ED1_DE5EFD88	0X0005
#define _SCC_RUNNER_ED1_DE5EFD89	0X0006
#define _SCC_RUNNER_ED1_DE5EFD8A	0X0007
#define _SCC_RUNNER_ED1_DE5EFD8B	0X0008
#define _SCC_RUNNER_ED1_DE5EFD85	0X0009
#define _SCC_RUNNER_ED1_DE5EFD86	0X000A
#define _SCC_RUNNER_ED1_DE5EFD87	0X000B
#define _SCC_RUNNER_ED1_DE5EFD82	0X000C
#define _SCC_RUNNER_ED1_DE5EFD83	0X000D
#define _SCC_RUNNER_ED1_DE5EFD84	0X000E
#define _SCC_RUNNER_ED1_DE5EFD80	0X000F
#define _SCC_RUNNER_ED1_DE5EFD81	0X0010

#define _SCC_RUNNER_ED1_DE5EFD91	0X0001
#define _SCC_RUNNER_ED1_DE5EFD7F	0X0002

#define _SCC_RUNNER_ED1_DE5EFD7B	0X0001

#define _SCC_RUNNER_ED1_DE5EFD7C	0X0001

#define _SCC_RUNNER_ED1_DE5EFD7D	0X0001

#define _SCC_RUNNER_ED1_DE5EFD7A	0X0001


