/**********************************************************************/
/*                                                                    */
/*  File name : appli.H                                               */
/*  Date      : 17.08.2018 13:03:56                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : myreg                                      */
/*                                                                    */
/**********************************************************************/

/* Global variables of the various programs */

/* Programs */

#define _SCC_PROG	0X0001
#define _SCC_PI_DUO	0X0002
#define _SCC_PIDMY	0X0003

/* Booleans */

#define _SCC_AM_15	0X0003
#define _SCC_ZONE	0X0004
#define _SCC_AM_20	0X0005
#define _SCC_CBOO00000001	0X000A
#define _SCC_CBOO00000000	0X000B
#define _SCC_ED1_771FF3B8_ZONE__VA	0X000C
#define _SCC_ED1_771FF3B8_ZONE0__VA	0X000D
#define _SCC_DUMMYCOIL	0X000E
#define _SCC_TMPB2	0X000F
#define _SCC_TMPB1	0X0010

/* Analogs */

#define _SCC_XMAX_20	0X0001
#define _SCC_XMAX_15	0X0002
#define _SCC_TI_20	0X0003
#define _SCC_TI_15	0X0004
#define _SCC_KPR_20	0X0005
#define _SCC_KPR_15	0X0006
#define _SCC_SUM	0X0011
#define _SCC_XT_20	0X0012
#define _SCC_XT_15	0X0013
#define _SCC_XMIN_20	0X0014
#define _SCC_XMIN_15	0X0015
#define _SCC_C_20	0X0016
#define _SCC_C_15	0X0017
#define _SCC_SP_15	0X0018
#define _SCC_V_09	0X0019
#define _SCC_CANA00000000	0X0034
#define _SCC_CANA00000002	0X0035
#define _SCC_FBL_RET	0X0038
#define _SCC_ED1_771FF3B8_SUM0__VA	0X0039
#define _SCC_ED1_771FF3B8_XOUT_N_VA	0X003A
#define _SCC_ED1_771FF3B8_XOUT_P_VA	0X003B
#define _SCC_ED1_771FF3B8_SUM_N_VA	0X003C
#define _SCC_ED1_771FF3B8_SUM_P_VA	0X003D
#define _SCC_ED1_771FF3B8_XT_N_VA	0X003E
#define _SCC_ED1_771FF3B8_XT_P_VA	0X003F
#define _SCC_ED1_771FF3B8_SUM__VA	0X0040
#define _SCC_ED1_771FF3B8_KE_N_VA	0X0041
#define _SCC_ED1_771FF3B8_KE_P_VA	0X0042
#define _SCC_TMPI2	0X0043
#define _SCC_TMPR1	0X0044
#define _SCC_TMPR4	0X0045
#define _SCC_TMPR2	0X0046
