/**********************************************************************/
/*                                                                    */
/*  File name : PI_DUO.H                                              */
/*  Date      : 17.08.2018 13:03:56                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : myreg                                      */
/*  ISaGRAF program name : PI_DUO                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PI_DUO_ZONE_	0X0001
#define _SCC_PI_DUO_ZONE0_	0X0002
#define _SCC_PI_DUO_AM_N	0X0006
#define _SCC_PI_DUO_AM_P	0X0007

/* Analogs */

#define _SCC_PI_DUO_SUM_N	0X0007
#define _SCC_PI_DUO_SUM_P	0X0008
#define _SCC_PI_DUO_XT_N	0X0009
#define _SCC_PI_DUO_XT_P	0X000A
#define _SCC_PI_DUO_SUM_	0X000B
#define _SCC_PI_DUO_KE_N	0X000C
#define _SCC_PI_DUO_KE_P	0X000D
#define _SCC_PI_DUO_SUM0_	0X000E
#define _SCC_PI_DUO_XOUT_N	0X000F
#define _SCC_PI_DUO_XOUT_P	0X0010
#define _SCC_PI_DUO_XMAX_N	0X001A
#define _SCC_PI_DUO_XMIN_N	0X001B
#define _SCC_PI_DUO_TI_N	0X001C
#define _SCC_PI_DUO_KPR_N	0X001D
#define _SCC_PI_DUO_XMAX_P	0X001E
#define _SCC_PI_DUO_XMIN_P	0X001F
#define _SCC_PI_DUO_TI_P	0X0020
#define _SCC_PI_DUO_KPR_P	0X0021
#define _SCC_PI_DUO_X0_N	0X0022
#define _SCC_PI_DUO_X0_P	0X0023
#define _SCC_PI_DUO_SP_	0X0024
#define _SCC_PI_DUO_PV_	0X0025
#define _SCC_PI_DUO_TMPR3	0X0037
