/**********************************************************************/
/*                                                                    */
/*  File name : PIDMY.H                                               */
/*  Date      : 17.08.2018 13:03:56                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : myreg                                      */
/*  ISaGRAF program name : PIDMY                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PIDMY_AUTO_	0X0008
#define _SCC_PIDMY_MODE_	0X0009

/* Analogs */

#define _SCC_PIDMY_SUM0_	0X0026
#define _SCC_PIDMY_XOUT_	0X0027
#define _SCC_PIDMY_XMAX_	0X0028
#define _SCC_PIDMY_XMIN_	0X0029
#define _SCC_PIDMY_P0_	0X002A
#define _SCC_PIDMY_TD_	0X002B
#define _SCC_PIDMY_TI_	0X002C
#define _SCC_PIDMY_KP_	0X002D
#define _SCC_PIDMY_X0_	0X002E
#define _SCC_PIDMY_SP_	0X002F
#define _SCC_PIDMY_PV_	0X0030
#define _SCC_PIDMY_KE_	0X0031
#define _SCC_PIDMY_SUM_	0X0032
#define _SCC_PIDMY_XT_	0X0033
#define _SCC_PIDMY_TMPR3	0X0036
