/**********************************************************************/
/*                                                                    */
/*  File name : appli.H                                               */
/*  Date      : 02.02.2017 13:12:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : test                                       */
/*                                                                    */
/**********************************************************************/

/* Global variables of the various programs */

/* Programs */

#define _SCC_TEST	0X0001

/* Booleans */

#define _SCC_RESET	0X0001
#define _SCC_START	0X0002
#define _SCC_DZ_TEST	0X0003
#define _SCC_WATERFLOW	0X0004
#define _SCC_X_VC	0X0005
#define _SCC_SAVE	0X0006
#define _SCC_DUMMYCOIL	0X0008

/* Analogs */

#define _SCC_IO0009_00	0X0001
#define _SCC_MAX_CI	0X0002
#define _SCC_I_AVG	0X0003
#define _SCC_V_8	0X0004
#define _SCC_V_7	0X0005
#define _SCC_V_6	0X0006
#define _SCC_V_5	0X0007
#define _SCC_V_4	0X0008
#define _SCC_V_3	0X0009
#define _SCC_V_2	0X000A
#define _SCC_V_1	0X000B
#define _SCC_STATUS	0X000C
#define _SCC_PV_SPD	0X000D
#define _SCC_CANA00000005	0X000E
#define _SCC_FBL_RET	0X000F

/* Timers */

#define _SCC_TI	0X0001
#define _SCC_DTSP	0X0002
#define _SCC_TSP	0X0003

/* Function blocks */

#define _SCC_I_7017	0X0015
