/**********************************************************************/
/*                                                                    */
/*  File name : EEP_N_W.H                                             */
/*  Date      : 05.08.2015 17:38:54                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : test                                       */
/*  ISaGRAF program name : EEP_N_W                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Functions */

