/**********************************************************************/
/*                                                                    */
/*  File name : EEP_PR.H                                              */
/*  Date      : 05.08.2015 17:38:54                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : test                                       */
/*  ISaGRAF program name : EEP_PR                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Functions */

