/**********************************************************************/
/*                                                                    */
/*  File name : TEST.H                                                */
/*  Date      : 02.02.2017 13:12:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : test                                       */
/*  ISaGRAF program name : TEST                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_TEST_ED1_93A0BDC0_Q__VA	0X0007

/* Analogs */

#define _SCC_TEST_ED1_93A0BDC0_NI8__VA	0X0010
#define _SCC_TEST_ED1_93A0BDC0_NI7__VA	0X0011
#define _SCC_TEST_ED1_93A0BDC0_NI6__VA	0X0012
#define _SCC_TEST_ED1_93A0BDC0_NI5__VA	0X0013
#define _SCC_TEST_ED1_93A0BDC0_NI4__VA	0X0014
#define _SCC_TEST_ED1_93A0BDC0_NI3__VA	0X0015
#define _SCC_TEST_ED1_93A0BDC0_NI2__VA	0X0016
#define _SCC_TEST_ED1_93A0BDC0_NI1__VA	0X0017

/* Timers */


/* Function blocks */

#define _SCC_TEST_ED1_93A0BDC0	0X0001
