/**********************************************************************/
/*                                                                    */
/*  File name : BLEDING.H                                             */
/*  Date      : 29.09.2020 11:49:16                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : difu2019                                   */
/*  ISaGRAF program name : BLEDING                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_BLEDING_P_06	0X007A
#define _SCC_BLEDING_P_05	0X007B
#define _SCC_BLEDING_P_04	0X007C
#define _SCC_BLEDING_P_03	0X007D
#define _SCC_BLEDING_P_02	0X007E
#define _SCC_BLEDING_P_01	0X007F
#define _SCC_BLEDING_RE_TS0	0X0080

/* Analogs */

#define _SCC_BLEDING_CB_04	0X0157
#define _SCC_BLEDING_CB_03	0X0158
#define _SCC_BLEDING_CB_02	0X0159
#define _SCC_BLEDING_CB_01	0X015A
#define _SCC_BLEDING_CBT	0X015B
#define _SCC_BLEDING_CB_06	0X015C
#define _SCC_BLEDING_CB_05	0X015D

/* Timers */

#define _SCC_BLEDING_TP_06	0X0001
#define _SCC_BLEDING_TP_05	0X0002
#define _SCC_BLEDING_TP_04	0X0003
#define _SCC_BLEDING_TP_03	0X0004
#define _SCC_BLEDING_TP_02	0X0005
#define _SCC_BLEDING_TP_01	0X0006

/* Messages */


/* Functions */


/* Function blocks */














