drop schema if exists centrif;
create schema centrif;
use centrif;

create table Cf1(
Dt integer unsigned not null,
Q_man integer default '0',
Gzag_s integer default '0',
Gzag_c integer default '0',
I_a integer default '0',
I_b integer default '0',
Iavg integer default '0',
Q_pr_zd integer default '0',
Gzag integer default '0',
Qall integer default '0',
Q_reg integer default '0',
Q_prl integer default '0',
Q_pr integer default '0',
Q_man_r integer default '0',
Nc integer default '0',
T_all integer default '0',
T_reg integer default '0',
T_prl integer default '0',
T_fug integer default '0',
T_pr integer default '0',
T_nt integer default '0',
Error integer default '0',
Status integer default '0',
State integer default '0',
Ob integer default '0',
Fott integer default '0',
Fsgr integer default '0',
Tvod integer default '0',
pv_spd integer default '0',
Xtorm integer default '0',
XLotok integer default '0',
Xshib integer default '0',
Xsgrb integer default '0',
Xsgrz integer default '0',
Xdsph integer default '0',
Xdspl integer default '0',
X_Vc integer default '0',
X_Vv integer default '0',
X_Luk integer default '0',
X_Stop integer default '0',
X_Endz integer default '0',
X_man integer default '0',
X_Alarm integer default '0',
Gzag_end integer default '0',
drv_fail integer default '0',
cf_fail integer default '0',
dz_fail integer default '0',
YTrom integer default '0',
YLotok integer default '0',
Yshib integer default '0',
Yprl integer default '0',
Ysir integer default '0',
Ypr integer default '0',
Ysgr integer default '0',
Ydsp integer default '0',
YCool integer default '0',
Y_KM1 integer default '0',
Y_KM2 integer default '0',
Y_KM3 integer default '0',
Y_KM4 integer default '0',
Y_Tyr integer default '0',
Y_L_fw integer default '0',
Y_L_bw integer default '0',
a_dsp integer default '0',
a_torm integer default '0',
a_sgr integer default '0',
a_Shib integer default '0',
a_lot integer default '0',
a_vv integer default '0',
vc_fail integer default '0',
a_all integer default '0',
primary key(Dt)
);

create table Cf2(
Dt integer unsigned not null,
Q_man integer default '0',
Gzag_s integer default '0',
Gzag_c integer default '0',
I_a integer default '0',
I_b integer default '0',
Iavg integer default '0',
Q_pr_zd integer default '0',
Gzag integer default '0',
Qall integer default '0',
Q_reg integer default '0',
Q_prl integer default '0',
Q_pr integer default '0',
Q_man_r integer default '0',
Nc integer default '0',
T_all integer default '0',
T_reg integer default '0',
T_prl integer default '0',
T_fug integer default '0',
T_pr integer default '0',
T_nt integer default '0',
Error integer default '0',
Status integer default '0',
State integer default '0',
Ob integer default '0',
Fott integer default '0',
Fsgr integer default '0',
Tvod integer default '0',
pv_spd integer default '0',
Xtorm integer default '0',
XLotok integer default '0',
Xshib integer default '0',
Xsgrb integer default '0',
Xsgrz integer default '0',
Xdsph integer default '0',
Xdspl integer default '0',
X_Vc integer default '0',
X_Vv integer default '0',
X_Luk integer default '0',
X_Stop integer default '0',
X_Endz integer default '0',
X_man integer default '0',
X_Alarm integer default '0',
Gzag_end integer default '0',
drv_fail integer default '0',
cf_fail integer default '0',
dz_fail integer default '0',
YTrom integer default '0',
YLotok integer default '0',
Yshib integer default '0',
Yprl integer default '0',
Ysir integer default '0',
Ypr integer default '0',
Ysgr integer default '0',
Ydsp integer default '0',
YCool integer default '0',
Y_KM1 integer default '0',
Y_KM2 integer default '0',
Y_KM3 integer default '0',
Y_KM4 integer default '0',
Y_Tyr integer default '0',
Y_L_fw integer default '0',
Y_L_bw integer default '0',
a_dsp integer default '0',
a_torm integer default '0',
a_sgr integer default '0',
a_Shib integer default '0',
a_lot integer default '0',
a_vv integer default '0',
vc_fail integer default '0',
a_all integer default '0',
primary key(Dt)
);

create table Cf3(
Dt integer unsigned not null,
Q_man integer default '0',
Gzag_s integer default '0',
Gzag_c integer default '0',
I_a integer default '0',
I_b integer default '0',
Iavg integer default '0',
Q_pr_zd integer default '0',
Gzag integer default '0',
Qall integer default '0',
Q_reg integer default '0',
Q_prl integer default '0',
Q_pr integer default '0',
Q_man_r integer default '0',
Nc integer default '0',
T_all integer default '0',
T_reg integer default '0',
T_prl integer default '0',
T_fug integer default '0',
T_pr integer default '0',
T_nt integer default '0',
Error integer default '0',
Status integer default '0',
State integer default '0',
Ob integer default '0',
Fott integer default '0',
Fsgr integer default '0',
Tvod integer default '0',
pv_spd integer default '0',
Xtorm integer default '0',
XLotok integer default '0',
Xshib integer default '0',
Xsgrb integer default '0',
Xsgrz integer default '0',
Xdsph integer default '0',
Xdspl integer default '0',
X_Vc integer default '0',
X_Vv integer default '0',
X_Luk integer default '0',
X_Stop integer default '0',
X_Endz integer default '0',
X_man integer default '0',
X_Alarm integer default '0',
Gzag_end integer default '0',
drv_fail integer default '0',
cf_fail integer default '0',
dz_fail integer default '0',
YTrom integer default '0',
YLotok integer default '0',
Yshib integer default '0',
Yprl integer default '0',
Ysir integer default '0',
Ypr integer default '0',
Ysgr integer default '0',
Ydsp integer default '0',
YCool integer default '0',
Y_KM1 integer default '0',
Y_KM2 integer default '0',
Y_KM3 integer default '0',
Y_KM4 integer default '0',
Y_Tyr integer default '0',
Y_L_fw integer default '0',
Y_L_bw integer default '0',
a_dsp integer default '0',
a_torm integer default '0',
a_sgr integer default '0',
a_Shib integer default '0',
a_lot integer default '0',
a_vv integer default '0',
vc_fail integer default '0',
a_all integer default '0',
primary key(Dt)
);


create table Cf4(
Dt integer unsigned not null,
Q_man integer default '0',
Gzag_s integer default '0',
Gzag_c integer default '0',
I_a integer default '0',
I_b integer default '0',
Iavg integer default '0',
Q_pr_zd integer default '0',
Gzag integer default '0',
Qall integer default '0',
Q_reg integer default '0',
Q_prl integer default '0',
Q_pr integer default '0',
Q_man_r integer default '0',
Nc integer default '0',
T_all integer default '0',
T_reg integer default '0',
T_prl integer default '0',
T_fug integer default '0',
T_pr integer default '0',
T_nt integer default '0',
Error integer default '0',
Status integer default '0',
State integer default '0',
Ob integer default '0',
Fott integer default '0',
Fsgr integer default '0',
Tvod integer default '0',
pv_spd integer default '0',
Xtorm integer default '0',
XLotok integer default '0',
Xshib integer default '0',
Xsgrb integer default '0',
Xsgrz integer default '0',
Xdsph integer default '0',
Xdspl integer default '0',
X_Vc integer default '0',
X_Vv integer default '0',
X_Luk integer default '0',
X_Stop integer default '0',
X_Endz integer default '0',
X_man integer default '0',
X_Alarm integer default '0',
Gzag_end integer default '0',
drv_fail integer default '0',
cf_fail integer default '0',
dz_fail integer default '0',
YTrom integer default '0',
YLotok integer default '0',
Yshib integer default '0',
Yprl integer default '0',
Ysir integer default '0',
Ypr integer default '0',
Ysgr integer default '0',
Ydsp integer default '0',
YCool integer default '0',
Y_KM1 integer default '0',
Y_KM2 integer default '0',
Y_KM3 integer default '0',
Y_KM4 integer default '0',
Y_Tyr integer default '0',
Y_L_fw integer default '0',
Y_L_bw integer default '0',
a_dsp integer default '0',
a_torm integer default '0',
a_sgr integer default '0',
a_Shib integer default '0',
a_lot integer default '0',
a_vv integer default '0',
vc_fail integer default '0',
a_all integer default '0',
primary key(Dt)
);


create table Cf5(
Dt integer unsigned not null,
Q_man integer default '0',
Gzag_s integer default '0',
Gzag_c integer default '0',
I_a integer default '0',
I_b integer default '0',
Iavg integer default '0',
Q_pr_zd integer default '0',
Gzag integer default '0',
Qall integer default '0',
Q_reg integer default '0',
Q_prl integer default '0',
Q_pr integer default '0',
Q_man_r integer default '0',
Nc integer default '0',
T_all integer default '0',
T_reg integer default '0',
T_prl integer default '0',
T_fug integer default '0',
T_pr integer default '0',
T_nt integer default '0',
Error integer default '0',
Status integer default '0',
State integer default '0',
Ob integer default '0',
Fott integer default '0',
Fsgr integer default '0',
Tvod integer default '0',
pv_spd integer default '0',
Xtorm integer default '0',
XLotok integer default '0',
Xshib integer default '0',
Xsgrb integer default '0',
Xsgrz integer default '0',
Xdsph integer default '0',
Xdspl integer default '0',
X_Vc integer default '0',
X_Vv integer default '0',
X_Luk integer default '0',
X_Stop integer default '0',
X_Endz integer default '0',
X_man integer default '0',
X_Alarm integer default '0',
Gzag_end integer default '0',
drv_fail integer default '0',
cf_fail integer default '0',
dz_fail integer default '0',
YTrom integer default '0',
YLotok integer default '0',
Yshib integer default '0',
Yprl integer default '0',
Ysir integer default '0',
Ypr integer default '0',
Ysgr integer default '0',
Ydsp integer default '0',
YCool integer default '0',
Y_KM1 integer default '0',
Y_KM2 integer default '0',
Y_KM3 integer default '0',
Y_KM4 integer default '0',
Y_Tyr integer default '0',
Y_L_fw integer default '0',
Y_L_bw integer default '0',
a_dsp integer default '0',
a_torm integer default '0',
a_sgr integer default '0',
a_Shib integer default '0',
a_lot integer default '0',
a_vv integer default '0',
vc_fail integer default '0',
a_all integer default '0',
primary key(Dt)
);



create table trend(
Dt integer unsigned not null,
V01 integer default '0',
V02 integer default '0',
V03 integer default '0',
V04 integer default '0',
V05 integer default '0',
V06 integer default '0',
V07 integer default '0',
V08 integer default '0',
C_01 integer default '0',
C_02 integer default '0',
C_03 integer default '0',
C_04 integer default '0',
Y_01 integer default '0',
Y_02 integer default '0',
Y_03 integer default '0',
Y_04 integer default '0',
primary key(Dt));


create table report(
id integer unsigned not NULL auto_increment,
cft timestamp default '00-01-01 00:00:00',
nCf integer default '0',
T_all integer default '0',
T_reg integer default '0',
T_prl integer default '0',
T_fug integer default '0',
T_pr integer default '0',
T_nt integer default '0',
Nc integer default '0',
Gzag integer default '0',
Q_pr_zd integer default '0',
Q_man integer default '0',
Qall integer default '0',
Q_reg integer default '0',
Q_prl integer default '0',
Q_pr integer default '0',
primary key(id),
key s(cft,nCf)
) Engine=InnoDb;

