/**********************************************************************/
/*                                                                    */
/*  File name : PARA.H                                                */
/*  Date      : 26.09.2019 12:45:23                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : rou3                                       */
/*  ISaGRAF program name : PARA                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARA_TMPB1	0X0097

/* Analogs */

#define _SCC_PARA_TERM	0X00DE
#define _SCC_PARA_PRESH	0X00DF
#define _SCC_PARA_R1	0X00E0
#define _SCC_PARA_R0	0X00E1
#define _SCC_PARA_T_	0X00E2
#define _SCC_PARA_P_	0X00E3
#define _SCC_PARA_IY	0X00E4
#define _SCC_PARA_IX	0X00E5
#define _SCC_PARA_MAX1	0X00E6
#define _SCC_PARA_MAX0	0X00E7
#define _SCC_PARA_MIN1	0X00E8
#define _SCC_PARA_MIN0	0X00E9
#define _SCC_PARA_PARA	0X00EA
#define _SCC_PARA_TMPR1	0X0152
#define _SCC_PARA_TMPR10	0X0154
#define _SCC_PARA_TMPR3	0X0156
#define _SCC_PARA_TMPR4	0X0157
#define _SCC_PARA_TMPR22	0X0158
#define _SCC_PARA_TMPR5	0X0159
#define _SCC_PARA_TMPR6	0X015B
#define _SCC_PARA_TMPR7	0X015D
#define _SCC_PARA_TMPR8	0X0160
#define _SCC_PARA_TMPI4	0X01C7
#define _SCC_PARA_TMPR2	0X01C8
#define _SCC_PARA_TMPR19	0X01C9
#define _SCC_PARA_TMPR17	0X01CA
#define _SCC_PARA_TMPR16	0X01CB
#define _SCC_PARA_TMPI11	0X01CC
#define _SCC_PARA_TMPR15	0X01CD
#define _SCC_PARA_TMPI9	0X01CE
#define _SCC_PARA_TMPR14	0X01CF
#define _SCC_PARA_TMPI8	0X01D0
#define _SCC_PARA_TMPR13	0X01D1
#define _SCC_PARA_TMPI7	0X01D2
#define _SCC_PARA_TMPR11	0X01D3
#define _SCC_PARA_TMPR9	0X01D4
#define _SCC_PARA_TMPR29	0X01D5
#define _SCC_PARA_TMPR28	0X01D6
#define _SCC_PARA_TMPR27	0X01D7
#define _SCC_PARA_TMPR26	0X01D8
#define _SCC_PARA_TMPR25	0X01D9
#define _SCC_PARA_TMPR24	0X01DA
#define _SCC_PARA_TMPI16	0X01DB
#define _SCC_PARA_TMPI15	0X01DC
#define _SCC_PARA_TMPI14	0X01DD
#define _SCC_PARA_TMPI13	0X01DE
#define _SCC_PARA_TMPI12	0X01DF
#define _SCC_PARA_TMPR21	0X01E0

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */

















