/**********************************************************************/
/*                                                                    */
/*  File name : SLOW_UP.H                                             */
/*  Date      : 26.09.2019 12:45:23                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : rou3                                       */
/*  ISaGRAF program name : SLOW_UP                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_SLOW_UP_FIRST	0X0057

/* Analogs */

#define _SCC_SLOW_UP_OUT_	0X00F3
#define _SCC_SLOW_UP_MAX_	0X00F4
#define _SCC_SLOW_UP_MIN_	0X00F5
#define _SCC_SLOW_UP_IN_	0X00F6
#define _SCC_SLOW_UP_LOCOUT	0X00F7
#define _SCC_SLOW_UP_DELTA	0X00F8

/* Timers */

#define _SCC_SLOW_UP_TUP_	0X0003

/* Messages */


/* Functions */


/* Function blocks */

















