/**********************************************************************/
/*                                                                    */
/*  File name : appli.H                                               */
/*  Date      : 04.09.2011 12:22:50                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : redcmn                                     */
/*                                                                    */
/**********************************************************************/

/* Global variables of the various programs */

/* Programs */

#define _SCC_IOS	0X0001
#define _SCC_CONTROL	0X0002
#define _SCC_SEM	0X0003
#define _SCC_SYNC	0X0004

/* Booleans */

#define _SCC_IO000C_00	0X0001
#define _SCC_IO010C_00	0X0002
#define _SCC_IO020C_00	0X0003
#define _SCC_AM_01	0X0004
#define _SCC_X_01	0X0005
#define _SCC_X_10	0X0006
#define _SCC_X_02	0X0007
#define _SCC_X_11	0X0008
#define _SCC_Y_01	0X0009
#define _SCC_X_03	0X000A
#define _SCC_X_12	0X000B
#define _SCC_Y_02	0X000C
#define _SCC_X_04	0X000D
#define _SCC_X_13	0X000E
#define _SCC_Y_03	0X000F
#define _SCC_X_05	0X0010
#define _SCC_X_14	0X0011
#define _SCC_Y_04	0X0012
#define _SCC_X_06	0X0013
#define _SCC_X_15	0X0014
#define _SCC_Y_05	0X0015
#define _SCC_X_07	0X0016
#define _SCC_X_16	0X0017
#define _SCC_Y_06	0X0018
#define _SCC_X_08	0X0019
#define _SCC_Y_07	0X001A
#define _SCC_X_09	0X001B
#define _SCC_Y_08	0X001C
#define _SCC_DOZVIL_1	0X001D
#define _SCC_DOZVIL_2	0X001E
#define _SCC_DOZVIL_3	0X001F
#define _SCC_DOZVIL_4	0X0020
#define _SCC_DOZVIL_5	0X0021
#define _SCC_NET_2	0X0022
#define _SCC_NET_1	0X0023
#define _SCC_TOUT	0X0024
#define _SCC_TS	0X0025
#define _SCC_UNLOOK	0X0026
#define _SCC_LOOK	0X0027
#define _SCC_BUSY	0X0028
#define _SCC_RUN	0X0029
#define _SCC_NET_5	0X002A
#define _SCC_NET_4	0X002B
#define _SCC_NET_3	0X002C
#define _SCC_CBOO00000001	0X0031
#define _SCC_CBOO00000000	0X0032
#define _SCC_DUMMYCOIL	0X0033
#define _SCC_TMPB1	0X003F
#define _SCC_TMPB2	0X0043
#define _SCC_ED1_63CFE448_DOZVIL_VA	0X0045
#define _SCC_ED1_63CFE449_DZ_VA	0X0046
#define _SCC_ED1_63CFE449_DOZVIL_VA	0X0047
#define _SCC_ED1_63CFE446_DZ_VA	0X0049
#define _SCC_ED1_63CFE446_DOZVIL_VA	0X004A
#define _SCC_ED1_63CFE447_DZ_VA	0X004B
#define _SCC_ED1_63CFE447_DOZVIL_VA	0X004C
#define _SCC_ED1_63CFE448_DZ_VA	0X004D
#define _SCC_ED1_63CFE445_DZ_VA	0X004E
#define _SCC_ED1_63CFE445_DOZVIL_VA	0X004F
#define _SCC_TMPB3	0X0050
#define _SCC_TMPB6	0X0051
#define _SCC_TMPB5	0X0052
#define _SCC_TMPB4	0X0053

/* Analogs */

#define _SCC_FS_V_05	0X0001
#define _SCC_FS_V_06	0X0002
#define _SCC_FS_V_07	0X0003
#define _SCC_FS_V_08	0X0004
#define _SCC_TVOD_I	0X0005
#define _SCC_V_01	0X0006
#define _SCC_V_10	0X0007
#define _SCC_V_02	0X0008
#define _SCC_V_11	0X0009
#define _SCC_V_03	0X000A
#define _SCC_V_12	0X000B
#define _SCC_V_04	0X000C
#define _SCC_V_13	0X000D
#define _SCC_STATE_1	0X000E
#define _SCC_STATE_2	0X000F
#define _SCC_STATE_3	0X0010
#define _SCC_V_05	0X0011
#define _SCC_STATE_4	0X0012
#define _SCC_V_14	0X0013
#define _SCC_STATE_5	0X0014
#define _SCC_V_06	0X0015
#define _SCC_V_15	0X0016
#define _SCC_V_07	0X0017
#define _SCC_V_16	0X0018
#define _SCC_V_08	0X0019
#define _SCC_V_09	0X001A
#define _SCC_PSIR_I	0X001B
#define _SCC_AI_8	0X001C
#define _SCC_AI_7	0X001D
#define _SCC_AI_6	0X001E
#define _SCC_AI_5	0X001F
#define _SCC_AI_4	0X0020
#define _SCC_AI_3	0X0021
#define _SCC_AI_2	0X0022
#define _SCC_AI_1	0X0023
#define _SCC_OB_5	0X0024
#define _SCC_OB_4	0X0025
#define _SCC_OB_3	0X0026
#define _SCC_OB_2	0X0027
#define _SCC_OB_1	0X0028
#define _SCC_CANA00000005	0X002B
#define _SCC_CANA000003D4	0X002C
#define _SCC_CANA00000010	0X002D
#define _SCC_CANA00000002	0X002E
#define _SCC_CANA00000003	0X002F
#define _SCC_CANA00000004	0X0030
#define _SCC_CANA000055F0	0X0031
#define _SCC_CANA0000000D	0X0032
#define _SCC_CANA00000019	0X0033
#define _SCC_CANA00000006	0X0034
#define _SCC_CANA00000001	0X0035
#define _SCC_CANA00000000	0X0036
#define _SCC_REAL_NULL	0X0037
#define _SCC_FBL_RET	0X003E
#define _SCC_TMPI9	0X0053
#define _SCC_TMPI8	0X0054
#define _SCC_TMPI7	0X0055
#define _SCC_TMPI6	0X0056
#define _SCC_TMPI5	0X0057
#define _SCC_TMPI4	0X0058
#define _SCC_TMPI3	0X0059
#define _SCC_TMPI2	0X005A
#define _SCC_TMPR2	0X005B

/* Timers */

#define _SCC_T_SET	0X0001
#define _SCC_CTMR0000EA60	0X0002
#define _SCC_CTMR00001770	0X0003
#define _SCC_CTMR000007D0	0X0004
#define _SCC_CTMR000000FA	0X0005

/* Functions */

#define _SCC_A4_20_TO	0X0001
#define _SCC_REAL_INT	0X0002

/* Function blocks */

#define _SCC_STD_R_TRIG	0X0004

#define _SCC_STD_TON	0X0009

#define _SCC_STD_SEMA	0X000C

#define _SCC_STD_AVERAGE	0X0011

#define _SCC_STD_BLINK	0X0013

#define _SCC_EBUS_N_W	0X0015

#define _SCC_EBUS_N_R	0X0016

#define _SCC_EBUS_B_W	0X0017
