/**********************************************************************/
/*                                                                    */
/*  File name : CONTROL.H                                             */
/*  Date      : 04.09.2011 12:22:52                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : redcmn                                     */
/*  ISaGRAF program name : CONTROL                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_CONTROL_FE_AM_01	0X002D

/* Analogs */

#define _SCC_CONTROL_TMPR1	0X003D

/* Timers */


/* Functions */


/* Function blocks */








