/**********************************************************************/
/*                                                                    */
/*  File name : IOS.H                                                 */
/*  Date      : 04.09.2011 12:22:51                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : redcmn                                     */
/*  ISaGRAF program name : IOS                                        */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_IOS_ED1_63CFB45D_Q_VA	0X0034
#define _SCC_IOS_ED1_63CFB45E_Q_VA	0X0035
#define _SCC_IOS_ED1_63CFB459_Q_VA	0X0036
#define _SCC_IOS_ED1_63CFB45A_Q_VA	0X0037
#define _SCC_IOS_ED1_63CFB456_Q_VA	0X0038
#define _SCC_IOS_ED1_63CFB457_Q_VA	0X0039
#define _SCC_IOS_ED1_63CFB453_Q_VA	0X003A
#define _SCC_IOS_ED1_63CFB454_Q_VA	0X003B
#define _SCC_IOS_ED1_63CFB450_Q_VA	0X003C
#define _SCC_IOS_ED1_63CFB451_Q_VA	0X003D
#define _SCC_IOS_ED1_63CFB44B_Q_VA	0X003E
#define _SCC_IOS_ED1_V0001	0X0040
#define _SCC_IOS_ED1_V0002	0X0041
#define _SCC_IOS_ED1_V0003	0X0042

/* Analogs */

#define _SCC_IOS_TMPR1	0X0038
#define _SCC_IOS_TMPR3	0X0039
#define _SCC_IOS_TMPR4	0X003A
#define _SCC_IOS_TMPR5	0X003B
#define _SCC_IOS_TMPR6	0X003C
#define _SCC_IOS_ED1_63CFB464_XOUT_VA	0X003F
#define _SCC_IOS_ED1_63CFB465_XOUT_VA	0X0040
#define _SCC_IOS_ED1_63CFB466_XOUT_VA	0X0041
#define _SCC_IOS_ED1_63CFB461_XOUT_VA	0X0042
#define _SCC_IOS_ED1_63CFB462_XOUT_VA	0X0043
#define _SCC_IOS_ED1_63CFB463_XOUT_VA	0X0044
#define _SCC_IOS_ED1_63CFB45F_XOUT_VA	0X0045
#define _SCC_IOS_ED1_63CFB460_XOUT_VA	0X0046
#define _SCC_IOS_ED1_63CFB45B_N3__VA	0X0047
#define _SCC_IOS_ED1_63CFB45B_N2__VA	0X0048
#define _SCC_IOS_ED1_63CFB45B_N1__VA	0X0049
#define _SCC_IOS_ED1_63CFB458_N3__VA	0X004A
#define _SCC_IOS_ED1_63CFB458_N2__VA	0X004B
#define _SCC_IOS_ED1_63CFB458_N1__VA	0X004C
#define _SCC_IOS_ED1_63CFB455_N2__VA	0X004D
#define _SCC_IOS_ED1_63CFB455_N1__VA	0X004E
#define _SCC_IOS_ED1_63CFB455_N3__VA	0X004F
#define _SCC_IOS_ED1_63CFB452_N3__VA	0X0050
#define _SCC_IOS_ED1_63CFB452_N2__VA	0X0051
#define _SCC_IOS_ED1_63CFB452_N1__VA	0X0052

/* Timers */


/* Functions */


/* Function blocks */

#define _SCC_IOS_ED1_63CFB45D	0X0001
#define _SCC_IOS_ED1_63CFB45A	0X0002
#define _SCC_IOS_ED1_63CFB457	0X0003
#define _SCC_IOS_ED1_63CFB454	0X0004
#define _SCC_IOS_ED1_63CFB451	0X0005

#define _SCC_IOS_ED1_63CFB459	0X0001
#define _SCC_IOS_ED1_63CFB456	0X0002
#define _SCC_IOS_ED1_63CFB453	0X0003
#define _SCC_IOS_ED1_63CFB450	0X0004


#define _SCC_IOS_ED1_63CFB464	0X0001
#define _SCC_IOS_ED1_63CFB465	0X0002
#define _SCC_IOS_ED1_63CFB466	0X0003
#define _SCC_IOS_ED1_63CFB461	0X0004
#define _SCC_IOS_ED1_63CFB462	0X0005
#define _SCC_IOS_ED1_63CFB463	0X0006
#define _SCC_IOS_ED1_63CFB45F	0X0007
#define _SCC_IOS_ED1_63CFB460	0X0008

#define _SCC_IOS_ED1_63CFB45E	0X0001
#define _SCC_IOS_ED1_63CFB44B	0X0002

#define _SCC_IOS_ED1_63CFB45C	0X0001

#define _SCC_IOS_ED1_63CFB45B	0X0001
#define _SCC_IOS_ED1_63CFB458	0X0002
#define _SCC_IOS_ED1_63CFB455	0X0003
#define _SCC_IOS_ED1_63CFB452	0X0004

#define _SCC_IOS_ED1_63CFB44F	0X0001
#define _SCC_IOS_ED1_63CFB44E	0X0002
#define _SCC_IOS_ED1_63CFB44C	0X0003
#define _SCC_IOS_ED1_63CFB44D	0X0004
