/**********************************************************************/
/*                                                                    */
/*  File name : REAL_INT.H                                            */
/*  Date      : 04.09.2011 12:22:54                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : redcmn                                     */
/*  ISaGRAF program name : REAL_INT                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */








