/**********************************************************************/
/*                                                                    */
/*  File name : SEM.H                                                 */
/*  Date      : 04.09.2011 12:22:52                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : redcmn                                     */
/*  ISaGRAF program name : SEM                                        */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_SEM_ED1_63CFE44B_BUSY_VA	0X0044
#define _SCC_SEM_ED1_63CFE44A_Q_VA	0X0048

/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */


#define _SCC_SEM_ED1_63CFE44A	0X0005

#define _SCC_SEM_ED1_63CFE44B	0X0001





