/**********************************************************************/
/*                                                                    */
/*  File name : SYNC.H                                                */
/*  Date      : 04.09.2011 12:22:53                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : redcmn                                     */
/*  ISaGRAF program name : SYNC                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_SYNC_DZ	0X002E
#define _SCC_SYNC_DOZVIL	0X002F
#define _SCC_SYNC_LINK	0X0030

/* Analogs */

#define _SCC_SYNC_OB	0X0029
#define _SCC_SYNC_ST_NEW	0X002A

/* Timers */


/* Functions */


/* Function blocks */








