/**********************************************************************/
/*                                                                    */
/*  File name : DEXPO.H                                               */
/*  Date      : 16.08.2016 18:14:42                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : apana                                      */
/*  ISaGRAF program name : DEXPO                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */

#define _SCC_DEXPO_DEXPO	0X0052
#define _SCC_DEXPO_EXP_	0X0053
#define _SCC_DEXPO_SP_	0X0054
#define _SCC_DEXPO_PV_	0X0055
#define _SCC_DEXPO_D_	0X0056
#define _SCC_DEXPO_TMPR2	0X0093
#define _SCC_DEXPO_TMPR4	0X0094
#define _SCC_DEXPO_TMPR11	0X00FE
#define _SCC_DEXPO_TMPR10	0X00FF
#define _SCC_DEXPO_TMPR9	0X0100
#define _SCC_DEXPO_TMPR8	0X0101
#define _SCC_DEXPO_TMPR7	0X0102
#define _SCC_DEXPO_TMPR6	0X0103
#define _SCC_DEXPO_TMPR5	0X0104

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












