/**********************************************************************/
/*                                                                    */
/*  File name : TO_A4_20.H                                            */
/*  Date      : 16.08.2016 18:14:43                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : apana                                      */
/*  ISaGRAF program name : TO_A4_20                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












