/**********************************************************************/
/*                                                                    */
/*  File name : CONTROL.H                                             */
/*  Date      : 06.08.2018 17:16:37                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : difuz                                      */
/*  ISaGRAF program name : CONTROL                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_CONTROL_TAM_09	0X0068

/* Analogs */

#define _SCC_CONTROL_TXT_09	0X0110
#define _SCC_CONTROL_V_00	0X0111
#define _SCC_CONTROL_TMPR2	0X014A
#define _SCC_CONTROL_TMPR5	0X014B
#define _SCC_CONTROL_ED1_68E4E717_XOUT__VA	0X01CC
#define _SCC_CONTROL_ED1_68E4E718_XOUT__VA	0X01CD
#define _SCC_CONTROL_ED1_V0001	0X01CE
#define _SCC_CONTROL_ED1_V0002	0X01CF
#define _SCC_CONTROL_ED1_V0003	0X01D0
#define _SCC_CONTROL_ED1_V0004	0X01D1
#define _SCC_CONTROL_ED1_V0005	0X01D2
#define _SCC_CONTROL_ED1_V0006	0X01D3
#define _SCC_CONTROL_ED1_V0007	0X01D4
#define _SCC_CONTROL_ED1_V0008	0X01D5
#define _SCC_CONTROL_ED1_V0009	0X01D6
#define _SCC_CONTROL_ED1_V000A	0X01D7
#define _SCC_CONTROL_ED1_V000B	0X01D8
#define _SCC_CONTROL_ED1_V000C	0X01D9
#define _SCC_CONTROL_ED1_68E4E716_XOUT__VA	0X01DC
#define _SCC_CONTROL_ED1_68E4E715_XOUT__VA	0X01DF
#define _SCC_CONTROL_ED1_68E4E713_XOUT__VA	0X01E3
#define _SCC_CONTROL_ED1_68E4E714_XOUT__VA	0X01E4
#define _SCC_CONTROL_ED1_68E4E712_XOUT__VA	0X01E7
#define _SCC_CONTROL_ED1_68E4E711_XOUT__VA	0X01E8
#define _SCC_CONTROL_ED1_68E4E70F_XOUT__VA	0X01ED
#define _SCC_CONTROL_ED1_68E4E710_XOUT__VA	0X01EE
#define _SCC_CONTROL_ED1_68E4E70E_XOUT__VA	0X01EF
#define _SCC_CONTROL_ED1_68E4E70D_XOUT__VA	0X01F1

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */













#define _SCC_CONTROL_ED1_68E4E717	0X0001
#define _SCC_CONTROL_ED1_68E4E718	0X0002
#define _SCC_CONTROL_ED1_68E4E716	0X0003
#define _SCC_CONTROL_ED1_68E4E715	0X0004
#define _SCC_CONTROL_ED1_68E4E713	0X0005
#define _SCC_CONTROL_ED1_68E4E714	0X0006
#define _SCC_CONTROL_ED1_68E4E712	0X0007
#define _SCC_CONTROL_ED1_68E4E711	0X0008
#define _SCC_CONTROL_ED1_68E4E70F	0X0009
#define _SCC_CONTROL_ED1_68E4E710	0X000A
#define _SCC_CONTROL_ED1_68E4E70E	0X000B
#define _SCC_CONTROL_ED1_68E4E70D	0X000C
