/**********************************************************************/
/*                                                                    */
/*  File name : MUX2.H                                                */
/*  Date      : 06.08.2018 17:16:37                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : difuz                                      */
/*  ISaGRAF program name : MUX2                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MUX2_SL	0X006B

/* Analogs */

#define _SCC_MUX2_MUX2	0X0116
#define _SCC_MUX2_IN2	0X0117
#define _SCC_MUX2_IN1	0X0118

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */













