/**********************************************************************/
/*                                                                    */
/*  File name : P_P0.H                                                */
/*  Date      : 06.08.2018 17:16:37                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : difuz                                      */
/*  ISaGRAF program name : P_P0                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_P_P0_AUTO_O	0X0067
#define _SCC_P_P0_MODE_	0X006C
#define _SCC_P_P0_AUTO_	0X006D

/* Analogs */

#define _SCC_P_P0_SP_O	0X010E
#define _SCC_P_P0_PV_O	0X010F
#define _SCC_P_P0_KP_O	0X0112
#define _SCC_P_P0_X0_O	0X0113
#define _SCC_P_P0_KP_	0X0119
#define _SCC_P_P0_X0_	0X011A
#define _SCC_P_P0_SP_	0X011B
#define _SCC_P_P0_PV_	0X011C
#define _SCC_P_P0_P0_	0X011D

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */













