/**********************************************************************/
/*                                                                    */
/*  File name : PARM_RAM.H                                            */
/*  Date      : 06.08.2018 17:16:37                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : difuz                                      */
/*  ISaGRAF program name : PARM_RAM                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARM_RAM_INIT	0X005B
#define _SCC_PARM_RAM_RES	0X005D

/* Analogs */

#define _SCC_PARM_RAM_II	0X00D6
#define _SCC_PARM_RAM_ADR	0X00D7

/* Timers */


/* Messages */

#define _SCC_PARM_RAM_TMPM1	0X0001
#define _SCC_PARM_RAM_TMPM2	0X0002
#define _SCC_PARM_RAM_TMPM3	0X0003

/* Functions */


/* Function blocks */













