/**********************************************************************/
/*                                                                    */
/*  File name : TX_X.H                                                */
/*  Date      : 06.08.2018 17:16:37                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : difuz                                      */
/*  ISaGRAF program name : TX_X                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_TX_X_TIMEBACKUP	0X0069
#define _SCC_TX_X_BRES	0X006A

/* Analogs */

#define _SCC_TX_X_LAST_01	0X00CC
#define _SCC_TX_X_LAST_02	0X00CE
#define _SCC_TX_X_RES	0X0114
#define _SCC_TX_X_IX	0X0115
#define _SCC_TX_X_TMPR3	0X0146

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */













