/**********************************************************************/
/*                                                                    */
/*  File name : WD_LONG.H                                             */
/*  Date      : 06.08.2018 17:16:37                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : difuz                                      */
/*  ISaGRAF program name : WD_LONG                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Messages */


/* Functions */


/* Function blocks */













