/**********************************************************************/
/*                                                                    */
/*  File name : CONTROL.H                                             */
/*  Date      : 22.02.2020 21:41:57                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : kotel2                                     */
/*  ISaGRAF program name : CONTROL                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */

#define _SCC_CONTROL_ED1_5210A805_XOUT__VA	0X004E
#define _SCC_CONTROL_ED1_5210A803_XOUT__VA	0X004F
#define _SCC_CONTROL_ED1_5210A804_XOUT__VA	0X0050
#define _SCC_CONTROL_ED1_5210A802_XOUT__VA	0X0051
#define _SCC_CONTROL_ED1_5210A801_XOUT__VA	0X0052

/* Timers */


/* Function blocks */



#define _SCC_CONTROL_ED1_5210A805	0X0001
#define _SCC_CONTROL_ED1_5210A804	0X0002
#define _SCC_CONTROL_ED1_5210A802	0X0003
#define _SCC_CONTROL_ED1_5210A803	0X0004
#define _SCC_CONTROL_ED1_5210A801	0X0005
