

drop schema if exists report;
create schema report;
use report;


CREATE TABLE `report` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `startTime` TIMESTAMP NULL DEFAULT '2000-01-01 00:00:00',
  `stopTime` TIMESTAMP NULL DEFAULT '2000-01-01 00:00:00',
  `SGstr` DOUBLE DEFAULT '0',
  `SVvoda` DOUBLE DEFAULT '0',
  `SVds` DOUBLE DEFAULT '0',
  `SVvm` DOUBLE DEFAULT '0',
  `SVsvp` DOUBLE DEFAULT '0',
  `SVsfv` DOUBLE DEFAULT '0',
  `SVkpk` DOUBLE DEFAULT '0',
  `SVvfd` DOUBLE DEFAULT '0',
  `SVvtv` DOUBLE DEFAULT '0',
  `SGutf` DOUBLE DEFAULT '0',
  `SGcl` DOUBLE DEFAULT '0',
  `SGst` DOUBLE DEFAULT '0',
  `GT1` DOUBLE DEFAULT '0.0',
  `GT2` DOUBLE DEFAULT '0.0',
  `GRou` DOUBLE DEFAULT '0.0',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `s` (`startTime`,`stopTime`);

CREATE TABLE `hhreport` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `startTime` TIMESTAMP NULL DEFAULT '00-01-01 00:00:00',
  `Nw` INT DEFAULT '0',
  `H01` DOUBLE DEFAULT '0',
  `H02` DOUBLE DEFAULT '0',
  `H03` DOUBLE DEFAULT '0',
  `H04` DOUBLE DEFAULT '0',
  `H05` DOUBLE DEFAULT '0',
  `H06` DOUBLE DEFAULT '0',
  `H07` DOUBLE DEFAULT '0',
  `H08` DOUBLE DEFAULT '0',
  `H09` DOUBLE DEFAULT '0',
  `H10` DOUBLE DEFAULT '0',
  `H11` DOUBLE DEFAULT '0',
  `H12` DOUBLE DEFAULT '0',
  `G01` DOUBLE DEFAULT '0',
  `G02` DOUBLE DEFAULT '0',
  `G03` DOUBLE DEFAULT '0',
  `G04` DOUBLE DEFAULT '0',
  `G05` DOUBLE DEFAULT '0',
  `G06` DOUBLE DEFAULT '0',
  `G07` DOUBLE DEFAULT '0',
  `G08` DOUBLE DEFAULT '0',
  `G09` DOUBLE DEFAULT '0',
  `G10` DOUBLE DEFAULT '0',
  `G11` DOUBLE DEFAULT '0',
  `G12` DOUBLE DEFAULT '0',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `s` (`Nw`) USING BTREE
) ;

CREATE TABLE `ereport` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `startTime` TIMESTAMP NULL DEFAULT '00-01-01 00:00:00',
  `Pow0001` DOUBLE DEFAULT '0.0',
  `Pow0002` DOUBLE DEFAULT '0.0',
  `Pow0003` DOUBLE DEFAULT '0.0',
  `Pow0004` DOUBLE DEFAULT '0.0',
  `Pow0005` DOUBLE DEFAULT '0.0',
  `Pow0006` DOUBLE DEFAULT '0.0',
  `Pow0007` DOUBLE DEFAULT '0.0',
  `Pow0008` DOUBLE DEFAULT '0.0',
  `Pow0009` DOUBLE DEFAULT '0.0',
  `Pow0010` DOUBLE DEFAULT '0.0',
  `Pow0011` DOUBLE DEFAULT '0.0',
  `Pow0012` DOUBLE DEFAULT '0.0',
  `Pow0013` DOUBLE DEFAULT '0.0',
  `Pow0014` DOUBLE DEFAULT '0.0',
  `Pow0015` DOUBLE DEFAULT '0.0',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `s` (`startTime`) USING BTREE
);



