/**********************************************************************/
/*                                                                    */
/*  File name : appli.H                                               */
/*  Date      : 10.10.2015 19:36:22                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : routest                                    */
/*                                                                    */
/**********************************************************************/

/* Global variables of the various programs */

/* Programs */

#define _SCC_TEST	0X0001

/* Booleans */

#define _SCC_START	0X0001
#define _SCC_REJ0003	0X0002
#define _SCC_AM0003	0X0003
#define _SCC_DUMMYCOIL	0X0004

/* Analogs */

#define _SCC_KK0003	0X0001
#define _SCC_V0024	0X0002
#define _SCC_K10003	0X0003
#define _SCC_SP2003	0X0004
#define _SCC_K	0X0005
#define _SCC_ISPR0003	0X0006
#define _SCC_SPR0003	0X0007
#define _SCC_SP0003	0X0008
#define _SCC_REAL_NULL	0X0009
#define _SCC_FBL_RET	0X000B
#define _SCC_TMPR1	0X000C

/* Timers */

#define _SCC_TTEST	0X0001
#define _SCC_CTMR000001F4	0X0002

/* Function blocks */

#define _SCC_STD_TP	0X000B

#define _SCC_STD_INTEGRAL	0X0014
