/**********************************************************************/
/*                                                                    */
/*  File name : TEST.H                                                */
/*  Date      : 10.10.2015 19:36:22                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : routest                                    */
/*  ISaGRAF program name : TEST                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_TEST_ED1_19CB26C0_Q_VA	0X0005

/* Analogs */

#define _SCC_TEST_TMPR2	0X000A
#define _SCC_TEST_ED1_19CB26C1_XOUT_VA	0X000D

/* Timers */


/* Function blocks */

#define _SCC_TEST_ED1_19CB26C0	0X0001

#define _SCC_TEST_ED1_19CB26C1	0X0001
