/**********************************************************************/
/*                                                                    */
/*  File name : ANALOG.H                                              */
/*  Date      : 03.12.2015 09:49:40                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : rou2                                       */
/*  ISaGRAF program name : ANALOG                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_ANALOG_ED1_6080B57B_Q__VA	0X0067
#define _SCC_ANALOG_ED1_6080B575_Q__VA	0X0068
#define _SCC_ANALOG_ED1_6080B577_Q__VA	0X0069
#define _SCC_ANALOG_ED1_6080B572_Q_VA	0X006A
#define _SCC_ANALOG_ED1_6080B573_Q_VA	0X006B
#define _SCC_ANALOG_ED1_6080B574_Q__VA	0X006C
#define _SCC_ANALOG_ED1_6080B58B_Q_VA	0X006D
#define _SCC_ANALOG_ED1_6080B58C_Q_VA	0X006E

/* Analogs */

#define _SCC_ANALOG_AI2_LO	0X00A1
#define _SCC_ANALOG_AI2_HI	0X00A2
#define _SCC_ANALOG_TMPR1	0X00D2
#define _SCC_ANALOG_ED1_6080B584_XOUT_VA	0X00DE
#define _SCC_ANALOG_ED1_6080B585_XOUT_VA	0X00DF
#define _SCC_ANALOG_ED1_6080B586_XOUT_VA	0X00E0
#define _SCC_ANALOG_ED1_6080B581_XOUT_VA	0X00E1
#define _SCC_ANALOG_ED1_6080B582_XOUT_VA	0X00E2
#define _SCC_ANALOG_ED1_6080B583_XOUT_VA	0X00E3
#define _SCC_ANALOG_ED1_6080B57E_XOUT_VA	0X00E4
#define _SCC_ANALOG_ED1_6080B57F_XOUT_VA	0X00E5
#define _SCC_ANALOG_ED1_6080B580_XOUT_VA	0X00E6
#define _SCC_ANALOG_ED1_6080B57A_MM__VA	0X00E7
#define _SCC_ANALOG_ED1_6080B57A_YY__VA	0X00E8
#define _SCC_ANALOG_ED1_6080B57C_XOUT_VA	0X00E9
#define _SCC_ANALOG_ED1_6080B57D_XOUT_VA	0X00EA
#define _SCC_ANALOG_ED1_6080B579_SS__VA	0X00EB
#define _SCC_ANALOG_ED1_6080B579_MM__VA	0X00EC
#define _SCC_ANALOG_ED1_6080B579_HH__VA	0X00ED
#define _SCC_ANALOG_ED1_6080B57A_DD__VA	0X00EE
#define _SCC_ANALOG_ED1_6080B575_NI1__VA	0X00EF
#define _SCC_ANALOG_ED1_6080B576_F2__VA	0X00F0
#define _SCC_ANALOG_ED1_6080B576_F1__VA	0X00F1
#define _SCC_ANALOG_ED1_6080B575_NI2__VA	0X00F2
#define _SCC_ANALOG_ED1_6080B58A_XOUT_VA	0X0107
#define _SCC_ANALOG_ED1_6080B58D_XOUT_VA	0X0108
#define _SCC_ANALOG_ED1_6080B587_XOUT_VA	0X0109
#define _SCC_ANALOG_ED1_6080B588_XOUT_VA	0X010A
#define _SCC_ANALOG_ED1_6080B589_XOUT_VA	0X010B

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */


#define _SCC_ANALOG_ED1_6080B58B	0X0001

#define _SCC_ANALOG_ED1_6080B572	0X0001

#define _SCC_ANALOG_ED1_6080B573	0X0001

#define _SCC_ANALOG_ED1_6080B584	0X0001
#define _SCC_ANALOG_ED1_6080B585	0X0002
#define _SCC_ANALOG_ED1_6080B586	0X0003
#define _SCC_ANALOG_ED1_6080B581	0X0004
#define _SCC_ANALOG_ED1_6080B582	0X0005
#define _SCC_ANALOG_ED1_6080B583	0X0006
#define _SCC_ANALOG_ED1_6080B57E	0X0007
#define _SCC_ANALOG_ED1_6080B57F	0X0008
#define _SCC_ANALOG_ED1_6080B580	0X0009
#define _SCC_ANALOG_ED1_6080B57C	0X000A
#define _SCC_ANALOG_ED1_6080B57D	0X000B
#define _SCC_ANALOG_ED1_6080B58D	0X000C
#define _SCC_ANALOG_ED1_6080B587	0X000D
#define _SCC_ANALOG_ED1_6080B588	0X000E
#define _SCC_ANALOG_ED1_6080B589	0X000F
#define _SCC_ANALOG_ED1_6080B58A	0X0010

#define _SCC_ANALOG_ED1_6080B58C	0X0001


#define _SCC_ANALOG_ED1_6080B57B	0X0001

#define _SCC_ANALOG_ED1_6080B578	0X0001

#define _SCC_ANALOG_ED1_6080B579	0X0001

#define _SCC_ANALOG_ED1_6080B57A	0X0001

#define _SCC_ANALOG_ED1_6080B576	0X0001

#define _SCC_ANALOG_ED1_6080B577	0X0001

#define _SCC_ANALOG_ED1_6080B575	0X0001

#define _SCC_ANALOG_ED1_6080B574	0X0001

