/**********************************************************************/
/*                                                                    */
/*  File name : FLIMIT.H                                              */
/*  Date      : 03.12.2015 09:49:40                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : rou2                                       */
/*  ISaGRAF program name : FLIMIT                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FLIMIT_TMPB1	0X0085

/* Analogs */

#define _SCC_FLIMIT_IN_	0X00A9
#define _SCC_FLIMIT_MAX_	0X00AA
#define _SCC_FLIMIT_OUT	0X00AB
#define _SCC_FLIMIT_FLIMIT	0X00AC
#define _SCC_FLIMIT_MIN_	0X00AD

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */
















