/**********************************************************************/
/*                                                                    */
/*  File name : MUX2.H                                                */
/*  Date      : 03.12.2015 09:49:40                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : rou2                                       */
/*  ISaGRAF program name : MUX2                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MUX2_SL	0X0053

/* Analogs */

#define _SCC_MUX2_IN2	0X00A6
#define _SCC_MUX2_IN1	0X00A7
#define _SCC_MUX2_MUX2	0X00A8

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */
















