/**********************************************************************/
/*                                                                    */
/*  File name : P_P0.H                                                */
/*  Date      : 03.12.2015 09:49:40                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : rou2                                       */
/*  ISaGRAF program name : P_P0                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_P_P0_AUTO_O	0X0054
#define _SCC_P_P0_MODE_	0X0055
#define _SCC_P_P0_AUTO_	0X0056

/* Analogs */

#define _SCC_P_P0_KP_O	0X00AE
#define _SCC_P_P0_X0_O	0X00AF
#define _SCC_P_P0_SP_O	0X00B0
#define _SCC_P_P0_PV_O	0X00B1
#define _SCC_P_P0_KP_	0X00B2
#define _SCC_P_P0_X0_	0X00B3
#define _SCC_P_P0_SP_	0X00B4
#define _SCC_P_P0_PV_	0X00B5
#define _SCC_P_P0_P0_	0X00B6

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */
















