/**********************************************************************/
/*                                                                    */
/*  File name : PARM_RAM.H                                            */
/*  Date      : 03.12.2015 09:49:40                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : rou2                                       */
/*  ISaGRAF program name : PARM_RAM                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARM_RAM_INIT	0X0032
#define _SCC_PARM_RAM_RES	0X0052

/* Analogs */

#define _SCC_PARM_RAM_II	0X009E
#define _SCC_PARM_RAM_ADR	0X009F

/* Timers */


/* Messages */

#define _SCC_PARM_RAM_TMPM1	0X0001
#define _SCC_PARM_RAM_TMPM2	0X0002
#define _SCC_PARM_RAM_TMPM3	0X0003

/* Functions */


/* Function blocks */
















