/**********************************************************************/
/*                                                                    */
/*  File name : TX_X.H                                                */
/*  Date      : 03.12.2015 09:49:40                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : rou2                                       */
/*  ISaGRAF program name : TX_X                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */

#define _SCC_TX_X_TMPR1	0X00CE
#define _SCC_TX_X_TMPR2	0X00CF
#define _SCC_TX_X_TMPR5	0X00D0
#define _SCC_TX_X_TMPR6	0X00D1
#define _SCC_TX_X_TMPR7	0X00D3
#define _SCC_TX_X_TMPR9	0X00D4

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */
















