/**********************************************************************/
/*                                                                    */
/*  File name : WD_LONG.H                                             */
/*  Date      : 03.12.2015 09:49:40                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : rou2                                       */
/*  ISaGRAF program name : WD_LONG                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Messages */


/* Functions */


/* Function blocks */
















