/**********************************************************************/
/*                                                                    */
/*  File name : DISPATCH.H                                            */
/*  Date      : 15.10.2014 12:12:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ifpn                                       */
/*  ISaGRAF program name : DISPATCH                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_DISPATCH_ED1_3DE35150_Q_VA	0X00AC

/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */


#define _SCC_DISPATCH_ED1_3DE35150	0X001F











