/**********************************************************************/
/*                                                                    */
/*  File name : DRIVER.H                                              */
/*  Date      : 15.10.2014 12:12:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ifpn                                       */
/*  ISaGRAF program name : DRIVER                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_DRIVER_I_LOW	0X0064

/* Analogs */

#define _SCC_DRIVER_TMPR3	0X00CE

/* Timers */


/* Functions */


/* Function blocks */













