/**********************************************************************/
/*                                                                    */
/*  File name : MAIN.H                                                */
/*  Date      : 15.10.2014 12:12:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ifpn                                       */
/*  ISaGRAF program name : MAIN                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MAIN_RE_ETEST	0X005D
#define _SCC_MAIN_RE_FOTT	0X005E
#define _SCC_MAIN_RE_X_STOP	0X005F
#define _SCC_MAIN_RE_TS_LOT	0X0060
#define _SCC_MAIN_RE_X6B	0X0061
#define _SCC_MAIN_FE_X4B	0X0062
#define _SCC_MAIN_RE_X4B	0X0063

/* Analogs */

#define _SCC_MAIN_H0_1	0X0071
#define _SCC_MAIN_GZAG_TMP	0X0072
#define _SCC_MAIN_T_P_S	0X0073
#define _SCC_MAIN_K_V	0X0074
#define _SCC_MAIN_Q_M_M	0X0075
#define _SCC_MAIN_HB_1	0X0076
#define _SCC_MAIN_TMPR1	0X00C2
#define _SCC_MAIN_TMPR10	0X00C3
#define _SCC_MAIN_TMPR4	0X00C5
#define _SCC_MAIN_TMPR7	0X00C6
#define _SCC_MAIN_TMPR8	0X00C9
#define _SCC_MAIN_TMPR9	0X00CB

/* Timers */


/* Functions */


/* Function blocks */













