/**********************************************************************/
/*                                                                    */
/*  File name : PARM_STO.H                                            */
/*  Date      : 15.10.2014 12:12:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ifpn                                       */
/*  ISaGRAF program name : PARM_STO                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARM_STO_RES	0X0059
#define _SCC_PARM_STO_READ	0X005A

/* Analogs */

#define _SCC_PARM_STO_STATUS_OLD	0X0066
#define _SCC_PARM_STO_SAV_ST	0X0067

/* Timers */


/* Functions */


/* Function blocks */













