/**********************************************************************/
/*                                                                    */
/*  File name : REAL_INT.H                                            */
/*  Date      : 15.10.2014 12:12:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ifpn                                       */
/*  ISaGRAF program name : REAL_INT                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */













