/**********************************************************************/
/*                                                                    */
/*  File name : TIMERS.H                                              */
/*  Date      : 15.10.2014 12:12:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ifpn                                       */
/*  ISaGRAF program name : TIMERS                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_TIMERS_ED1_3DE34E99_Q_VA	0X0089
#define _SCC_TIMERS_ED1_3DE34E9A_Q_VA	0X008A
#define _SCC_TIMERS_ED1_3DE34E9B_Q_VA	0X008B
#define _SCC_TIMERS_ED1_3DE34E96_Q_VA	0X008C
#define _SCC_TIMERS_ED1_3DE34E97_Q_VA	0X008D
#define _SCC_TIMERS_ED1_3DE34E98_Q_VA	0X008E
#define _SCC_TIMERS_ED1_3DE34E94_Q_VA	0X008F
#define _SCC_TIMERS_ED1_3DE34E95_Q_VA	0X0090
#define _SCC_TIMERS_ED1_3DE34EB0_Q_VA	0X0091
#define _SCC_TIMERS_ED1_3DE34EAC_Q_VA	0X0092
#define _SCC_TIMERS_ED1_3DE34EAD_Q_VA	0X0093
#define _SCC_TIMERS_ED1_3DE34EAE_Q_VA	0X0094
#define _SCC_TIMERS_ED1_3DE34EAF_Q_VA	0X0095
#define _SCC_TIMERS_ED1_3DE34EA9_Q_VA	0X0096
#define _SCC_TIMERS_ED1_3DE34EAA_Q_VA	0X0097
#define _SCC_TIMERS_ED1_3DE34EA6_Q_VA	0X0098
#define _SCC_TIMERS_ED1_3DE34EA7_Q_VA	0X0099
#define _SCC_TIMERS_ED1_3DE34EA8_Q_VA	0X009A
#define _SCC_TIMERS_ED1_3DE34EA3_Q_VA	0X009B
#define _SCC_TIMERS_ED1_3DE34EA4_Q_VA	0X009C
#define _SCC_TIMERS_ED1_3DE34EA5_Q_VA	0X009D
#define _SCC_TIMERS_ED1_3DE34EA0_Q_VA	0X009E
#define _SCC_TIMERS_ED1_3DE34EA1_Q_VA	0X009F
#define _SCC_TIMERS_ED1_3DE34EA2_Q_VA	0X00A0
#define _SCC_TIMERS_ED1_3DE34E9C_Q_VA	0X00A1
#define _SCC_TIMERS_ED1_3DE34E9D_Q_VA	0X00A2
#define _SCC_TIMERS_ED1_3DE34E9E_Q_VA	0X00A3
#define _SCC_TIMERS_ED1_3DE34E9F_Q_VA	0X00A4

/* Analogs */

#define _SCC_TIMERS_TMPR2	0X00D3

/* Timers */

#define _SCC_TIMERS_ED1_3DE34EB0_ET_VA	0X001B
#define _SCC_TIMERS_ED1_3DE34EAE_ET_VA	0X001C
#define _SCC_TIMERS_ED1_3DE34EAF_ET_VA	0X001D
#define _SCC_TIMERS_ED1_3DE34EA9_ET_VA	0X001E
#define _SCC_TIMERS_ED1_3DE34EAA_ET_VA	0X001F
#define _SCC_TIMERS_ED1_3DE34EAB_ET_VA	0X0020
#define _SCC_TIMERS_ED1_3DE34EA8_ET_VA	0X0021

/* Functions */


/* Function blocks */


#define _SCC_TIMERS_ED1_3DE34E9A	0X0003
#define _SCC_TIMERS_ED1_3DE34E9B	0X0004
#define _SCC_TIMERS_ED1_3DE34E9C	0X0005
#define _SCC_TIMERS_ED1_3DE34E96	0X0006
#define _SCC_TIMERS_ED1_3DE34E97	0X0007
#define _SCC_TIMERS_ED1_3DE34E98	0X0008
#define _SCC_TIMERS_ED1_3DE34E99	0X0009
#define _SCC_TIMERS_ED1_3DE34E94	0X000A
#define _SCC_TIMERS_ED1_3DE34E95	0X000B
#define _SCC_TIMERS_ED1_3DE34EB0	0X000C
#define _SCC_TIMERS_ED1_3DE34EAD	0X000D
#define _SCC_TIMERS_ED1_3DE34EAE	0X000E
#define _SCC_TIMERS_ED1_3DE34EAF	0X000F
#define _SCC_TIMERS_ED1_3DE34EAA	0X0010
#define _SCC_TIMERS_ED1_3DE34EAB	0X0011
#define _SCC_TIMERS_ED1_3DE34EAC	0X0012
#define _SCC_TIMERS_ED1_3DE34EA6	0X0013
#define _SCC_TIMERS_ED1_3DE34EA7	0X0014
#define _SCC_TIMERS_ED1_3DE34EA8	0X0015
#define _SCC_TIMERS_ED1_3DE34EA9	0X0016
#define _SCC_TIMERS_ED1_3DE34EA3	0X0017
#define _SCC_TIMERS_ED1_3DE34EA4	0X0018
#define _SCC_TIMERS_ED1_3DE34EA5	0X0019
#define _SCC_TIMERS_ED1_3DE34EA0	0X001A
#define _SCC_TIMERS_ED1_3DE34EA1	0X001B
#define _SCC_TIMERS_ED1_3DE34EA2	0X001C
#define _SCC_TIMERS_ED1_3DE34E9E	0X001D
#define _SCC_TIMERS_ED1_3DE34E9F	0X001E

#define _SCC_TIMERS_ED1_3DE34E9D	0X0003










