/**********************************************************************/
/*                                                                    */
/*  File name : V0_10_TO.H                                            */
/*  Date      : 15.10.2014 12:12:29                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : ifpn                                       */
/*  ISaGRAF program name : V0_10_TO                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */













