/**********************************************************************/
/*                                                                    */
/*  File name : appli.H                                               */
/*  Date      : 12.09.2016 22:54:34                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : voda                                       */
/*                                                                    */
/**********************************************************************/

/* Global variables of the various programs */

/* Programs */

#define _SCC_INIT	0X0001
#define _SCC_TAST	0X0002
#define _SCC_PARA	0X0003

/* Booleans */

#define _SCC_CBOO00000000	0X0002
#define _SCC_DUMMYCOIL	0X0003

/* Analogs */

#define _SCC_P2004	0X0001
#define _SCC_P2013	0X0002
#define _SCC_P2005	0X0003
#define _SCC_P2014	0X0004
#define _SCC_P2006	0X0005
#define _SCC_P2015	0X0006
#define _SCC_P1500	0X0007
#define _SCC_P2007	0X0008
#define _SCC_P1501	0X0009
#define _SCC_P2008	0X000A
#define _SCC_P1510	0X000B
#define _SCC_P1502	0X000C
#define _SCC_P2009	0X000D
#define _SCC_P2500	0X000E
#define _SCC_P1511	0X000F
#define _SCC_P1503	0X0010
#define _SCC_P	0X0011
#define _SCC_P2501	0X0012
#define _SCC_P1512	0X0013
#define _SCC_P2510	0X0014
#define _SCC_P1504	0X0015
#define _SCC_P2502	0X0016
#define _SCC_P1513	0X0017
#define _SCC_P2511	0X0018
#define _SCC_P1505	0X0019
#define _SCC_P2503	0X001A
#define _SCC_P1514	0X001B
#define _SCC_P2512	0X001C
#define _SCC_P1506	0X001D
#define _SCC_P2504	0X001E
#define _SCC_P1515	0X001F
#define _SCC_P2513	0X0020
#define _SCC_P1507	0X0021
#define _SCC_P2505	0X0022
#define _SCC_P2514	0X0023
#define _SCC_P1508	0X0024
#define _SCC_P2506	0X0025
#define _SCC_P2515	0X0026
#define _SCC_P1509	0X0027
#define _SCC_P2507	0X0028
#define _SCC_P2508	0X0029
#define _SCC_P2509	0X002A
#define _SCC_T	0X002B
#define _SCC_P0000	0X002C
#define _SCC_P2000	0X002D
#define _SCC_P2001	0X002E
#define _SCC_P2010	0X002F
#define _SCC_P2002	0X0030
#define _SCC_P2011	0X0031
#define _SCC_P2003	0X0032
#define _SCC_P2012	0X0033
#define _SCC_RES	0X0034
#define _SCC_CANA00000020	0X0042
#define _SCC_CANA00000800	0X0043
#define _SCC_CANA00000820	0X0044
#define _SCC_CANA0000001C	0X0045
#define _SCC_CANA0000000A	0X0046
#define _SCC_CANA00000002	0X0047
#define _SCC_CANA00000000	0X0048
#define _SCC_FBL_RET	0X0082
#define _SCC_TMPR1	0X0083

/* Functions */

#define _SCC_R_MB_REL	0X0001
