/**********************************************************************/
/*                                                                    */
/*  File name : INIT.H                                                */
/*  Date      : 12.09.2016 22:54:34                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : voda                                       */
/*  ISaGRAF program name : INIT                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_INIT_INIT_	0X0001

/* Analogs */

#define _SCC_INIT_TMPR1	0X0049
#define _SCC_INIT_TMPR2	0X004A
#define _SCC_INIT_TMPR3	0X004C
#define _SCC_INIT_TMPR10	0X004D
#define _SCC_INIT_TMPR4	0X004E
#define _SCC_INIT_TMPR11	0X0050
#define _SCC_INIT_TMPR20	0X0051
#define _SCC_INIT_TMPR12	0X0053
#define _SCC_INIT_TMPR5	0X0054
#define _SCC_INIT_TMPR21	0X0056
#define _SCC_INIT_TMPR13	0X0057
#define _SCC_INIT_TMPR30	0X0058
#define _SCC_INIT_TMPR22	0X0059
#define _SCC_INIT_TMPR6	0X005A
#define _SCC_INIT_TMPR14	0X005B
#define _SCC_INIT_TMPR31	0X005D
#define _SCC_INIT_TMPR23	0X005E
#define _SCC_INIT_TMPR40	0X005F
#define _SCC_INIT_TMPR15	0X0060
#define _SCC_INIT_TMPR32	0X0061
#define _SCC_INIT_TMPR7	0X0062
#define _SCC_INIT_TMPR24	0X0063
#define _SCC_INIT_TMPR41	0X0065
#define _SCC_INIT_TMPR16	0X0066
#define _SCC_INIT_TMPR33	0X0067
#define _SCC_INIT_TMPR25	0X0068
#define _SCC_INIT_TMPR42	0X0069
#define _SCC_INIT_TMPR17	0X006A
#define _SCC_INIT_TMPR8	0X006B
#define _SCC_INIT_TMPR34	0X006C
#define _SCC_INIT_TMPR26	0X006E
#define _SCC_INIT_TMPR43	0X006F
#define _SCC_INIT_TMPR18	0X0070
#define _SCC_INIT_TMPR35	0X0071
#define _SCC_INIT_TMPR27	0X0072
#define _SCC_INIT_TMPR9	0X0073
#define _SCC_INIT_TMPR44	0X0074
#define _SCC_INIT_TMPR19	0X0075
#define _SCC_INIT_TMPR36	0X0077
#define _SCC_INIT_TMPR28	0X0078
#define _SCC_INIT_TMPR45	0X0079
#define _SCC_INIT_TMPR37	0X007A
#define _SCC_INIT_TMPR29	0X007B
#define _SCC_INIT_TMPR46	0X007D
#define _SCC_INIT_TMPR38	0X007E
#define _SCC_INIT_TMPR47	0X007F
#define _SCC_INIT_TMPR39	0X0080
#define _SCC_INIT_TMPR48	0X0081

/* Functions */

