/**********************************************************************/
/*                                                                    */
/*  File name : PARA.H                                                */
/*  Date      : 12.09.2016 22:54:34                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : voda                                       */
/*  ISaGRAF program name : PARA                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARA_TMPB1	0X0004

/* Analogs */

#define _SCC_PARA_PARA	0X0035
#define _SCC_PARA_TERM	0X0036
#define _SCC_PARA_PRESH	0X0037
#define _SCC_PARA_R1	0X0038
#define _SCC_PARA_R0	0X0039
#define _SCC_PARA_T_	0X003A
#define _SCC_PARA_P_	0X003B
#define _SCC_PARA_IY	0X003C
#define _SCC_PARA_IX	0X003D
#define _SCC_PARA_MAX1	0X003E
#define _SCC_PARA_MAX0	0X003F
#define _SCC_PARA_MIN1	0X0040
#define _SCC_PARA_MIN0	0X0041
#define _SCC_PARA_TMPR1	0X004B
#define _SCC_PARA_TMPR3	0X004F
#define _SCC_PARA_TMPR12	0X0052
#define _SCC_PARA_TMPR4	0X0055
#define _SCC_PARA_TMPR5	0X005C
#define _SCC_PARA_TMPR6	0X0064
#define _SCC_PARA_TMPR7	0X006D
#define _SCC_PARA_TMPR8	0X0076
#define _SCC_PARA_TMPR9	0X007C
#define _SCC_PARA_TMPI4	0X0084
#define _SCC_PARA_TMPR2	0X0085
#define _SCC_PARA_TMPR11	0X0086
#define _SCC_PARA_TMPR10	0X0087

/* Functions */

