/**********************************************************************/
/*                                                                    */
/*  File name : R_MB_REL.H                                            */
/*  Date      : 12.09.2016 22:54:34                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : voda                                       */
/*  ISaGRAF program name : R_MB_REL                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Functions */

