/**********************************************************************/
/*                                                                    */
/*  File name : FD_04.H                                               */
/*  Date      : 11.09.2019 12:06:14                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fqdmon                                     */
/*  ISaGRAF program name : FD_04                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_04_MQ_03	0X000B
#define _SCC_FD_04_MQ_01	0X004E
#define _SCC_FD_04_ED1_7942C78F_Q_VA	0X0069
#define _SCC_FD_04_ED1_7942C78E_Q_VA	0X006A
#define _SCC_FD_04_ED1_7942C78D_B3__VA	0X006B
#define _SCC_FD_04_ED1_7942C78D_B1__VA	0X006C

/* Analogs */

#define _SCC_FD_04_W_14	0X008E
#define _SCC_FD_04_W_13	0X008F
#define _SCC_FD_04_W_12	0X0090
#define _SCC_FD_04_W_11	0X0091
#define _SCC_FD_04_W_10	0X0092
#define _SCC_FD_04_W_09	0X0093
#define _SCC_FD_04_W_08	0X0094
#define _SCC_FD_04_W_07	0X0095
#define _SCC_FD_04_W_06	0X0096
#define _SCC_FD_04_W_05	0X0097
#define _SCC_FD_04_W_04	0X0098
#define _SCC_FD_04_W_03	0X0099
#define _SCC_FD_04_W_02	0X009A
#define _SCC_FD_04_W_01	0X009B
#define _SCC_FD_04_W_16	0X009C
#define _SCC_FD_04_W_15	0X009D
#define _SCC_FD_04_TMPR1	0X010E
#define _SCC_FD_04_TMPR5	0X0118
#define _SCC_FD_04_TMPR7	0X011F
#define _SCC_FD_04_ED1_7942C78F_N3__VA	0X0160
#define _SCC_FD_04_ED1_7942C78F_N2__VA	0X0161
#define _SCC_FD_04_ED1_7942C78F_N1__VA	0X0162
#define _SCC_FD_04_ED1_7942C78E_N7__VA	0X0163
#define _SCC_FD_04_ED1_7942C78E_N6__VA	0X0164
#define _SCC_FD_04_ED1_7942C78E_N5__VA	0X0165
#define _SCC_FD_04_ED1_7942C78E_N4__VA	0X0166
#define _SCC_FD_04_ED1_7942C78E_N3__VA	0X0167
#define _SCC_FD_04_ED1_7942C78E_N2__VA	0X0168
#define _SCC_FD_04_ED1_7942C78E_N1__VA	0X0169
#define _SCC_FD_04_ED1_7942C78F_N8__VA	0X016A
#define _SCC_FD_04_ED1_7942C78F_N7__VA	0X016B
#define _SCC_FD_04_ED1_7942C78F_N6__VA	0X016C
#define _SCC_FD_04_ED1_7942C78F_N5__VA	0X016D
#define _SCC_FD_04_ED1_7942C78F_N4__VA	0X016E
#define _SCC_FD_04_ED1_7942C78E_N8__VA	0X016F

/* Functions */


/* Function blocks */


#define _SCC_FD_04_ED1_7942C78D	0X0004

#define _SCC_FD_04_ED1_7942C78F	0X0001
#define _SCC_FD_04_ED1_7942C78E	0X0002


