/**********************************************************************/
/*                                                                    */
/*  File name : FD_06.H                                               */
/*  Date      : 11.09.2019 12:06:14                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fqdmon                                     */
/*  ISaGRAF program name : FD_06                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_06_MQ_03	0X0009
#define _SCC_FD_06_MQ_01	0X0050
#define _SCC_FD_06_ED1_7942C891_Q_VA	0X0071
#define _SCC_FD_06_ED1_7942C890_Q_VA	0X0072
#define _SCC_FD_06_ED1_7942C88F_B3__VA	0X0073
#define _SCC_FD_06_ED1_7942C88F_B1__VA	0X0074

/* Analogs */

#define _SCC_FD_06_W_14	0X00AE
#define _SCC_FD_06_W_13	0X00AF
#define _SCC_FD_06_W_12	0X00B0
#define _SCC_FD_06_W_11	0X00B1
#define _SCC_FD_06_W_10	0X00B2
#define _SCC_FD_06_W_09	0X00B3
#define _SCC_FD_06_W_08	0X00B4
#define _SCC_FD_06_W_07	0X00B5
#define _SCC_FD_06_W_06	0X00B6
#define _SCC_FD_06_W_05	0X00B7
#define _SCC_FD_06_W_04	0X00B8
#define _SCC_FD_06_W_03	0X00B9
#define _SCC_FD_06_W_02	0X00BA
#define _SCC_FD_06_W_01	0X00BB
#define _SCC_FD_06_W_16	0X00BC
#define _SCC_FD_06_W_15	0X00BD
#define _SCC_FD_06_TMPR1	0X010C
#define _SCC_FD_06_TMPR5	0X0116
#define _SCC_FD_06_TMPR7	0X011D
#define _SCC_FD_06_ED1_7942C891_N3__VA	0X0180
#define _SCC_FD_06_ED1_7942C891_N2__VA	0X0181
#define _SCC_FD_06_ED1_7942C891_N1__VA	0X0182
#define _SCC_FD_06_ED1_7942C890_N7__VA	0X0183
#define _SCC_FD_06_ED1_7942C890_N6__VA	0X0184
#define _SCC_FD_06_ED1_7942C890_N5__VA	0X0185
#define _SCC_FD_06_ED1_7942C890_N4__VA	0X0186
#define _SCC_FD_06_ED1_7942C890_N3__VA	0X0187
#define _SCC_FD_06_ED1_7942C890_N2__VA	0X0188
#define _SCC_FD_06_ED1_7942C890_N1__VA	0X0189
#define _SCC_FD_06_ED1_7942C891_N8__VA	0X018A
#define _SCC_FD_06_ED1_7942C891_N7__VA	0X018B
#define _SCC_FD_06_ED1_7942C891_N6__VA	0X018C
#define _SCC_FD_06_ED1_7942C891_N5__VA	0X018D
#define _SCC_FD_06_ED1_7942C891_N4__VA	0X018E
#define _SCC_FD_06_ED1_7942C890_N8__VA	0X018F

/* Functions */


/* Function blocks */


#define _SCC_FD_06_ED1_7942C88F	0X0006

#define _SCC_FD_06_ED1_7942C891	0X0005
#define _SCC_FD_06_ED1_7942C890	0X0006


