/**********************************************************************/
/*                                                                    */
/*  File name : FD_02.H                                               */
/*  Date      : 11.09.2019 12:06:14                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fqdmon                                     */
/*  ISaGRAF program name : FD_02                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_02_MQ_01	0X004A
#define _SCC_FD_02_MQ_03	0X004B
#define _SCC_FD_02_ED1_7942C78D_Q_VA	0X0061
#define _SCC_FD_02_ED1_7942C78C_Q_VA	0X0062
#define _SCC_FD_02_ED1_7942C78B_B6__VA	0X0063
#define _SCC_FD_02_ED1_7942C78B_B5__VA	0X0064

/* Analogs */

#define _SCC_FD_02_W_12	0X0066
#define _SCC_FD_02_W_11	0X0067
#define _SCC_FD_02_W_10	0X0068
#define _SCC_FD_02_W_09	0X0069
#define _SCC_FD_02_W_08	0X006A
#define _SCC_FD_02_W_07	0X006B
#define _SCC_FD_02_W_06	0X006C
#define _SCC_FD_02_W_05	0X006D
#define _SCC_FD_02_W_04	0X006E
#define _SCC_FD_02_W_03	0X006F
#define _SCC_FD_02_W_02	0X0070
#define _SCC_FD_02_W_01	0X0071
#define _SCC_FD_02_W_24	0X0072
#define _SCC_FD_02_W_23	0X0073
#define _SCC_FD_02_W_22	0X0074
#define _SCC_FD_02_W_21	0X0075
#define _SCC_FD_02_W_20	0X0076
#define _SCC_FD_02_W_19	0X0077
#define _SCC_FD_02_W_18	0X0078
#define _SCC_FD_02_W_17	0X0079
#define _SCC_FD_02_TMPR1	0X0110
#define _SCC_FD_02_TMPR5	0X011A
#define _SCC_FD_02_ED1_7942C78D_N1__VA	0X0138
#define _SCC_FD_02_ED1_7942C78D_N8__VA	0X0139
#define _SCC_FD_02_ED1_7942C78D_N7__VA	0X013A
#define _SCC_FD_02_ED1_7942C78D_N6__VA	0X013B
#define _SCC_FD_02_ED1_7942C78D_N5__VA	0X013C
#define _SCC_FD_02_ED1_7942C78D_N4__VA	0X013D
#define _SCC_FD_02_ED1_7942C78D_N3__VA	0X013E
#define _SCC_FD_02_ED1_7942C78D_N2__VA	0X013F
#define _SCC_FD_02_ED1_7942C78C_N12__VA	0X0140
#define _SCC_FD_02_ED1_7942C78C_N11__VA	0X0141
#define _SCC_FD_02_ED1_7942C78C_N10__VA	0X0142
#define _SCC_FD_02_ED1_7942C78C_N9__VA	0X0143
#define _SCC_FD_02_ED1_7942C78C_N8__VA	0X0144
#define _SCC_FD_02_ED1_7942C78C_N7__VA	0X0145
#define _SCC_FD_02_ED1_7942C78C_N6__VA	0X0146
#define _SCC_FD_02_ED1_7942C78C_N5__VA	0X0147
#define _SCC_FD_02_ED1_7942C78C_N4__VA	0X0148
#define _SCC_FD_02_ED1_7942C78C_N3__VA	0X0149
#define _SCC_FD_02_ED1_7942C78C_N2__VA	0X014A
#define _SCC_FD_02_ED1_7942C78C_N1__VA	0X014B

/* Functions */


/* Function blocks */

#define _SCC_FD_02_ED1_7942C78D	0X0003
#define _SCC_FD_02_ED1_7942C78C	0X0004

#define _SCC_FD_02_ED1_7942C78B	0X0002



