/**********************************************************************/
/*                                                                    */
/*  File name : FD_05.H                                               */
/*  Date      : 11.09.2019 12:06:14                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fqdmon                                     */
/*  ISaGRAF program name : FD_05                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_05_MQ_03	0X000A
#define _SCC_FD_05_MQ_01	0X004F
#define _SCC_FD_05_ED1_7942C890_Q_VA	0X006D
#define _SCC_FD_05_ED1_7942C88F_Q_VA	0X006E
#define _SCC_FD_05_ED1_7942C88E_B3__VA	0X006F
#define _SCC_FD_05_ED1_7942C88E_B1__VA	0X0070

/* Analogs */

#define _SCC_FD_05_W_14	0X009E
#define _SCC_FD_05_W_13	0X009F
#define _SCC_FD_05_W_12	0X00A0
#define _SCC_FD_05_W_11	0X00A1
#define _SCC_FD_05_W_10	0X00A2
#define _SCC_FD_05_W_09	0X00A3
#define _SCC_FD_05_W_08	0X00A4
#define _SCC_FD_05_W_07	0X00A5
#define _SCC_FD_05_W_06	0X00A6
#define _SCC_FD_05_W_05	0X00A7
#define _SCC_FD_05_W_04	0X00A8
#define _SCC_FD_05_W_03	0X00A9
#define _SCC_FD_05_W_02	0X00AA
#define _SCC_FD_05_W_01	0X00AB
#define _SCC_FD_05_W_16	0X00AC
#define _SCC_FD_05_W_15	0X00AD
#define _SCC_FD_05_TMPR1	0X010D
#define _SCC_FD_05_TMPR5	0X0117
#define _SCC_FD_05_TMPR7	0X011E
#define _SCC_FD_05_ED1_7942C890_N3__VA	0X0170
#define _SCC_FD_05_ED1_7942C890_N2__VA	0X0171
#define _SCC_FD_05_ED1_7942C890_N1__VA	0X0172
#define _SCC_FD_05_ED1_7942C88F_N7__VA	0X0173
#define _SCC_FD_05_ED1_7942C88F_N6__VA	0X0174
#define _SCC_FD_05_ED1_7942C88F_N5__VA	0X0175
#define _SCC_FD_05_ED1_7942C88F_N4__VA	0X0176
#define _SCC_FD_05_ED1_7942C88F_N3__VA	0X0177
#define _SCC_FD_05_ED1_7942C88F_N2__VA	0X0178
#define _SCC_FD_05_ED1_7942C88F_N1__VA	0X0179
#define _SCC_FD_05_ED1_7942C890_N8__VA	0X017A
#define _SCC_FD_05_ED1_7942C890_N7__VA	0X017B
#define _SCC_FD_05_ED1_7942C890_N6__VA	0X017C
#define _SCC_FD_05_ED1_7942C890_N5__VA	0X017D
#define _SCC_FD_05_ED1_7942C890_N4__VA	0X017E
#define _SCC_FD_05_ED1_7942C88F_N8__VA	0X017F

/* Functions */


/* Function blocks */


#define _SCC_FD_05_ED1_7942C88E	0X0005

#define _SCC_FD_05_ED1_7942C890	0X0003
#define _SCC_FD_05_ED1_7942C88F	0X0004


