/**********************************************************************/
/*                                                                    */
/*  File name : FD_01.H                                               */
/*  Date      : 11.09.2019 12:06:14                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fqdmon                                     */
/*  ISaGRAF program name : FD_01                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_01_MQ_01	0X0048
#define _SCC_FD_01_MQ_03	0X0049
#define _SCC_FD_01_ED1_7942C78C_Q_VA	0X005D
#define _SCC_FD_01_ED1_7942C78B_Q_VA	0X005E
#define _SCC_FD_01_ED1_7942C78A_B6__VA	0X005F
#define _SCC_FD_01_ED1_7942C78A_B5__VA	0X0060

/* Analogs */

#define _SCC_FD_01_W_12	0X0052
#define _SCC_FD_01_W_11	0X0053
#define _SCC_FD_01_W_10	0X0054
#define _SCC_FD_01_W_09	0X0055
#define _SCC_FD_01_W_08	0X0056
#define _SCC_FD_01_W_07	0X0057
#define _SCC_FD_01_W_06	0X0058
#define _SCC_FD_01_W_05	0X0059
#define _SCC_FD_01_W_04	0X005A
#define _SCC_FD_01_W_03	0X005B
#define _SCC_FD_01_W_02	0X005C
#define _SCC_FD_01_W_01	0X005D
#define _SCC_FD_01_W_24	0X005E
#define _SCC_FD_01_W_23	0X005F
#define _SCC_FD_01_W_22	0X0060
#define _SCC_FD_01_W_21	0X0061
#define _SCC_FD_01_W_20	0X0062
#define _SCC_FD_01_W_19	0X0063
#define _SCC_FD_01_W_18	0X0064
#define _SCC_FD_01_W_17	0X0065
#define _SCC_FD_01_TMPR1	0X0111
#define _SCC_FD_01_TMPR5	0X011B
#define _SCC_FD_01_ED1_7942C78C_N1__VA	0X0121
#define _SCC_FD_01_ED1_7942C78C_N8__VA	0X0122
#define _SCC_FD_01_ED1_7942C78C_N7__VA	0X0123
#define _SCC_FD_01_ED1_7942C78C_N6__VA	0X0124
#define _SCC_FD_01_ED1_7942C78C_N5__VA	0X0125
#define _SCC_FD_01_ED1_7942C78C_N4__VA	0X0126
#define _SCC_FD_01_ED1_7942C78C_N3__VA	0X0127
#define _SCC_FD_01_ED1_7942C78C_N2__VA	0X0128
#define _SCC_FD_01_ED1_7942C78B_N12__VA	0X0129
#define _SCC_FD_01_ED1_7942C78B_N11__VA	0X012A
#define _SCC_FD_01_ED1_7942C78B_N10__VA	0X012B
#define _SCC_FD_01_ED1_7942C78B_N9__VA	0X012C
#define _SCC_FD_01_ED1_7942C78B_N8__VA	0X012D
#define _SCC_FD_01_ED1_7942C78B_N7__VA	0X012E
#define _SCC_FD_01_ED1_7942C78B_N6__VA	0X012F
#define _SCC_FD_01_ED1_7942C78B_N5__VA	0X0130
#define _SCC_FD_01_ED1_7942C78B_N4__VA	0X0131
#define _SCC_FD_01_ED1_7942C78B_N3__VA	0X0132
#define _SCC_FD_01_ED1_7942C78B_N2__VA	0X0133
#define _SCC_FD_01_ED1_7942C78B_N1__VA	0X0134

/* Functions */


/* Function blocks */

#define _SCC_FD_01_ED1_7942C78C	0X0001
#define _SCC_FD_01_ED1_7942C78B	0X0002

#define _SCC_FD_01_ED1_7942C78A	0X0001



