/**********************************************************************/
/*                                                                    */
/*  File name : FD_03.H                                               */
/*  Date      : 11.09.2019 12:06:14                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fqdmon                                     */
/*  ISaGRAF program name : FD_03                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_03_MQ_01	0X004C
#define _SCC_FD_03_MQ_03	0X004D
#define _SCC_FD_03_ED1_7942C78E_Q_VA	0X0065
#define _SCC_FD_03_ED1_7942C78D_Q_VA	0X0066
#define _SCC_FD_03_ED1_7942C78C_B6__VA	0X0067
#define _SCC_FD_03_ED1_7942C78C_B5__VA	0X0068

/* Analogs */

#define _SCC_FD_03_W_12	0X007A
#define _SCC_FD_03_W_11	0X007B
#define _SCC_FD_03_W_10	0X007C
#define _SCC_FD_03_W_09	0X007D
#define _SCC_FD_03_W_08	0X007E
#define _SCC_FD_03_W_07	0X007F
#define _SCC_FD_03_W_06	0X0080
#define _SCC_FD_03_W_05	0X0081
#define _SCC_FD_03_W_04	0X0082
#define _SCC_FD_03_W_03	0X0083
#define _SCC_FD_03_W_02	0X0084
#define _SCC_FD_03_W_01	0X0085
#define _SCC_FD_03_W_24	0X0086
#define _SCC_FD_03_W_23	0X0087
#define _SCC_FD_03_W_22	0X0088
#define _SCC_FD_03_W_21	0X0089
#define _SCC_FD_03_W_20	0X008A
#define _SCC_FD_03_W_19	0X008B
#define _SCC_FD_03_W_18	0X008C
#define _SCC_FD_03_W_17	0X008D
#define _SCC_FD_03_TMPR1	0X010F
#define _SCC_FD_03_TMPR5	0X0119
#define _SCC_FD_03_ED1_7942C78E_N1__VA	0X014C
#define _SCC_FD_03_ED1_7942C78E_N8__VA	0X014D
#define _SCC_FD_03_ED1_7942C78E_N7__VA	0X014E
#define _SCC_FD_03_ED1_7942C78E_N6__VA	0X014F
#define _SCC_FD_03_ED1_7942C78E_N5__VA	0X0150
#define _SCC_FD_03_ED1_7942C78E_N4__VA	0X0151
#define _SCC_FD_03_ED1_7942C78E_N3__VA	0X0152
#define _SCC_FD_03_ED1_7942C78E_N2__VA	0X0153
#define _SCC_FD_03_ED1_7942C78D_N12__VA	0X0154
#define _SCC_FD_03_ED1_7942C78D_N11__VA	0X0155
#define _SCC_FD_03_ED1_7942C78D_N10__VA	0X0156
#define _SCC_FD_03_ED1_7942C78D_N9__VA	0X0157
#define _SCC_FD_03_ED1_7942C78D_N8__VA	0X0158
#define _SCC_FD_03_ED1_7942C78D_N7__VA	0X0159
#define _SCC_FD_03_ED1_7942C78D_N6__VA	0X015A
#define _SCC_FD_03_ED1_7942C78D_N5__VA	0X015B
#define _SCC_FD_03_ED1_7942C78D_N4__VA	0X015C
#define _SCC_FD_03_ED1_7942C78D_N3__VA	0X015D
#define _SCC_FD_03_ED1_7942C78D_N2__VA	0X015E
#define _SCC_FD_03_ED1_7942C78D_N1__VA	0X015F

/* Functions */


/* Function blocks */

#define _SCC_FD_03_ED1_7942C78E	0X0005
#define _SCC_FD_03_ED1_7942C78D	0X0006

#define _SCC_FD_03_ED1_7942C78C	0X0003



