/**********************************************************************/
/*                                                                    */
/*  File name : FD_15.H                                               */
/*  Date      : 11.09.2019 12:06:14                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fqdmon                                     */
/*  ISaGRAF program name : FD_15                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_15_MQ_03	0X0005
#define _SCC_FD_15_MQ_01	0X0059
#define _SCC_FD_15_ED1_7942C991_Q_VA	0X008B
#define _SCC_FD_15_ED1_7942C990_B1__VA	0X008C
#define _SCC_FD_15_ED1_7942C990_B8__VA	0X008D

/* Analogs */

#define _SCC_FD_15_ADR	0X003D
#define _SCC_FD_15_W_08	0X00DE
#define _SCC_FD_15_W_07	0X00DF
#define _SCC_FD_15_W_06	0X00E0
#define _SCC_FD_15_W_05	0X00E1
#define _SCC_FD_15_W_04	0X00E2
#define _SCC_FD_15_W_03	0X00E3
#define _SCC_FD_15_W_02	0X00E4
#define _SCC_FD_15_W_01	0X00E5
#define _SCC_FD_15_TMPR1	0X0108
#define _SCC_FD_15_TMPR7	0X011C
#define _SCC_FD_15_ED1_7942C991_N8__VA	0X01B0
#define _SCC_FD_15_ED1_7942C991_N7__VA	0X01B1
#define _SCC_FD_15_ED1_7942C991_N6__VA	0X01B2
#define _SCC_FD_15_ED1_7942C991_N5__VA	0X01B3
#define _SCC_FD_15_ED1_7942C991_N4__VA	0X01B4
#define _SCC_FD_15_ED1_7942C991_N3__VA	0X01B5
#define _SCC_FD_15_ED1_7942C991_N2__VA	0X01B6
#define _SCC_FD_15_ED1_7942C991_N1__VA	0X01B7
#define _SCC_FD_15_ED1_7942C98F_LO__VA	0X01B8

/* Functions */


/* Function blocks */

#define _SCC_FD_15_ED1_7942C991	0X000F

#define _SCC_FD_15_ED1_7942C990	0X000C



#define _SCC_FD_15_ED1_7942C98F	0X0001
