/**********************************************************************/
/*                                                                    */
/*  File name : FD_14.H                                               */
/*  Date      : 11.09.2019 12:06:14                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fqdmon                                     */
/*  ISaGRAF program name : FD_14                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_14_MQ_03	0X0006
#define _SCC_FD_14_MQ_01	0X0058
#define _SCC_FD_14_ED1_7942C991_Q_VA	0X0087
#define _SCC_FD_14_ED1_7942C990_Q_VA	0X0088
#define _SCC_FD_14_ED1_7942C98F_B4__VA	0X0089
#define _SCC_FD_14_ED1_7942C98F_B3__VA	0X008A

/* Analogs */

#define _SCC_FD_14_W_14	0X00CE
#define _SCC_FD_14_W_13	0X00CF
#define _SCC_FD_14_W_12	0X00D0
#define _SCC_FD_14_W_11	0X00D1
#define _SCC_FD_14_W_10	0X00D2
#define _SCC_FD_14_W_09	0X00D3
#define _SCC_FD_14_W_08	0X00D4
#define _SCC_FD_14_W_07	0X00D5
#define _SCC_FD_14_W_06	0X00D6
#define _SCC_FD_14_W_05	0X00D7
#define _SCC_FD_14_W_04	0X00D8
#define _SCC_FD_14_W_03	0X00D9
#define _SCC_FD_14_W_02	0X00DA
#define _SCC_FD_14_W_01	0X00DB
#define _SCC_FD_14_W_16	0X00DC
#define _SCC_FD_14_W_15	0X00DD
#define _SCC_FD_14_TMPR1	0X0109
#define _SCC_FD_14_TMPR5	0X0113
#define _SCC_FD_14_ED1_7942C991_N1__VA	0X01A0
#define _SCC_FD_14_ED1_7942C991_N8__VA	0X01A1
#define _SCC_FD_14_ED1_7942C991_N7__VA	0X01A2
#define _SCC_FD_14_ED1_7942C991_N6__VA	0X01A3
#define _SCC_FD_14_ED1_7942C991_N5__VA	0X01A4
#define _SCC_FD_14_ED1_7942C991_N4__VA	0X01A5
#define _SCC_FD_14_ED1_7942C991_N3__VA	0X01A6
#define _SCC_FD_14_ED1_7942C991_N2__VA	0X01A7
#define _SCC_FD_14_ED1_7942C990_N8__VA	0X01A8
#define _SCC_FD_14_ED1_7942C990_N7__VA	0X01A9
#define _SCC_FD_14_ED1_7942C990_N6__VA	0X01AA
#define _SCC_FD_14_ED1_7942C990_N5__VA	0X01AB
#define _SCC_FD_14_ED1_7942C990_N4__VA	0X01AC
#define _SCC_FD_14_ED1_7942C990_N3__VA	0X01AD
#define _SCC_FD_14_ED1_7942C990_N2__VA	0X01AE
#define _SCC_FD_14_ED1_7942C990_N1__VA	0X01AF

/* Functions */


/* Function blocks */

#define _SCC_FD_14_ED1_7942C991	0X000D
#define _SCC_FD_14_ED1_7942C990	0X000E

#define _SCC_FD_14_ED1_7942C98F	0X000B


#define _SCC_FD_14_ED1_7942C98E	0X0001

