/**********************************************************************/
/*                                                                    */
/*  File name : FD_12.H                                               */
/*  Date      : 11.09.2019 12:06:14                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fqdmon                                     */
/*  ISaGRAF program name : FD_12                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_12_MQ_03	0X0007
#define _SCC_FD_12_MQ_01	0X0057
#define _SCC_FD_12_ED1_7942C98E_Q_VA	0X0083
#define _SCC_FD_12_ED1_7942C98D_Q_VA	0X0084
#define _SCC_FD_12_ED1_7942C98C_B16__VA	0X0085
#define _SCC_FD_12_ED1_7942C98C_B1__VA	0X0086

/* Analogs */

#define _SCC_FD_12_W_09	0X00CA
#define _SCC_FD_12_W_03	0X00CB
#define _SCC_FD_12_W_02	0X00CC
#define _SCC_FD_12_W_01	0X00CD
#define _SCC_FD_12_TMPR1	0X010A
#define _SCC_FD_12_TMPR5	0X0114
#define _SCC_FD_12_ED1_7942C98E_N1__VA	0X019C
#define _SCC_FD_12_ED1_7942C98E_N3__VA	0X019D
#define _SCC_FD_12_ED1_7942C98E_N2__VA	0X019E
#define _SCC_FD_12_ED1_7942C98D_N1__VA	0X019F

/* Functions */


/* Function blocks */

#define _SCC_FD_12_ED1_7942C98E	0X000B
#define _SCC_FD_12_ED1_7942C98D	0X000C

#define _SCC_FD_12_ED1_7942C98C	0X000A



