/**********************************************************************/
/*                                                                    */
/*  File name : FD_16.H                                               */
/*  Date      : 11.09.2019 12:06:14                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fqdmon                                     */
/*  ISaGRAF program name : FD_16                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_16_MB1	0X005A
#define _SCC_FD_16_MB2	0X005B
#define _SCC_FD_16_ED1_7945A791_Q_VA	0X008E
#define _SCC_FD_16_ED1_7945A790_Q_VA	0X008F

/* Analogs */

#define _SCC_FD_16_W004	0X00E6
#define _SCC_FD_16_W003	0X00E7
#define _SCC_FD_16_W002	0X00E8
#define _SCC_FD_16_W001	0X00E9
#define _SCC_FD_16_S001	0X00EA
#define _SCC_FD_16_TMPR2	0X0112
#define _SCC_FD_16_ED1_7945A791_N4__VA	0X01BB
#define _SCC_FD_16_ED1_7945A791_N3__VA	0X01BC
#define _SCC_FD_16_ED1_7945A791_N2__VA	0X01BD
#define _SCC_FD_16_ED1_7945A791_N1__VA	0X01BE
#define _SCC_FD_16_ED1_7945A790_N3__VA	0X01BF
#define _SCC_FD_16_ED1_7945A790_N1__VA	0X01C0
#define _SCC_FD_16_ED1_V0001	0X01C1

/* Functions */


/* Function blocks */

#define _SCC_FD_16_ED1_7945A791	0X0010
#define _SCC_FD_16_ED1_7945A790	0X0011




