/**********************************************************************/
/*                                                                    */
/*  File name : FD_11.H                                               */
/*  Date      : 11.09.2019 12:06:14                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fqdmon                                     */
/*  ISaGRAF program name : FD_11                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_11_MQ_03	0X0008
#define _SCC_FD_11_MQ_01	0X0056
#define _SCC_FD_11_ED1_7942C98D_Q_VA	0X007F
#define _SCC_FD_11_ED1_7942C98C_Q_VA	0X0080
#define _SCC_FD_11_ED1_7942C98B_B16__VA	0X0081
#define _SCC_FD_11_ED1_7942C98B_B1__VA	0X0082

/* Analogs */

#define _SCC_FD_11_W_09	0X00C6
#define _SCC_FD_11_W_03	0X00C7
#define _SCC_FD_11_W_02	0X00C8
#define _SCC_FD_11_W_01	0X00C9
#define _SCC_FD_11_TMPR1	0X010B
#define _SCC_FD_11_TMPR5	0X0115
#define _SCC_FD_11_ED1_7942C98D_N1__VA	0X0198
#define _SCC_FD_11_ED1_7942C98D_N3__VA	0X0199
#define _SCC_FD_11_ED1_7942C98D_N2__VA	0X019A
#define _SCC_FD_11_ED1_7942C98C_N1__VA	0X019B

/* Functions */


/* Function blocks */

#define _SCC_FD_11_ED1_7942C98D	0X0009
#define _SCC_FD_11_ED1_7942C98C	0X000A

#define _SCC_FD_11_ED1_7942C98B	0X0009



