/**********************************************************************/
/*                                                                    */
/*  File name : FD_8.H                                                */
/*  Date      : 11.09.2019 12:06:14                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fqdmon                                     */
/*  ISaGRAF program name : FD_8                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_8_MQ_03	0X0004
#define _SCC_FD_8_MQ_01	0X0051
#define _SCC_FD_8_LEN08	0X0052
#define _SCC_FD_8_BCC08	0X0053
#define _SCC_FD_8_TRIP08	0X0054
#define _SCC_FD_8_ED1_7942C861_B2__VA	0X0075
#define _SCC_FD_8_ED1_7942C861_B1__VA	0X0076
#define _SCC_FD_8_ED1_7942C862_Q_VA	0X0077
#define _SCC_FD_8_ED1_7942C861_B5__VA	0X0078
#define _SCC_FD_8_ED1_7942C861_B4__VA	0X0079
#define _SCC_FD_8_ED1_7942C861_B3__VA	0X007A

/* Analogs */

#define _SCC_FD_8_W_12	0X00BE
#define _SCC_FD_8_W_11	0X00BF
#define _SCC_FD_8_W_10	0X00C0
#define _SCC_FD_8_W_09	0X00C1
#define _SCC_FD_8_TMPR1	0X0105
#define _SCC_FD_8_TMPR5	0X0107
#define _SCC_FD_8_ED1_7942C862_N4__VA	0X0190
#define _SCC_FD_8_ED1_7942C862_N3__VA	0X0191
#define _SCC_FD_8_ED1_7942C862_N2__VA	0X0192
#define _SCC_FD_8_ED1_7942C862_N1__VA	0X0193

/* Functions */


/* Function blocks */


#define _SCC_FD_8_ED1_7942C861	0X0007

#define _SCC_FD_8_ED1_7942C862	0X0007


