/**********************************************************************/
/*                                                                    */
/*  File name : FD_9.H                                                */
/*  Date      : 11.09.2019 12:06:14                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fqdmon                                     */
/*  ISaGRAF program name : FD_9                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FD_9_MQ_03	0X0003
#define _SCC_FD_9_MQ_01	0X0055
#define _SCC_FD_9_ED1_7942C864_Q_VA	0X007B
#define _SCC_FD_9_ED1_7942C863_Q_VA	0X007C
#define _SCC_FD_9_ED1_7942C862_B16__VA	0X007D
#define _SCC_FD_9_ED1_7942C862_B1__VA	0X007E

/* Analogs */

#define _SCC_FD_9_W_09	0X00C2
#define _SCC_FD_9_W_03	0X00C3
#define _SCC_FD_9_W_02	0X00C4
#define _SCC_FD_9_W_01	0X00C5
#define _SCC_FD_9_TMPR1	0X0104
#define _SCC_FD_9_TMPR5	0X0106
#define _SCC_FD_9_ED1_7942C864_N1__VA	0X0194
#define _SCC_FD_9_ED1_7942C864_N3__VA	0X0195
#define _SCC_FD_9_ED1_7942C864_N2__VA	0X0196
#define _SCC_FD_9_ED1_7942C863_N1__VA	0X0197

/* Functions */


/* Function blocks */

#define _SCC_FD_9_ED1_7942C864	0X0007
#define _SCC_FD_9_ED1_7942C863	0X0008

#define _SCC_FD_9_ED1_7942C862	0X0008



