/**********************************************************************/
/*                                                                    */
/*  File name : CTRLPTS.H                                             */
/*  Date      : 13.10.2017 14:55:19                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : kfcm                                       */
/*  ISaGRAF program name : CTRLPTS                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_CTRLPTS_ED1_E136490E_Q_VA	0X0086
#define _SCC_CTRLPTS_ED1_E136490F_Q_VA	0X0087
#define _SCC_CTRLPTS_ED1_E1364910_Q_VA	0X0088
#define _SCC_CTRLPTS_ED1_E1364911_Q_VA	0X0089
#define _SCC_CTRLPTS_ED1_V0003	0X008A
#define _SCC_CTRLPTS_ED1_V0004	0X008B
#define _SCC_CTRLPTS_ED1_V0005	0X008C
#define _SCC_CTRLPTS_ED1_V0006	0X008D
#define _SCC_CTRLPTS_ED1_E136490C_Q_VA	0X008E
#define _SCC_CTRLPTS_ED1_E136490D_Q_VA	0X008F
#define _SCC_CTRLPTS_ED1_V0001	0X0090
#define _SCC_CTRLPTS_ED1_V0002	0X0091

/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */


#define _SCC_CTRLPTS_ED1_E136490F	0X0008
#define _SCC_CTRLPTS_ED1_E1364911	0X0009
#define _SCC_CTRLPTS_ED1_E136490D	0X000A

#define _SCC_CTRLPTS_ED1_E1364910	0X0001
#define _SCC_CTRLPTS_ED1_E136490C	0X0002
#define _SCC_CTRLPTS_ED1_E136490E	0X0003









