/**********************************************************************/
/*                                                                    */
/*  File name : MANAGE.H                                              */
/*  Date      : 13.10.2017 14:55:19                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : kfcm                                       */
/*  ISaGRAF program name : MANAGE                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */












