/**********************************************************************/
/*                                                                    */
/*  File name : MUX2.H                                                */
/*  Date      : 13.10.2017 14:55:19                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : kfcm                                       */
/*  ISaGRAF program name : MUX2                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MUX2_SEL_	0X0054

/* Analogs */

#define _SCC_MUX2_IN2	0X006E
#define _SCC_MUX2_IN1	0X006F
#define _SCC_MUX2_MUX2	0X0070

/* Timers */


/* Functions */


/* Function blocks */












