/**********************************************************************/
/*                                                                    */
/*  File name : PARM_STO.H                                            */
/*  Date      : 13.10.2017 14:55:19                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : kfcm                                       */
/*  ISaGRAF program name : PARM_STO                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARM_STO_RES	0X0051
#define _SCC_PARM_STO_READ	0X0052

/* Analogs */

#define _SCC_PARM_STO_SAV_ST	0X006A

/* Timers */

#define _SCC_PARM_STO_SAV_TM	0X0008

/* Functions */


/* Function blocks */












