/**********************************************************************/
/*                                                                    */
/*  File name : PREG.H                                                */
/*  Date      : 13.10.2017 14:55:19                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : kfcm                                       */
/*  ISaGRAF program name : PREG                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PREG_AUTO_	0X0055

/* Analogs */

#define _SCC_PREG_XT_	0X006C
#define _SCC_PREG_XOUT_	0X006D
#define _SCC_PREG_XMAX_	0X0071
#define _SCC_PREG_XMIN_	0X0072
#define _SCC_PREG_P0_	0X0073
#define _SCC_PREG_KP_	0X0074
#define _SCC_PREG_X0_	0X0075
#define _SCC_PREG_SP_	0X0076
#define _SCC_PREG_PV_	0X0077
#define _SCC_PREG_TMPR3	0X00BB

/* Timers */


/* Functions */


/* Function blocks */












