/**********************************************************************/
/*                                                                    */
/*  File name : REAL_INT.H                                            */
/*  Date      : 13.10.2017 14:55:19                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : kfcm                                       */
/*  ISaGRAF program name : REAL_INT                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */












