/**********************************************************************/
/*                                                                    */
/*  File name : A4_20_TO.H                                            */
/*  Date      : 25.11.2015 15:34:46                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : gasp4                                      */
/*  ISaGRAF program name : A4_20_TO                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Messages */


/* Functions */


/* Function blocks */













