/**********************************************************************/
/*                                                                    */
/*  File name : CONTROL.H                                             */
/*  Date      : 25.11.2015 15:34:46                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : gasp4                                      */
/*  ISaGRAF program name : CONTROL                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */

#define _SCC_CONTROL_TMPR1	0X0141

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */













