/**********************************************************************/
/*                                                                    */
/*  File name : MUX2.H                                                */
/*  Date      : 25.11.2015 15:34:46                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : gasp4                                      */
/*  ISaGRAF program name : MUX2                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MUX2_SL	0X00BC

/* Analogs */

#define _SCC_MUX2_MUX2	0X00F8
#define _SCC_MUX2_IN2	0X00F9
#define _SCC_MUX2_IN1	0X00FA

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */













