/**********************************************************************/
/*                                                                    */
/*  File name : P_P0.H                                                */
/*  Date      : 25.11.2015 15:34:46                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : gasp4                                      */
/*  ISaGRAF program name : P_P0                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_P_P0_AUTO_O	0X00BD
#define _SCC_P_P0_MODE_	0X00BE
#define _SCC_P_P0_AUTO_	0X00BF

/* Analogs */

#define _SCC_P_P0_X0_O	0X00FB
#define _SCC_P_P0_SP_O	0X00FC
#define _SCC_P_P0_PV_O	0X00FD
#define _SCC_P_P0_KP_	0X00FE
#define _SCC_P_P0_X0_	0X00FF
#define _SCC_P_P0_SP_	0X0100
#define _SCC_P_P0_PV_	0X0101
#define _SCC_P_P0_P0_	0X0102
#define _SCC_P_P0_KP_O	0X0103

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */













