/**********************************************************************/
/*                                                                    */
/*  File name : PARM_RAM.H                                            */
/*  Date      : 25.11.2015 15:34:46                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : gasp4                                      */
/*  ISaGRAF program name : PARM_RAM                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARM_RAM_INIT	0X0078
#define _SCC_PARM_RAM_RES	0X00A6

/* Analogs */

#define _SCC_PARM_RAM_II	0X00D5
#define _SCC_PARM_RAM_ADR	0X00D6

/* Timers */


/* Messages */

#define _SCC_PARM_RAM_TMPM1	0X0001
#define _SCC_PARM_RAM_TMPM2	0X0002
#define _SCC_PARM_RAM_TMPM3	0X0003
#define _SCC_PARM_RAM_TMPM4	0X0004

/* Functions */


/* Function blocks */













