/**********************************************************************/
/*                                                                    */
/*  File name : TX_X.H                                                */
/*  Date      : 25.11.2015 15:34:46                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : gasp4                                      */
/*  ISaGRAF program name : TX_X                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_TX_X_RES2	0X00A8
#define _SCC_TX_X_RES1	0X00A9

/* Analogs */

#define _SCC_TX_X_LC0002	0X00F3
#define _SCC_TX_X_LC0001	0X00F4
#define _SCC_TX_X_TMPR1	0X013A

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */













