/**********************************************************************/
/*                                                                    */
/*  File name : UPDOWN.H                                              */
/*  Date      : 25.11.2015 15:34:46                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : gasp4                                      */
/*  ISaGRAF program name : UPDOWN                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_UPDOWN_DIRECT	0X00A7
#define _SCC_UPDOWN_AM_	0X00C0

/* Analogs */

#define _SCC_UPDOWN_VAL	0X00F0
#define _SCC_UPDOWN_DELTA	0X00F1
#define _SCC_UPDOWN_Q	0X00F2
#define _SCC_UPDOWN_XMAX_	0X0104
#define _SCC_UPDOWN_XMIN_	0X0105
#define _SCC_UPDOWN_X_	0X0106

/* Timers */

#define _SCC_UPDOWN_PERIOD_	0X002B

/* Messages */


/* Functions */


/* Function blocks */













