/**********************************************************************/
/*                                                                    */
/*  File name : AIRFAN.H                                              */
/*  Date      : 25.05.2020 18:25:10                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : simukot                                    */
/*  ISaGRAF program name : AIRFAN                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */

