/**********************************************************************/
/*                                                                    */
/*  File name : GAZKOLEK.H                                            */
/*  Date      : 25.05.2020 18:25:10                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : simukot                                    */
/*  ISaGRAF program name : GAZKOLEK                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */

