/**********************************************************************/
/*                                                                    */
/*  File name : UTECHKI.H                                             */
/*  Date      : 25.05.2020 18:25:10                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : simukot                                    */
/*  ISaGRAF program name : UTECHKI                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */

