/**********************************************************************/
/*                                                                    */
/*  File name : EEP_N_W.H                                             */
/*  Date      : 29.11.2013 02:18:56                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : aparat                                     */
/*  ISaGRAF program name : EEP_N_W                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Messages */


/* Functions */


/* Function blocks */











