/**********************************************************************/
/*                                                                    */
/*  File name : IOS.H                                                 */
/*  Date      : 29.11.2013 02:18:56                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : aparat                                     */
/*  ISaGRAF program name : IOS                                        */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_IOS_ED1_986A094C_B1__VA	0X0066
#define _SCC_IOS_ED1_V0001	0X0067
#define _SCC_IOS_ED1_986A094B_Q1_VA	0X0068
#define _SCC_IOS_ED1_986A095D_Q_VA	0X0069
#define _SCC_IOS_ED1_986A095E_Q_VA	0X006A
#define _SCC_IOS_ED1_986A095F_Q_VA	0X006B
#define _SCC_IOS_ED1_986A0960_Q_VA	0X006C
#define _SCC_IOS_ED1_986A0953_Q_VA	0X006D
#define _SCC_IOS_ED1_986A094F_Q_VA	0X006E
#define _SCC_IOS_ED1_986A0950_Q_VA	0X006F
#define _SCC_IOS_ED1_986A0951_Q_VA	0X0070
#define _SCC_IOS_ED1_986A0952_Q1_VA	0X0071

/* Analogs */

#define _SCC_IOS_DR	0X004B
#define _SCC_IOS_TMPR2	0X0089
#define _SCC_IOS_TMPR3	0X008A
#define _SCC_IOS_TMPR8	0X008B
#define _SCC_IOS_ED1_986A0961_XOUT__VA	0X00D9
#define _SCC_IOS_ED1_986A095A_XOUT_VA	0X00DA
#define _SCC_IOS_ED1_986A095B_XOUT_VA	0X00DB
#define _SCC_IOS_ED1_986A095C_XOUT_VA	0X00DC
#define _SCC_IOS_ED1_986A0957_XOUT_VA	0X00DD
#define _SCC_IOS_ED1_986A0958_XOUT_VA	0X00DE
#define _SCC_IOS_ED1_986A0959_XOUT_VA	0X00DF
#define _SCC_IOS_ED1_986A0954_XOUT_VA	0X00E0
#define _SCC_IOS_ED1_986A0955_XOUT_VA	0X00E1
#define _SCC_IOS_ED1_986A0956_XOUT_VA	0X00E2
#define _SCC_IOS_ED1_986A094E_F8__VA	0X00E3
#define _SCC_IOS_ED1_986A094E_F7__VA	0X00E4
#define _SCC_IOS_ED1_986A094E_F6__VA	0X00E5
#define _SCC_IOS_ED1_986A094E_F5__VA	0X00E6
#define _SCC_IOS_ED1_986A094E_F4__VA	0X00E7
#define _SCC_IOS_ED1_986A094E_F3__VA	0X00E8
#define _SCC_IOS_ED1_986A094E_F2__VA	0X00E9
#define _SCC_IOS_ED1_986A094E_F1__VA	0X00EA

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */

#define _SCC_IOS_ED1_986A094B	0X0001
#define _SCC_IOS_ED1_986A0952	0X0002

#define _SCC_IOS_ED1_986A095D	0X0001
#define _SCC_IOS_ED1_986A0950	0X0002
#define _SCC_IOS_ED1_986A0951	0X0003

#define _SCC_IOS_ED1_986A0960	0X0001
#define _SCC_IOS_ED1_986A094F	0X0002
#define _SCC_IOS_ED1_986A0953	0X0003

#define _SCC_IOS_ED1_986A0954	0X0001

#define _SCC_IOS_ED1_986A095F	0X0001

#define _SCC_IOS_ED1_986A095A	0X0001
#define _SCC_IOS_ED1_986A095B	0X0002
#define _SCC_IOS_ED1_986A095C	0X0003
#define _SCC_IOS_ED1_986A0957	0X0004
#define _SCC_IOS_ED1_986A0958	0X0005
#define _SCC_IOS_ED1_986A0959	0X0006
#define _SCC_IOS_ED1_986A0955	0X0007
#define _SCC_IOS_ED1_986A0956	0X0008

#define _SCC_IOS_ED1_986A095E	0X0001

#define _SCC_IOS_ED1_986A094C	0X0001

#define _SCC_IOS_ED1_986A094D	0X0001

#define _SCC_IOS_ED1_986A0961	0X0001

#define _SCC_IOS_ED1_986A094E	0X0001
