/**********************************************************************/
/*                                                                    */
/*  File name : PARM_STO.H                                            */
/*  Date      : 29.11.2013 02:18:56                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : aparat                                     */
/*  ISaGRAF program name : PARM_STO                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARM_STO_READ	0X0037
#define _SCC_PARM_STO_RES	0X0038

/* Analogs */

#define _SCC_PARM_STO_SAV_ST	0X004A

/* Timers */

#define _SCC_PARM_STO_SAV_TM	0X0003

/* Messages */


/* Functions */


/* Function blocks */











