/**********************************************************************/
/*                                                                    */
/*  File name : TOTIME.H                                              */
/*  Date      : 29.11.2013 02:18:56                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : aparat                                     */
/*  ISaGRAF program name : TOTIME                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_TOTIME_TMPB1	0X0073

/* Analogs */

#define _SCC_TOTIME_S_	0X0051
#define _SCC_TOTIME_M_	0X0052
#define _SCC_TOTIME_TM	0X0053
#define _SCC_TOTIME_TMPI3	0X00FA

/* Timers */


/* Messages */

#define _SCC_TOTIME_TOTIME	0X0003
#define _SCC_TOTIME_RES	0X0004
#define _SCC_TOTIME_TMPM2	0X0007
#define _SCC_TOTIME_TMPM3	0X000B
#define _SCC_TOTIME_TMPM1	0X000C

/* Functions */


/* Function blocks */











