/**********************************************************************/
/*                                                                    */
/*  File name : A4_20_TO.H                                            */
/*  Date      : 06.10.2012 11:12:38                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fpn                                        */
/*  ISaGRAF program name : A4_20_TO                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */









