/**********************************************************************/
/*                                                                    */
/*  File name : ANALOG.H                                              */
/*  Date      : 24.09.2017 10:38:18                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fpn                                        */
/*  ISaGRAF program name : ANALOG                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_ANALOG_ED1_C7ED8772_Q_VA	0X0074
#define _SCC_ANALOG_ED1_C7ED8773_Q_VA	0X0075
#define _SCC_ANALOG_ED1_C7ED8780_Q_VA	0X0076
#define _SCC_ANALOG_ED1_C7ED8781_Q_VA	0X0077
#define _SCC_ANALOG_ED1_C7ED877A_B2__VA	0X0078
#define _SCC_ANALOG_ED1_C7ED877A_B1__VA	0X0079
#define _SCC_ANALOG_ED1_C7ED877B_Q_VA	0X007A
#define _SCC_ANALOG_ED1_C7ED8778_Q_VA	0X007B
#define _SCC_ANALOG_ED1_C7ED8779_Q_VA	0X007C
#define _SCC_ANALOG_ED1_C7ED8775_Q_VA	0X007D
#define _SCC_ANALOG_ED1_C7ED8776_Q_VA	0X007E

/* Analogs */

#define _SCC_ANALOG_TMPR2	0X00C7
#define _SCC_ANALOG_TMPR3	0X00C9
#define _SCC_ANALOG_TMPR4	0X00CB
#define _SCC_ANALOG_TMPR6	0X00CD
#define _SCC_ANALOG_TMPR7	0X00CE
#define _SCC_ANALOG_ED1_C7ED8774_XOUT_VA	0X00D2
#define _SCC_ANALOG_ED1_C7ED8782_XOUT_VA	0X00D7
#define _SCC_ANALOG_ED1_C7ED877D_XOUT_VA	0X00D8
#define _SCC_ANALOG_ED1_C7ED877E_XOUT_VA	0X00D9
#define _SCC_ANALOG_ED1_C7ED877F_XOUT_VA	0X00DA
#define _SCC_ANALOG_ED1_C7ED8777_F2__VA	0X00DB
#define _SCC_ANALOG_ED1_C7ED8777_F1__VA	0X00DC
#define _SCC_ANALOG_ED1_C7ED8777_F8__VA	0X00DD
#define _SCC_ANALOG_ED1_C7ED8777_F7__VA	0X00DE
#define _SCC_ANALOG_ED1_C7ED8777_F6__VA	0X00DF
#define _SCC_ANALOG_ED1_C7ED8777_F5__VA	0X00E0
#define _SCC_ANALOG_ED1_C7ED8777_F4__VA	0X00E1
#define _SCC_ANALOG_ED1_C7ED8777_F3__VA	0X00E2

/* Timers */


/* Functions */


/* Function blocks */

#define _SCC_ANALOG_ED1_C7ED8773	0X0001
#define _SCC_ANALOG_ED1_C7ED8780	0X0002
#define _SCC_ANALOG_ED1_C7ED8779	0X0003
#define _SCC_ANALOG_ED1_C7ED8775	0X0004

#define _SCC_ANALOG_ED1_C7ED8772	0X0001
#define _SCC_ANALOG_ED1_C7ED8778	0X0002
#define _SCC_ANALOG_ED1_C7ED8776	0X0003


#define _SCC_ANALOG_ED1_C7ED8782	0X0001
#define _SCC_ANALOG_ED1_C7ED877D	0X0002
#define _SCC_ANALOG_ED1_C7ED877E	0X0003
#define _SCC_ANALOG_ED1_C7ED877F	0X0004

#define _SCC_ANALOG_ED1_C7ED8781	0X0001
#define _SCC_ANALOG_ED1_C7ED877B	0X0002

#define _SCC_ANALOG_ED1_C7ED8774	0X0001

#define _SCC_ANALOG_ED1_C7ED877C	0X0001

#define _SCC_ANALOG_ED1_C7ED877A	0X0001

#define _SCC_ANALOG_ED1_C7ED8777	0X0001
