/**********************************************************************/
/*                                                                    */
/*  File name : DISPATCH.H                                            */
/*  Date      : 24.09.2017 10:38:18                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fpn                                        */
/*  ISaGRAF program name : DISPATCH                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_DISPATCH_ED1_C7ED8B50_Q_VA	0X00A5

/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */


#define _SCC_DISPATCH_ED1_C7ED8B50	0X0022







