/**********************************************************************/
/*                                                                    */
/*  File name : DRIVER.H                                              */
/*  Date      : 24.09.2017 10:38:18                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fpn                                        */
/*  ISaGRAF program name : DRIVER                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_DRIVER_I_LOW	0X006B

/* Analogs */

#define _SCC_DRIVER_TMPR3	0X00CA

/* Timers */


/* Functions */


/* Function blocks */









