/**********************************************************************/
/*                                                                    */
/*  File name : MAIN.H                                                */
/*  Date      : 24.09.2017 10:38:18                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fpn                                        */
/*  ISaGRAF program name : MAIN                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MAIN_RE_X6B	0X0064
#define _SCC_MAIN_FE_X4B	0X0065
#define _SCC_MAIN_RE_X4B	0X0066
#define _SCC_MAIN_RE_TEST	0X0067
#define _SCC_MAIN_RE_FOTT	0X0068
#define _SCC_MAIN_RE_X_STOP	0X0069
#define _SCC_MAIN_RE_TS_LOT	0X006A

/* Analogs */

#define _SCC_MAIN_T_P_S	0X0077
#define _SCC_MAIN_K_V	0X0078
#define _SCC_MAIN_Q_M_M	0X0079
#define _SCC_MAIN_HB_1	0X007A
#define _SCC_MAIN_H0_1	0X007B
#define _SCC_MAIN_TMPR1	0X00C1
#define _SCC_MAIN_TMPR3	0X00C2
#define _SCC_MAIN_TMPR10	0X00C3
#define _SCC_MAIN_TMPR11	0X00C4
#define _SCC_MAIN_TMPR5	0X00C5
#define _SCC_MAIN_TMPR8	0X00C6
#define _SCC_MAIN_TMPR9	0X00C8

/* Timers */


/* Functions */


/* Function blocks */









