/**********************************************************************/
/*                                                                    */
/*  File name : PARM_STO.H                                            */
/*  Date      : 24.09.2017 10:38:18                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fpn                                        */
/*  ISaGRAF program name : PARM_STO                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARM_STO_RES	0X0062
#define _SCC_PARM_STO_READ	0X0063

/* Analogs */

#define _SCC_PARM_STO_SAV_ST	0X0075
#define _SCC_PARM_STO_STATUS_OLD	0X0076

/* Timers */


/* Functions */


/* Function blocks */









