/**********************************************************************/
/*                                                                    */
/*  File name : REAL_INT.H                                            */
/*  Date      : 24.09.2017 10:38:18                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : fpn                                        */
/*  ISaGRAF program name : REAL_INT                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */









