/**********************************************************************/
/*                                                                    */
/*  File name : CTRL_6.H                                              */
/*  Date      : 15.09.2018 12:03:12                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : filtr                                      */
/*  ISaGRAF program name : CTRL_6                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */

#define _SCC_CTRL_6_LS_START	0X0080

/* Timers */


/* Functions */


/* Function blocks */












