/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_3.H                                             */
/*  Date      : 15.09.2018 12:03:12                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : filtr                                      */
/*  ISaGRAF program name : FL_FB_3                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_3_ED1_9D576C95_BI5__VA	0X0136
#define _SCC_FL_FB_3_ED1_9D576C95_BI3__VA	0X0137
#define _SCC_FL_FB_3_ED1_9D576C95_BI2__VA	0X0138
#define _SCC_FL_FB_3_ED1_9D576C95_BI1__VA	0X0139
#define _SCC_FL_FB_3_ED1_9D576C95_Q__VA	0X013A
#define _SCC_FL_FB_3_ED1_9D576C96_Q__VA	0X013B
#define _SCC_FL_FB_3_ED1_9D576C94_Q_VA	0X013C
#define _SCC_FL_FB_3_ED1_9D576C91_Q_VA	0X013D
#define _SCC_FL_FB_3_ED1_9D576C92_Q_VA	0X013E
#define _SCC_FL_FB_3_ED1_9D576C93_Q_VA	0X013F
#define _SCC_FL_FB_3_ED1_9D576C8D_Q_VA	0X0140
#define _SCC_FL_FB_3_ED1_9D576C8E_Q_VA	0X0141
#define _SCC_FL_FB_3_ED1_9D576C8F_Q_VA	0X0142
#define _SCC_FL_FB_3_ED1_9D576C90_Q_VA	0X0143
#define _SCC_FL_FB_3_ED1_V0003	0X0144
#define _SCC_FL_FB_3_ED1_V0004	0X0145
#define _SCC_FL_FB_3_ED1_V0005	0X0146
#define _SCC_FL_FB_3_ED1_V0006	0X0147
#define _SCC_FL_FB_3_ED1_9D576C8B_Q_VA	0X0148
#define _SCC_FL_FB_3_ED1_9D576C8C_Q_VA	0X0149
#define _SCC_FL_FB_3_ED1_V0001	0X014A
#define _SCC_FL_FB_3_ED1_V0002	0X014B

/* Analogs */


/* Timers */

#define _SCC_FL_FB_3_ED1_9D576C91_ET_VA	0X0011
#define _SCC_FL_FB_3_ED1_9D576C90_ET_VA	0X0012

/* Functions */


/* Function blocks */



#define _SCC_FL_FB_3_ED1_9D576C94	0X0010
#define _SCC_FL_FB_3_ED1_9D576C91	0X0011
#define _SCC_FL_FB_3_ED1_9D576C92	0X0012
#define _SCC_FL_FB_3_ED1_9D576C93	0X0013
#define _SCC_FL_FB_3_ED1_9D576C8E	0X0014
#define _SCC_FL_FB_3_ED1_9D576C8F	0X0015
#define _SCC_FL_FB_3_ED1_9D576C90	0X0016

#define _SCC_FL_FB_3_ED1_9D576C8B	0X0007
#define _SCC_FL_FB_3_ED1_9D576C8C	0X0008
#define _SCC_FL_FB_3_ED1_9D576C8D	0X0009







#define _SCC_FL_FB_3_ED1_9D576C96	0X0003

#define _SCC_FL_FB_3_ED1_9D576C95	0X0003
