/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_1.H                                             */
/*  Date      : 15.09.2018 12:03:12                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : filtr                                      */
/*  ISaGRAF program name : FL_FB_1                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_1_ED1_9D576C93_BI5__VA	0X010A
#define _SCC_FL_FB_1_ED1_9D576C93_BI3__VA	0X010B
#define _SCC_FL_FB_1_ED1_9D576C93_BI2__VA	0X010C
#define _SCC_FL_FB_1_ED1_9D576C93_BI1__VA	0X010D
#define _SCC_FL_FB_1_ED1_9D576C93_Q__VA	0X010E
#define _SCC_FL_FB_1_ED1_9D576C94_Q__VA	0X010F
#define _SCC_FL_FB_1_ED1_9D576C92_Q_VA	0X0110
#define _SCC_FL_FB_1_ED1_9D576C8F_Q_VA	0X0111
#define _SCC_FL_FB_1_ED1_9D576C90_Q_VA	0X0112
#define _SCC_FL_FB_1_ED1_9D576C91_Q_VA	0X0113
#define _SCC_FL_FB_1_ED1_9D576C8B_Q_VA	0X0114
#define _SCC_FL_FB_1_ED1_9D576C8C_Q_VA	0X0115
#define _SCC_FL_FB_1_ED1_9D576C8D_Q_VA	0X0116
#define _SCC_FL_FB_1_ED1_9D576C8E_Q_VA	0X0117
#define _SCC_FL_FB_1_ED1_V0003	0X0118
#define _SCC_FL_FB_1_ED1_V0004	0X0119
#define _SCC_FL_FB_1_ED1_V0005	0X011A
#define _SCC_FL_FB_1_ED1_V0006	0X011B
#define _SCC_FL_FB_1_ED1_9D576C89_Q_VA	0X011C
#define _SCC_FL_FB_1_ED1_9D576C8A_Q_VA	0X011D
#define _SCC_FL_FB_1_ED1_V0001	0X011E
#define _SCC_FL_FB_1_ED1_V0002	0X011F

/* Analogs */


/* Timers */

#define _SCC_FL_FB_1_ED1_9D576C8F_ET_VA	0X000C
#define _SCC_FL_FB_1_ED1_9D576C8E_ET_VA	0X000D

/* Functions */


/* Function blocks */



#define _SCC_FL_FB_1_ED1_9D576C92	0X0002
#define _SCC_FL_FB_1_ED1_9D576C8F	0X0003
#define _SCC_FL_FB_1_ED1_9D576C90	0X0004
#define _SCC_FL_FB_1_ED1_9D576C91	0X0005
#define _SCC_FL_FB_1_ED1_9D576C8C	0X0006
#define _SCC_FL_FB_1_ED1_9D576C8D	0X0007
#define _SCC_FL_FB_1_ED1_9D576C8E	0X0008

#define _SCC_FL_FB_1_ED1_9D576C89	0X0001
#define _SCC_FL_FB_1_ED1_9D576C8A	0X0002
#define _SCC_FL_FB_1_ED1_9D576C8B	0X0003







#define _SCC_FL_FB_1_ED1_9D576C94	0X0001

#define _SCC_FL_FB_1_ED1_9D576C93	0X0001
