/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_8.H                                             */
/*  Date      : 15.09.2018 12:03:12                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : filtr                                      */
/*  ISaGRAF program name : FL_FB_8                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_8_ED1_9D576E9A_BI5__VA	0X01A4
#define _SCC_FL_FB_8_ED1_9D576E9A_BI3__VA	0X01A5
#define _SCC_FL_FB_8_ED1_9D576E9A_BI2__VA	0X01A6
#define _SCC_FL_FB_8_ED1_9D576E9A_BI1__VA	0X01A7
#define _SCC_FL_FB_8_ED1_9D576E9A_Q__VA	0X01A8
#define _SCC_FL_FB_8_ED1_9D576E9B_Q__VA	0X01A9
#define _SCC_FL_FB_8_ED1_9D576E99_Q_VA	0X01AA
#define _SCC_FL_FB_8_ED1_9D576E96_Q_VA	0X01AB
#define _SCC_FL_FB_8_ED1_9D576E97_Q_VA	0X01AC
#define _SCC_FL_FB_8_ED1_9D576E98_Q_VA	0X01AD
#define _SCC_FL_FB_8_ED1_9D576E92_Q_VA	0X01AE
#define _SCC_FL_FB_8_ED1_9D576E93_Q_VA	0X01AF
#define _SCC_FL_FB_8_ED1_9D576E94_Q_VA	0X01B0
#define _SCC_FL_FB_8_ED1_9D576E95_Q_VA	0X01B1
#define _SCC_FL_FB_8_ED1_V0003	0X01B2
#define _SCC_FL_FB_8_ED1_V0004	0X01B3
#define _SCC_FL_FB_8_ED1_V0005	0X01B4
#define _SCC_FL_FB_8_ED1_V0006	0X01B5
#define _SCC_FL_FB_8_ED1_9D576E90_Q_VA	0X01B6
#define _SCC_FL_FB_8_ED1_9D576E91_Q_VA	0X01B7
#define _SCC_FL_FB_8_ED1_V0001	0X01B8
#define _SCC_FL_FB_8_ED1_V0002	0X01B9

/* Analogs */


/* Timers */

#define _SCC_FL_FB_8_ED1_9D576E96_ET_VA	0X001B
#define _SCC_FL_FB_8_ED1_9D576E95_ET_VA	0X001C

/* Functions */


/* Function blocks */



#define _SCC_FL_FB_8_ED1_9D576E99	0X0033
#define _SCC_FL_FB_8_ED1_9D576E96	0X0034
#define _SCC_FL_FB_8_ED1_9D576E97	0X0035
#define _SCC_FL_FB_8_ED1_9D576E98	0X0036
#define _SCC_FL_FB_8_ED1_9D576E93	0X0037
#define _SCC_FL_FB_8_ED1_9D576E94	0X0038
#define _SCC_FL_FB_8_ED1_9D576E95	0X0039

#define _SCC_FL_FB_8_ED1_9D576E90	0X0016
#define _SCC_FL_FB_8_ED1_9D576E91	0X0017
#define _SCC_FL_FB_8_ED1_9D576E92	0X0018







#define _SCC_FL_FB_8_ED1_9D576E9B	0X0008

#define _SCC_FL_FB_8_ED1_9D576E9A	0X0008
