/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_2.H                                             */
/*  Date      : 15.09.2018 12:03:12                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : filtr                                      */
/*  ISaGRAF program name : FL_FB_2                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_2_ED1_9D576C94_BI5__VA	0X0120
#define _SCC_FL_FB_2_ED1_9D576C94_BI3__VA	0X0121
#define _SCC_FL_FB_2_ED1_9D576C94_BI2__VA	0X0122
#define _SCC_FL_FB_2_ED1_9D576C94_BI1__VA	0X0123
#define _SCC_FL_FB_2_ED1_9D576C94_Q__VA	0X0124
#define _SCC_FL_FB_2_ED1_9D576C95_Q__VA	0X0125
#define _SCC_FL_FB_2_ED1_9D576C93_Q_VA	0X0126
#define _SCC_FL_FB_2_ED1_9D576C90_Q_VA	0X0127
#define _SCC_FL_FB_2_ED1_9D576C91_Q_VA	0X0128
#define _SCC_FL_FB_2_ED1_9D576C92_Q_VA	0X0129
#define _SCC_FL_FB_2_ED1_9D576C8C_Q_VA	0X012A
#define _SCC_FL_FB_2_ED1_9D576C8D_Q_VA	0X012B
#define _SCC_FL_FB_2_ED1_9D576C8E_Q_VA	0X012C
#define _SCC_FL_FB_2_ED1_9D576C8F_Q_VA	0X012D
#define _SCC_FL_FB_2_ED1_V0003	0X012E
#define _SCC_FL_FB_2_ED1_V0004	0X012F
#define _SCC_FL_FB_2_ED1_V0005	0X0130
#define _SCC_FL_FB_2_ED1_V0006	0X0131
#define _SCC_FL_FB_2_ED1_9D576C8A_Q_VA	0X0132
#define _SCC_FL_FB_2_ED1_9D576C8B_Q_VA	0X0133
#define _SCC_FL_FB_2_ED1_V0001	0X0134
#define _SCC_FL_FB_2_ED1_V0002	0X0135

/* Analogs */


/* Timers */

#define _SCC_FL_FB_2_ED1_9D576C90_ET_VA	0X000F
#define _SCC_FL_FB_2_ED1_9D576C8F_ET_VA	0X0010

/* Functions */


/* Function blocks */



#define _SCC_FL_FB_2_ED1_9D576C93	0X0009
#define _SCC_FL_FB_2_ED1_9D576C90	0X000A
#define _SCC_FL_FB_2_ED1_9D576C91	0X000B
#define _SCC_FL_FB_2_ED1_9D576C92	0X000C
#define _SCC_FL_FB_2_ED1_9D576C8D	0X000D
#define _SCC_FL_FB_2_ED1_9D576C8E	0X000E
#define _SCC_FL_FB_2_ED1_9D576C8F	0X000F

#define _SCC_FL_FB_2_ED1_9D576C8A	0X0004
#define _SCC_FL_FB_2_ED1_9D576C8B	0X0005
#define _SCC_FL_FB_2_ED1_9D576C8C	0X0006







#define _SCC_FL_FB_2_ED1_9D576C95	0X0002

#define _SCC_FL_FB_2_ED1_9D576C94	0X0002
