/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_6.H                                             */
/*  Date      : 15.09.2018 12:03:12                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : filtr                                      */
/*  ISaGRAF program name : FL_FB_6                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_6_ED1_9D576D98_BI5__VA	0X0178
#define _SCC_FL_FB_6_ED1_9D576D98_BI3__VA	0X0179
#define _SCC_FL_FB_6_ED1_9D576D98_BI2__VA	0X017A
#define _SCC_FL_FB_6_ED1_9D576D98_BI1__VA	0X017B
#define _SCC_FL_FB_6_ED1_9D576D98_Q__VA	0X017C
#define _SCC_FL_FB_6_ED1_9D576D99_Q__VA	0X017D
#define _SCC_FL_FB_6_ED1_9D576D97_Q_VA	0X017E
#define _SCC_FL_FB_6_ED1_9D576D94_Q_VA	0X017F
#define _SCC_FL_FB_6_ED1_9D576D95_Q_VA	0X0180
#define _SCC_FL_FB_6_ED1_9D576D96_Q_VA	0X0181
#define _SCC_FL_FB_6_ED1_9D576D90_Q_VA	0X0182
#define _SCC_FL_FB_6_ED1_9D576D91_Q_VA	0X0183
#define _SCC_FL_FB_6_ED1_9D576D92_Q_VA	0X0184
#define _SCC_FL_FB_6_ED1_9D576D93_Q_VA	0X0185
#define _SCC_FL_FB_6_ED1_V0003	0X0186
#define _SCC_FL_FB_6_ED1_V0004	0X0187
#define _SCC_FL_FB_6_ED1_V0005	0X0188
#define _SCC_FL_FB_6_ED1_V0006	0X0189
#define _SCC_FL_FB_6_ED1_9D576D8E_Q_VA	0X018A
#define _SCC_FL_FB_6_ED1_9D576D8F_Q_VA	0X018B
#define _SCC_FL_FB_6_ED1_V0001	0X018C
#define _SCC_FL_FB_6_ED1_V0002	0X018D

/* Analogs */


/* Timers */

#define _SCC_FL_FB_6_ED1_9D576D94_ET_VA	0X0017
#define _SCC_FL_FB_6_ED1_9D576D93_ET_VA	0X0018

/* Functions */


/* Function blocks */



#define _SCC_FL_FB_6_ED1_9D576D97	0X0025
#define _SCC_FL_FB_6_ED1_9D576D94	0X0026
#define _SCC_FL_FB_6_ED1_9D576D95	0X0027
#define _SCC_FL_FB_6_ED1_9D576D96	0X0028
#define _SCC_FL_FB_6_ED1_9D576D91	0X0029
#define _SCC_FL_FB_6_ED1_9D576D92	0X002A
#define _SCC_FL_FB_6_ED1_9D576D93	0X002B

#define _SCC_FL_FB_6_ED1_9D576D8E	0X0010
#define _SCC_FL_FB_6_ED1_9D576D8F	0X0011
#define _SCC_FL_FB_6_ED1_9D576D90	0X0012







#define _SCC_FL_FB_6_ED1_9D576D99	0X0006

#define _SCC_FL_FB_6_ED1_9D576D98	0X0006
