/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_4.H                                             */
/*  Date      : 15.09.2018 12:03:12                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : filtr                                      */
/*  ISaGRAF program name : FL_FB_4                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_4_ED1_9D576D96_BI5__VA	0X014C
#define _SCC_FL_FB_4_ED1_9D576D96_BI3__VA	0X014D
#define _SCC_FL_FB_4_ED1_9D576D96_BI2__VA	0X014E
#define _SCC_FL_FB_4_ED1_9D576D96_BI1__VA	0X014F
#define _SCC_FL_FB_4_ED1_9D576D96_Q__VA	0X0150
#define _SCC_FL_FB_4_ED1_9D576D97_Q__VA	0X0151
#define _SCC_FL_FB_4_ED1_9D576D95_Q_VA	0X0152
#define _SCC_FL_FB_4_ED1_9D576D92_Q_VA	0X0153
#define _SCC_FL_FB_4_ED1_9D576D93_Q_VA	0X0154
#define _SCC_FL_FB_4_ED1_9D576D94_Q_VA	0X0155
#define _SCC_FL_FB_4_ED1_9D576D8E_Q_VA	0X0156
#define _SCC_FL_FB_4_ED1_9D576D8F_Q_VA	0X0157
#define _SCC_FL_FB_4_ED1_9D576D90_Q_VA	0X0158
#define _SCC_FL_FB_4_ED1_9D576D91_Q_VA	0X0159
#define _SCC_FL_FB_4_ED1_V0003	0X015A
#define _SCC_FL_FB_4_ED1_V0004	0X015B
#define _SCC_FL_FB_4_ED1_V0005	0X015C
#define _SCC_FL_FB_4_ED1_V0006	0X015D
#define _SCC_FL_FB_4_ED1_9D576D8C_Q_VA	0X015E
#define _SCC_FL_FB_4_ED1_9D576D8D_Q_VA	0X015F
#define _SCC_FL_FB_4_ED1_V0001	0X0160
#define _SCC_FL_FB_4_ED1_V0002	0X0161

/* Analogs */


/* Timers */

#define _SCC_FL_FB_4_ED1_9D576D92_ET_VA	0X0013
#define _SCC_FL_FB_4_ED1_9D576D91_ET_VA	0X0014

/* Functions */


/* Function blocks */



#define _SCC_FL_FB_4_ED1_9D576D95	0X0017
#define _SCC_FL_FB_4_ED1_9D576D92	0X0018
#define _SCC_FL_FB_4_ED1_9D576D93	0X0019
#define _SCC_FL_FB_4_ED1_9D576D94	0X001A
#define _SCC_FL_FB_4_ED1_9D576D8F	0X001B
#define _SCC_FL_FB_4_ED1_9D576D90	0X001C
#define _SCC_FL_FB_4_ED1_9D576D91	0X001D

#define _SCC_FL_FB_4_ED1_9D576D8C	0X000A
#define _SCC_FL_FB_4_ED1_9D576D8D	0X000B
#define _SCC_FL_FB_4_ED1_9D576D8E	0X000C







#define _SCC_FL_FB_4_ED1_9D576D97	0X0004

#define _SCC_FL_FB_4_ED1_9D576D96	0X0004
