/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_5.H                                             */
/*  Date      : 15.09.2018 12:03:12                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : filtr                                      */
/*  ISaGRAF program name : FL_FB_5                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_5_ED1_9D576D97_BI5__VA	0X0162
#define _SCC_FL_FB_5_ED1_9D576D97_BI3__VA	0X0163
#define _SCC_FL_FB_5_ED1_9D576D97_BI2__VA	0X0164
#define _SCC_FL_FB_5_ED1_9D576D97_BI1__VA	0X0165
#define _SCC_FL_FB_5_ED1_9D576D97_Q__VA	0X0166
#define _SCC_FL_FB_5_ED1_9D576D98_Q__VA	0X0167
#define _SCC_FL_FB_5_ED1_9D576D96_Q_VA	0X0168
#define _SCC_FL_FB_5_ED1_9D576D93_Q_VA	0X0169
#define _SCC_FL_FB_5_ED1_9D576D94_Q_VA	0X016A
#define _SCC_FL_FB_5_ED1_9D576D95_Q_VA	0X016B
#define _SCC_FL_FB_5_ED1_9D576D8F_Q_VA	0X016C
#define _SCC_FL_FB_5_ED1_9D576D90_Q_VA	0X016D
#define _SCC_FL_FB_5_ED1_9D576D91_Q_VA	0X016E
#define _SCC_FL_FB_5_ED1_9D576D92_Q_VA	0X016F
#define _SCC_FL_FB_5_ED1_V0003	0X0170
#define _SCC_FL_FB_5_ED1_V0004	0X0171
#define _SCC_FL_FB_5_ED1_V0005	0X0172
#define _SCC_FL_FB_5_ED1_V0006	0X0173
#define _SCC_FL_FB_5_ED1_9D576D8D_Q_VA	0X0174
#define _SCC_FL_FB_5_ED1_9D576D8E_Q_VA	0X0175
#define _SCC_FL_FB_5_ED1_V0001	0X0176
#define _SCC_FL_FB_5_ED1_V0002	0X0177

/* Analogs */


/* Timers */

#define _SCC_FL_FB_5_ED1_9D576D93_ET_VA	0X0015
#define _SCC_FL_FB_5_ED1_9D576D92_ET_VA	0X0016

/* Functions */


/* Function blocks */



#define _SCC_FL_FB_5_ED1_9D576D96	0X001E
#define _SCC_FL_FB_5_ED1_9D576D93	0X001F
#define _SCC_FL_FB_5_ED1_9D576D94	0X0020
#define _SCC_FL_FB_5_ED1_9D576D95	0X0021
#define _SCC_FL_FB_5_ED1_9D576D90	0X0022
#define _SCC_FL_FB_5_ED1_9D576D91	0X0023
#define _SCC_FL_FB_5_ED1_9D576D92	0X0024

#define _SCC_FL_FB_5_ED1_9D576D8D	0X000D
#define _SCC_FL_FB_5_ED1_9D576D8E	0X000E
#define _SCC_FL_FB_5_ED1_9D576D8F	0X000F







#define _SCC_FL_FB_5_ED1_9D576D98	0X0005

#define _SCC_FL_FB_5_ED1_9D576D97	0X0005
