/**********************************************************************/
/*                                                                    */
/*  File name : FL_FB_7.H                                             */
/*  Date      : 15.09.2018 12:03:12                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : filtr                                      */
/*  ISaGRAF program name : FL_FB_7                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FL_FB_7_ED1_9D576E99_BI5__VA	0X018E
#define _SCC_FL_FB_7_ED1_9D576E99_BI3__VA	0X018F
#define _SCC_FL_FB_7_ED1_9D576E99_BI2__VA	0X0190
#define _SCC_FL_FB_7_ED1_9D576E99_BI1__VA	0X0191
#define _SCC_FL_FB_7_ED1_9D576E99_Q__VA	0X0192
#define _SCC_FL_FB_7_ED1_9D576E9A_Q__VA	0X0193
#define _SCC_FL_FB_7_ED1_9D576E98_Q_VA	0X0194
#define _SCC_FL_FB_7_ED1_9D576E95_Q_VA	0X0195
#define _SCC_FL_FB_7_ED1_9D576E96_Q_VA	0X0196
#define _SCC_FL_FB_7_ED1_9D576E97_Q_VA	0X0197
#define _SCC_FL_FB_7_ED1_9D576E91_Q_VA	0X0198
#define _SCC_FL_FB_7_ED1_9D576E92_Q_VA	0X0199
#define _SCC_FL_FB_7_ED1_9D576E93_Q_VA	0X019A
#define _SCC_FL_FB_7_ED1_9D576E94_Q_VA	0X019B
#define _SCC_FL_FB_7_ED1_V0003	0X019C
#define _SCC_FL_FB_7_ED1_V0004	0X019D
#define _SCC_FL_FB_7_ED1_V0005	0X019E
#define _SCC_FL_FB_7_ED1_V0006	0X019F
#define _SCC_FL_FB_7_ED1_9D576E8F_Q_VA	0X01A0
#define _SCC_FL_FB_7_ED1_9D576E90_Q_VA	0X01A1
#define _SCC_FL_FB_7_ED1_V0001	0X01A2
#define _SCC_FL_FB_7_ED1_V0002	0X01A3

/* Analogs */


/* Timers */

#define _SCC_FL_FB_7_ED1_9D576E95_ET_VA	0X0019
#define _SCC_FL_FB_7_ED1_9D576E94_ET_VA	0X001A

/* Functions */


/* Function blocks */



#define _SCC_FL_FB_7_ED1_9D576E98	0X002C
#define _SCC_FL_FB_7_ED1_9D576E95	0X002D
#define _SCC_FL_FB_7_ED1_9D576E96	0X002E
#define _SCC_FL_FB_7_ED1_9D576E97	0X002F
#define _SCC_FL_FB_7_ED1_9D576E92	0X0030
#define _SCC_FL_FB_7_ED1_9D576E93	0X0031
#define _SCC_FL_FB_7_ED1_9D576E94	0X0032

#define _SCC_FL_FB_7_ED1_9D576E8F	0X0013
#define _SCC_FL_FB_7_ED1_9D576E90	0X0014
#define _SCC_FL_FB_7_ED1_9D576E91	0X0015







#define _SCC_FL_FB_7_ED1_9D576E9A	0X0007

#define _SCC_FL_FB_7_ED1_9D576E99	0X0007
