/**********************************************************************/
/*                                                                    */
/*  File name : MAIN.H                                                */
/*  Date      : 15.09.2018 12:03:12                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : filtr                                      */
/*  ISaGRAF program name : MAIN                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */

#define _SCC_MAIN_NF	0X0083
#define _SCC_MAIN_NC_2	0X0084
#define _SCC_MAIN_I	0X0085

/* Timers */


/* Functions */


/* Function blocks */












