/**********************************************************************/
/*                                                                    */
/*  File name : MUX2.H                                                */
/*  Date      : 15.09.2018 12:03:12                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : filtr                                      */
/*  ISaGRAF program name : MUX2                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MUX2_SL	0X00E4

/* Analogs */

#define _SCC_MUX2_MUX2	0X0086
#define _SCC_MUX2_IN2	0X0087
#define _SCC_MUX2_IN1	0X0088

/* Timers */


/* Functions */


/* Function blocks */












