/**********************************************************************/
/*                                                                    */
/*  File name : OFF_ALL.H                                             */
/*  Date      : 15.09.2018 12:03:12                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : filtr                                      */
/*  ISaGRAF program name : OFF_ALL                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_OFF_ALL_OFF_ALL	0X00E3

/* Analogs */


/* Timers */


/* Functions */


/* Function blocks */












