/**********************************************************************/
/*                                                                    */
/*  File name : PARM_STO.H                                            */
/*  Date      : 15.09.2018 12:03:12                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : filtr                                      */
/*  ISaGRAF program name : PARM_STO                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARM_STO_READ	0X00AE

/* Analogs */

#define _SCC_PARM_STO_SAV_ST	0X0074

/* Timers */

#define _SCC_PARM_STO_SAV_TM	0X0002

/* Functions */


/* Function blocks */












