/**********************************************************************/
/*                                                                    */
/*  File name : BLEDING.H                                             */
/*  Date      : 19.08.2017 11:14:05                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur2                                     */
/*  ISaGRAF program name : BLEDING                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_BLEDING_RE_TS0	0X0078
#define _SCC_BLEDING_P_06	0X0079
#define _SCC_BLEDING_P_05	0X007A
#define _SCC_BLEDING_P_04	0X007B
#define _SCC_BLEDING_P_03	0X007C
#define _SCC_BLEDING_P_02	0X007D
#define _SCC_BLEDING_P_01	0X007E

/* Analogs */

#define _SCC_BLEDING_OC_13	0X0192
#define _SCC_BLEDING_TMPR1	0X01CC

/* Timers */

#define _SCC_BLEDING_TP_06	0X0001
#define _SCC_BLEDING_TP_05	0X0002
#define _SCC_BLEDING_TP_04	0X0003
#define _SCC_BLEDING_TP_03	0X0004
#define _SCC_BLEDING_TP_02	0X0005
#define _SCC_BLEDING_TP_01	0X0006

/* Messages */


/* Functions */


/* Function blocks */












