/**********************************************************************/
/*                                                                    */
/*  File name : FLIMIT.H                                              */
/*  Date      : 19.08.2017 11:14:05                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur2                                     */
/*  ISaGRAF program name : FLIMIT                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_FLIMIT_TMPB1	0X00B8

/* Analogs */

#define _SCC_FLIMIT_FLIMIT	0X0196
#define _SCC_FLIMIT_MAX_	0X0197
#define _SCC_FLIMIT_IN	0X0198
#define _SCC_FLIMIT_MIN_	0X0199

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












