/**********************************************************************/
/*                                                                    */
/*  File name : MUX2.H                                                */
/*  Date      : 19.08.2017 11:14:05                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur2                                     */
/*  ISaGRAF program name : MUX2                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MUX2_SL	0X007F

/* Analogs */

#define _SCC_MUX2_MUX2	0X0193
#define _SCC_MUX2_IN2	0X0194
#define _SCC_MUX2_IN1	0X0195

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












