/**********************************************************************/
/*                                                                    */
/*  File name : P_P0.H                                                */
/*  Date      : 19.08.2017 11:14:05                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur2                                     */
/*  ISaGRAF program name : P_P0                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_P_P0_AUTO_O	0X0076
#define _SCC_P_P0_MODE_	0X0080
#define _SCC_P_P0_AUTO_	0X0081

/* Analogs */

#define _SCC_P_P0_X0_O	0X0189
#define _SCC_P_P0_SP_O	0X018A
#define _SCC_P_P0_PV_O	0X018B
#define _SCC_P_P0_KP_O	0X018E
#define _SCC_P_P0_KP_	0X019A
#define _SCC_P_P0_X0_	0X019B
#define _SCC_P_P0_SP_	0X019C
#define _SCC_P_P0_PV_	0X019D
#define _SCC_P_P0_P0_	0X019E

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












