/**********************************************************************/
/*                                                                    */
/*  File name : PARM_RAM.H                                            */
/*  Date      : 19.08.2017 11:14:05                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur2                                     */
/*  ISaGRAF program name : PARM_RAM                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARM_RAM_INIT	0X0064
#define _SCC_PARM_RAM_RES	0X0075

/* Analogs */

#define _SCC_PARM_RAM_II	0X0174
#define _SCC_PARM_RAM_ADR	0X0175

/* Timers */


/* Messages */

#define _SCC_PARM_RAM_TMPM1	0X0001
#define _SCC_PARM_RAM_TMPM2	0X0002
#define _SCC_PARM_RAM_TMPM3	0X0003

/* Functions */


/* Function blocks */












