/**********************************************************************/
/*                                                                    */
/*  File name : PIDMY.H                                               */
/*  Date      : 19.08.2017 11:14:05                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur2                                     */
/*  ISaGRAF program name : PIDMY                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PIDMY_AUTO_	0X0082
#define _SCC_PIDMY_MODE_	0X0083

/* Analogs */

#define _SCC_PIDMY_SUM0_	0X018C
#define _SCC_PIDMY_XOUT_	0X018D
#define _SCC_PIDMY_KE_	0X018F
#define _SCC_PIDMY_SUM_	0X0190
#define _SCC_PIDMY_XT_	0X0191
#define _SCC_PIDMY_TD_	0X019F
#define _SCC_PIDMY_TI_	0X01A0
#define _SCC_PIDMY_KP_	0X01A1
#define _SCC_PIDMY_X0_	0X01A2
#define _SCC_PIDMY_SP_	0X01A3
#define _SCC_PIDMY_PV_	0X01A4
#define _SCC_PIDMY_XMAX_	0X01A5
#define _SCC_PIDMY_XMIN_	0X01A6
#define _SCC_PIDMY_P0_	0X01A7
#define _SCC_PIDMY_TMPR3	0X01C7

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












