/**********************************************************************/
/*                                                                    */
/*  File name : RETAIN_X.H                                            */
/*  Date      : 19.08.2017 11:14:05                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : satur2                                     */
/*  ISaGRAF program name : RETAIN_X                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */


/* Analogs */


/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












