drop database if exists aparat;
create database aparat;

use aparat;

create table ap1(
Dt integer unsigned not NULL,
V_temp integer default '0',
V_vak integer default '0',
V_l integer default '0',
V_r integer default '0',
V_m integer default '0',
V_6 integer default '0',
V_7 integer default '0',
V_8 integer default '0',
X_vo integer default '0',
X_vc integer default '0',
X_vk integer default '0',
X_sir integer default '0',
X_voda integer default '0',
X_amsir integer default '0',
X_amvoda integer default '0',
X_amvk integer default '0',
X_9 integer default '0',
X_10 integer default '0',
X_11 integer default '0',
X_12 integer default '0',
X_13 integer default '0',
X_14 integer default '0',
X_15 integer default '0',
X_pusk integer default '0',
Y_sir integer default '0',
Y_voda integer default '0',
Y_vk integer default '0',
Y_4 integer default '0',
Y_5 integer default '0',
Y_6 integer default '0',
Y_7 integer default '0',
Y_alarm integer default '0',
Spr_r integer default '0',
Spr_m integer default '0',
stepR integer default '0',
Cout integer default '0',
State integer default '0',
HH integer default '0',
MM integer default '0',
a_alert integer default '0',
a_vlow integer default '0',
a_visk integer default '0',
a_kond integer default '0',
a_svk integer default '0',
a_bvk integer default '0',
a_sir integer default '0',
a_voda integer default '0',
a_r integer default '0',
a_m integer default '0',
a_t integer default '0',
primary key(Dt));


create table ap2(
Dt integer unsigned not NULL,
V_temp integer default '0',
V_vak integer default '0',
V_l integer default '0',
V_r integer default '0',
V_m integer default '0',
V_6 integer default '0',
V_7 integer default '0',
V_8 integer default '0',
X_vo integer default '0',
X_vc integer default '0',
X_vk integer default '0',
X_sir integer default '0',
X_voda integer default '0',
X_amsir integer default '0',
X_amvoda integer default '0',
X_amvk integer default '0',
X_9 integer default '0',
X_10 integer default '0',
X_11 integer default '0',
X_12 integer default '0',
X_13 integer default '0',
X_14 integer default '0',
X_15 integer default '0',
X_pusk integer default '0',
Y_sir integer default '0',
Y_voda integer default '0',
Y_vk integer default '0',
Y_4 integer default '0',
Y_5 integer default '0',
Y_6 integer default '0',
Y_7 integer default '0',
Y_alarm integer default '0',
Spr_r integer default '0',
Spr_m integer default '0',
stepR integer default '0',
Cout integer default '0',
State integer default '0',
HH integer default '0',
MM integer default '0',
a_alert integer default '0',
a_vlow integer default '0',
a_visk integer default '0',
a_kond integer default '0',
a_svk integer default '0',
a_bvk integer default '0',
a_sir integer default '0',
a_voda integer default '0',
a_r integer default '0',
a_m integer default '0',
a_t integer default '0',
primary key(Dt) ) ;

create table ap3(
Dt integer unsigned not NULL,
V_temp integer default '0',
V_vak integer default '0',
V_l integer default '0',
V_r integer default '0',
V_m integer default '0',
V_6 integer default '0',
V_7 integer default '0',
V_8 integer default '0',
X_vo integer default '0',
X_vc integer default '0',
X_vk integer default '0',
X_sir integer default '0',
X_voda integer default '0',
X_amsir integer default '0',
X_amvoda integer default '0',
X_amvk integer default '0',
X_9 integer default '0',
X_10 integer default '0',
X_11 integer default '0',
X_12 integer default '0',
X_13 integer default '0',
X_14 integer default '0',
X_15 integer default '0',
X_pusk integer default '0',
Y_sir integer default '0',
Y_voda integer default '0',
Y_vk integer default '0',
Y_4 integer default '0',
Y_5 integer default '0',
Y_6 integer default '0',
Y_7 integer default '0',
Y_alarm integer default '0',
Spr_r integer default '0',
Spr_m integer default '0',
stepR integer default '0',
Cout integer default '0',
State integer default '0',
HH integer default '0',
MM integer default '0',
a_alert integer default '0',
a_vlow integer default '0',
a_visk integer default '0',
a_kond integer default '0',
a_svk integer default '0',
a_bvk integer default '0',
a_sir integer default '0',
a_voda integer default '0',
a_r integer default '0',
a_m integer default '0',
a_t integer default '0',
primary key(Dt));


create table trend(
Dt integer unsigned not NULL,
V_01 integer default '0',
V_02 integer default '0',
V_03 integer default '0',
V_04 integer default '0',
V_05 integer default '0',
V_06 integer default '0',
V_07 integer default '0',
V_08 integer default '0',
primary key(Dt));
