/**********************************************************************/
/*                                                                    */
/*  File name : ANALOG.H                                              */
/*  Date      : 21.09.2015 21:46:02                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : rou                                        */
/*  ISaGRAF program name : ANALOG                                     */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_ANALOG_ED1_00DD0A77_Q__VA	0X0057
#define _SCC_ANALOG_ED1_00DD0A73_Q__VA	0X0058
#define _SCC_ANALOG_ED1_00DD0A87_Q_VA	0X0059
#define _SCC_ANALOG_ED1_00DD0A88_Q_VA	0X005A

/* Analogs */

#define _SCC_ANALOG_TMPR1	0X00B8
#define _SCC_ANALOG_ED1_00DD0A79_XOUT_VA	0X00C1
#define _SCC_ANALOG_ED1_00DD0A7A_XOUT_VA	0X00C2
#define _SCC_ANALOG_ED1_00DD0A7B_XOUT_VA	0X00C3
#define _SCC_ANALOG_ED1_00DD0A76_DD__VA	0X00C4
#define _SCC_ANALOG_ED1_00DD0A76_MM__VA	0X00C5
#define _SCC_ANALOG_ED1_00DD0A76_YY__VA	0X00C6
#define _SCC_ANALOG_ED1_00DD0A78_XOUT_VA	0X00C7
#define _SCC_ANALOG_ED1_00DD0A75_SS__VA	0X00C8
#define _SCC_ANALOG_ED1_00DD0A75_MM__VA	0X00C9
#define _SCC_ANALOG_ED1_00DD0A75_HH__VA	0X00CA
#define _SCC_ANALOG_ED1_00DD0A72_F1__VA	0X00CC
#define _SCC_ANALOG_ED1_00DD0A86_XOUT_VA	0X00DF
#define _SCC_ANALOG_ED1_00DD0A89_XOUT_VA	0X00E0
#define _SCC_ANALOG_ED1_00DD0A83_XOUT_VA	0X00E1
#define _SCC_ANALOG_ED1_00DD0A84_XOUT_VA	0X00E2
#define _SCC_ANALOG_ED1_00DD0A85_XOUT_VA	0X00E3
#define _SCC_ANALOG_ED1_00DD0A80_XOUT_VA	0X00E4
#define _SCC_ANALOG_ED1_00DD0A81_XOUT_VA	0X00E5
#define _SCC_ANALOG_ED1_00DD0A82_XOUT_VA	0X00E6
#define _SCC_ANALOG_ED1_00DD0A7C_XOUT_VA	0X00E7
#define _SCC_ANALOG_ED1_00DD0A7D_XOUT_VA	0X00E8
#define _SCC_ANALOG_ED1_00DD0A7E_XOUT_VA	0X00E9
#define _SCC_ANALOG_ED1_00DD0A7F_XOUT_VA	0X00EA

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */

#define _SCC_ANALOG_ED1_00DD0A87	0X0001



#define _SCC_ANALOG_ED1_00DD0A79	0X0001
#define _SCC_ANALOG_ED1_00DD0A7A	0X0002
#define _SCC_ANALOG_ED1_00DD0A7B	0X0003
#define _SCC_ANALOG_ED1_00DD0A7C	0X0004
#define _SCC_ANALOG_ED1_00DD0A78	0X0005
#define _SCC_ANALOG_ED1_00DD0A86	0X0006
#define _SCC_ANALOG_ED1_00DD0A89	0X0007
#define _SCC_ANALOG_ED1_00DD0A83	0X0008
#define _SCC_ANALOG_ED1_00DD0A84	0X0009
#define _SCC_ANALOG_ED1_00DD0A85	0X000A
#define _SCC_ANALOG_ED1_00DD0A80	0X000B
#define _SCC_ANALOG_ED1_00DD0A81	0X000C
#define _SCC_ANALOG_ED1_00DD0A82	0X000D
#define _SCC_ANALOG_ED1_00DD0A7D	0X000E
#define _SCC_ANALOG_ED1_00DD0A7E	0X000F
#define _SCC_ANALOG_ED1_00DD0A7F	0X0010

#define _SCC_ANALOG_ED1_00DD0A88	0X0001

#define _SCC_ANALOG_ED1_00DD0A77	0X0001

#define _SCC_ANALOG_ED1_00DD0A74	0X0001

#define _SCC_ANALOG_ED1_00DD0A75	0X0001

#define _SCC_ANALOG_ED1_00DD0A76	0X0001

#define _SCC_ANALOG_ED1_00DD0A72	0X0001

#define _SCC_ANALOG_ED1_00DD0A73	0X0001

