/**********************************************************************/
/*                                                                    */
/*  File name : CONTROL.H                                             */
/*  Date      : 21.09.2015 21:46:02                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : rou                                        */
/*  ISaGRAF program name : CONTROL                                    */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_CONTROL_ED1_00DD0BE7_Q_VA	0X005B
#define _SCC_CONTROL_ED1_00DD0BE5_Q_VA	0X005C
#define _SCC_CONTROL_ED1_00DD0BE1_Q_VA	0X005D
#define _SCC_CONTROL_ED1_00DD0BE2_Q_VA	0X005E
#define _SCC_CONTROL_ED1_00DD0BE3_Q_VA	0X005F
#define _SCC_CONTROL_ED1_00DD0BEF_Q_VA	0X0060
#define _SCC_CONTROL_ED1_00DD0BED_Q_VA	0X0061
#define _SCC_CONTROL_ED1_00DD0BEB_Q_VA	0X0062
#define _SCC_CONTROL_ED1_00DD0BE9_Q_VA	0X0063

/* Analogs */

#define _SCC_CONTROL_V0000	0X0094
#define _SCC_CONTROL_TMPR1	0X00B9
#define _SCC_CONTROL_TMPR11	0X00BA
#define _SCC_CONTROL_TMPR12	0X00BB
#define _SCC_CONTROL_ED1_00DD0BE6_XOUT__VA	0X00EB
#define _SCC_CONTROL_ED1_00DD0BE4_XOUT__VA	0X00EC
#define _SCC_CONTROL_ED1_V0001	0X00ED
#define _SCC_CONTROL_ED1_V0002	0X00EE
#define _SCC_CONTROL_ED1_V0003	0X00EF
#define _SCC_CONTROL_ED1_V0004	0X00F0
#define _SCC_CONTROL_ED1_V0005	0X00F1
#define _SCC_CONTROL_ED1_V0006	0X00F2
#define _SCC_CONTROL_ED1_V0007	0X00F3
#define _SCC_CONTROL_ED1_00DD0BF0_XOUT__VA	0X00FE
#define _SCC_CONTROL_ED1_00DD0BEE_XOUT__VA	0X00FF
#define _SCC_CONTROL_ED1_00DD0BEC_XOUT__VA	0X0100
#define _SCC_CONTROL_ED1_00DD0BEA_XOUT__VA	0X0101
#define _SCC_CONTROL_ED1_00DD0BE8_XOUT__VA	0X0102

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */


#define _SCC_CONTROL_ED1_00DD0BE7	0X0001
#define _SCC_CONTROL_ED1_00DD0BE5	0X0002
#define _SCC_CONTROL_ED1_00DD0BE3	0X0003
#define _SCC_CONTROL_ED1_00DD0BEF	0X0004
#define _SCC_CONTROL_ED1_00DD0BED	0X0005
#define _SCC_CONTROL_ED1_00DD0BEB	0X0006
#define _SCC_CONTROL_ED1_00DD0BE9	0X0007

#define _SCC_CONTROL_ED1_00DD0BE2	0X0001
#define _SCC_CONTROL_ED1_00DD0BE1	0X0002









#define _SCC_CONTROL_ED1_00DD0BE6	0X0001
#define _SCC_CONTROL_ED1_00DD0BE4	0X0002
#define _SCC_CONTROL_ED1_00DD0BF0	0X0003
#define _SCC_CONTROL_ED1_00DD0BEE	0X0004
#define _SCC_CONTROL_ED1_00DD0BEC	0X0005
#define _SCC_CONTROL_ED1_00DD0BEA	0X0006
#define _SCC_CONTROL_ED1_00DD0BE8	0X0007
