/**********************************************************************/
/*                                                                    */
/*  File name : MUX2.H                                                */
/*  Date      : 21.09.2015 21:46:02                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : rou                                        */
/*  ISaGRAF program name : MUX2                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_MUX2_SL	0X0043

/* Analogs */

#define _SCC_MUX2_IN2	0X0095
#define _SCC_MUX2_IN1	0X0096
#define _SCC_MUX2_MUX2	0X0097

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












