/**********************************************************************/
/*                                                                    */
/*  File name : P_P0.H                                                */
/*  Date      : 21.09.2015 21:46:02                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : rou                                        */
/*  ISaGRAF program name : P_P0                                       */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_P_P0_AUTO_O	0X0044
#define _SCC_P_P0_MODE_	0X0045
#define _SCC_P_P0_AUTO_	0X0046

/* Analogs */

#define _SCC_P_P0_KP_O	0X0098
#define _SCC_P_P0_X0_O	0X0099
#define _SCC_P_P0_SP_O	0X009A
#define _SCC_P_P0_PV_O	0X009B
#define _SCC_P_P0_KP_	0X009C
#define _SCC_P_P0_X0_	0X009D
#define _SCC_P_P0_SP_	0X009E
#define _SCC_P_P0_PV_	0X009F
#define _SCC_P_P0_P0_	0X00A0

/* Timers */


/* Messages */


/* Functions */


/* Function blocks */












