/**********************************************************************/
/*                                                                    */
/*  File name : PARM_RAM.H                                            */
/*  Date      : 21.09.2015 21:46:02                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : rou                                        */
/*  ISaGRAF program name : PARM_RAM                                   */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_PARM_RAM_INIT	0X0030
#define _SCC_PARM_RAM_RES	0X0042

/* Analogs */

#define _SCC_PARM_RAM_II	0X0091
#define _SCC_PARM_RAM_ADR	0X0092

/* Timers */


/* Messages */

#define _SCC_PARM_RAM_TMPM1	0X0001
#define _SCC_PARM_RAM_TMPM2	0X0002
#define _SCC_PARM_RAM_TMPM3	0X0003

/* Functions */


/* Function blocks */












