/**********************************************************************/
/*                                                                    */
/*  File name : appli.H                                               */
/*  Date      : 29.09.2018 17:35:35                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : test3                                      */
/*                                                                    */
/**********************************************************************/

/* Global variables of the various programs */

/* Programs */

#define _SCC_TEST	0X0001
#define _SCC_DEXPO	0X0002

/* Booleans */

#define _SCC_DUMMYCOIL	0X0001

/* Analogs */

#define _SCC_RES_	0X0001
#define _SCC_EX_	0X0002
#define _SCC_SP	0X0003
#define _SCC_PV	0X0004
#define _SCC_REAL_NULL	0X000B
#define _SCC_FBL_RET	0X000E
#define _SCC_TMPR1	0X000F
