/**********************************************************************/
/*                                                                    */
/*  File name : DEXPO.H                                               */
/*  Date      : 29.09.2018 17:35:35                                   */
/*  ----------------------------------------------------------------  */
/*  ISaGRAF project name : test3                                      */
/*  ISaGRAF program name : DEXPO                                      */
/*                                                                    */
/**********************************************************************/

/* Local variables of the program */

/* Programs */


/* Booleans */

#define _SCC_DEXPO_TMPB1	0X0002

/* Analogs */

#define _SCC_DEXPO_DEXPO	0X0005
#define _SCC_DEXPO_EXP_	0X0006
#define _SCC_DEXPO_SP_	0X0007
#define _SCC_DEXPO_PV_	0X0008
#define _SCC_DEXPO_LO	0X0009
#define _SCC_DEXPO_D_	0X000A
#define _SCC_DEXPO_TMPR1	0X000C
#define _SCC_DEXPO_TMPR3	0X000D
#define _SCC_DEXPO_TMPR2	0X0010
#define _SCC_DEXPO_TMPR4	0X0011
